### ISSUE TITLE
Refresh repository and profile by pulling down

### ISSUE THREAD

**Issue by andrewda** [gitpoint/git-point#103]
It would be nice to be able to refresh a repository or a profile by pulling down. Would be useful for updating new issues on repos or updating followers on profiles.

![pulldown.gif](https://media.giphy.com/media/14gJ2V9Sh238ZO/giphy.gif)

**Comment by housseindjirdeh** [comment]
Ooh this would definitely be nice to have. There's a `RefreshControl` method we can attach to the scrollview (http://facebook.github.io/react-native/releases/0.46/docs/scrollview.html#refreshcontrol) and when the screen is pulled we can just call the getRepository call again.

**Comment by SammyIsra** [comment]
I can try this out if no one else is already on this

**Comment by andrewda** [comment]
Awesome, thanks @SammyIsra!!
