### ISSUE TITLE
Horizontal scroll on `README.md`

### ISSUE THREAD

**Issue by vpanjganj** [gitpoint/git-point#106]
When you open a  markdown file  in the repo, while the content fit nicely on the screen, you get an annoying horizontal scrollbar.

**Comment by RolfKoenders** [comment]
Im only experiencing this on some repo's not on all. When there is a horizontal scroll bar it is not visible (only when you scroll) and its because there is code or markdown tables which take up space. 
Not sure what a solution would be. Scrolling is fine here i guess?

**Comment by machour** [comment]
Thanks a lot for your report.
This have been fixed in #236, it will be live in the next release.
