### ISSUE TITLE
Auto complete usernames in @ mentions

### ISSUE THREAD

**Issue by andrewda** [gitpoint/git-point#110]
It's difficult to type out long usernames everytime.

**Comment by housseindjirdeh** [comment]
😂 I was thinking the exact same thing this morning typing comments on my commute 😂 

This would be amazing, but not sure how we can this? Open to all kinds of ideas.

**Comment by andrewda** [comment]
Yea I kinda butchered your username in one of my comments and figured this would probably help 😆 

As for the design, the one GitHub has on web is pretty nice. Maybe above the cursor to make it less intrusive, and display the two most recent names that best fit what the user's typing. This might come in handy: http://fusejs.io/#weighted-search

**Comment by andrewda** [comment]
https://github.com/yury-dymov/react-autocomplete-input

**Comment by housseindjirdeh** [comment]
Haha I know how you feel, I've almost butchered usernames a few times already 😂 

As @RolfKoenders was kind enough to suggest: [React Native Mentions](https://github.com/harshq/react-native-mentions) looks like it might work 🎉 Once we get this up and running, definitely worth looking into getting #issues support working as well (can be a separate ticket)
