### ISSUE TITLE
Add more complete test coverage

### ISSUE THREAD

**Issue by andrewda** [gitpoint/git-point#112]
Just to make sure we don't break things 👍

**Comment by machour** [comment]
We really need tests for 1.4 development, the app is getting bigger and harder to test by hand

**Comment by andrewda** [comment]
@machour Here's the blocker: https://github.com/RealOrangeOne/react-native-mock/issues/141

**Comment by machour** [comment]
Tried to add jest tests for GithubHtmlView earlier but got that exact same problem :(

**Comment by andrewda** [comment]
@machour I got it working using a fork of `react-native-mock` in #148.
