### ISSUE TITLE
Some width problems at repository title

### ISSUE THREAD

**Issue by jstrobel** [gitpoint/git-point#114]
![img_8114](https://user-images.githubusercontent.com/1428396/28333670-edf3eb12-6bf8-11e7-9d59-da816625c9eb.PNG)

As you can see at the screenshot there are some width issues with the repository title.

**Comment by andrewda** [comment]
One option is to move the repo description down near the owner (either above or below). Not sure how that would look.

**Comment by jstrobel** [comment]
isn't there a way to set a limit for the width?

**Comment by RolfKoenders** [comment]
I think the location of the description is good. A solution could be to set a padding of like 10 to 15 pixels on both sides and expand the text view down?

**Comment by andrewda** [comment]
@RolfKoenders :+1: Yep that'd work nicely! Is there a character limit for repository descriptions?

**Comment by RolfKoenders** [comment]
@andrewda After trying it with different characters, there is no actual limit on how much you can insert/save. Github is only showing **347** characters before it cuts it of "Loru..."

**Comment by andrewda** [comment]
Alright, then does it make sense to have the text view expand dynamically?

**Comment by RolfKoenders** [comment]
I think we should decide on a limit. 1/3 of my iPhone 6(s) Plus screen is filled with the repository description with 347 characters.. Thats to much i think?

**Comment by andrewda** [comment]
Yep I agree (though I don't think there are many repos with huge descriptions). Maybe add an ellipsis after the word before the text reaches ~150 characters?

**Comment by housseindjirdeh** [comment]
So we can definitely add some padding on the sides (and we probably should) but super long descriptions can still look funky.

In the list screen long descriptions look fine in my opinion:

![image](https://user-images.githubusercontent.com/12476932/28342829-409c0752-6be8-11e7-81a9-8bc36609a9d7.png)

But in the repo screen this can be a problem:

![image](https://user-images.githubusercontent.com/12476932/28342843-4fd1ee44-6be8-11e7-8b30-0398dfa8cd6d.png)

So I think we should:

1. Add a _little_ padding (or width) so long descriptions aren't so close to the left and right edges of the screen
2. Definitely cut out descriptions after a certain point with ellipsis (~150 characters sounds fine)

**Comment by jstrobel** [comment]
Looks good for me, and cutting after some kind of characters seems fine.

**Comment by RolfKoenders** [comment]
@housseindjirdeh That sounds like a decent solution!

**Comment by Antondomashnev** [comment]
Hi there, I've made some changes to the description style in repo screen, mainly according to what @housseindjirdeh suggested. Looking forward to hearing your feedback 😉

**Comment by RolfKoenders** [comment]
@Antondomashnev I haven't checked it yet, but does your PR fixes this issue? It looks like it, except the 150 character limit.

**Comment by Antondomashnev** [comment]
@RolfKoenders yeah, instead of 150 characters limit I introduces the number of lines limit, I think it's  better, so if we change the font size of something there will be still 5 lines and maybe less than 150 characters.

**Comment by housseindjirdeh** [comment]
Thanks for your awesome fix @Antondomashnev - this is good to close :)
