### ISSUE TITLE
Display repository language

### ISSUE THREAD

**Issue by andrewda** [gitpoint/git-point#119]
The repository's primary programming language string can be found at `repository.language`.

**Comment by Antoine38660** [comment]
Do you have an idea of where you'd like to show it on a repository page?
I don't think create a new `Section` is a good idea, it takes up too much space

**Comment by andrewda** [comment]
No idea. I really like how it's displayed on the pinned repositories section on GitHub, so we could use that for reference!

**Comment by Antoine38660** [comment]
Hum, something like that ?

<img src="https://user-images.githubusercontent.com/9287184/28343827-accd37c2-6bf5-11e7-84ad-7076760fcf74.png" width="300" />

**Comment by andrewda** [comment]
Yea that looks great @Antoine38660!

**Comment by Antoine38660** [comment]
Ok, I'll try to do this one 😉 

Last one, do you have any idea about how to generate/choose the circle color ? (To be consistent with Github web)

**Comment by andrewda** [comment]
Not sure if they're necessary (though I kinda like them :wink:), but we can use https://github.com/ozh/github-colors/blob/master/colors.json

**Comment by Antoine38660** [comment]
Oh nice! There is also this one https://github.com/github/linguist/blob/master/lib/linguist/languages.yml (Officially used by Github)

**Comment by housseindjirdeh** [comment]
I already take care of language colors in the codebase, theres a langaugeColors object in the colors config file. That's how I display repository language colors in the repository list screen :)

**Comment by housseindjirdeh** [comment]
Definitely understand not needing another section list for this - but it sure if I like it hooked to the bottom of the top section. Play around with and we can easily move its location at a later point, but I'm thinking along one of the corners maybe?

**Comment by Antoine38660** [comment]
You can compare location : 

| Left aligned | Centered |
|:-:|:-:|
| ![screenshot_1500475002](https://user-images.githubusercontent.com/9287184/28372638-a9b8322c-6c76-11e7-9985-28d5c72ec0dd.png) | ![screenshot_1500475026](https://user-images.githubusercontent.com/9287184/28372639-a9bcef88-6c76-11e7-8818-22c8a9094bff.png) |

Testing on Android today, the rendering is nice :smiley:

**Comment by andrewda** [comment]
They both look good to me, but in the screenshots above I slightly prefer the centered.

**Comment by FlorianTaut** [comment]
What about putting it after "Forks" in the right-center?

**Comment by housseindjirdeh** [comment]
This is great @Antoine38660, I'm personally a fan with having it either left or right aligned instead of centered. However my bigger concern than location is adding a little padding from the edges. 

I'll leave you with the decision to either have it in the center or not :) but I think it might look a little nicer if it's not _touching_ the edges/corner and there's a little margin/padding regardless of location.

**Comment by housseindjirdeh** [comment]
Actually - I think a better place to put it would be right up top now that I think about it:

![image](https://user-images.githubusercontent.com/12476932/28387006-6c816340-6c9b-11e7-934d-6e1f0bb0b116.png)

Once the user scrolls down the sticky header would hide it anyway - but I think it can live nicely up there :D

What do you folks think?

**Comment by andrewda** [comment]
That sounds (and looks) good!

**Comment by Antoine38660** [comment]
Yes, the top centered option looks good :)
