### ISSUE TITLE
Cancelling search bar doesn't seem to clear text (Android)

### ISSUE THREAD

**Issue by housseindjirdeh** [gitpoint/git-point#120]
Our recent Android search bar implementation doesn't seem to clear text when the cancel button is clicked

**Comment by lex111** [comment]
It's strange, it works for me, on the emulator and on the phone.

**Comment by housseindjirdeh** [comment]
Hmmmm really eh, something I just noticed last night so things may have been weird. Will try again tonight.

Pressing the X clears the text just fine right?

**Comment by lex111** [comment]
> Pressing the X clears the text just fine right?

@housseindjirdeh yeah, the text is simply cleared. I would slightly increase the clickable area near the icon, but the library does not allow this.

**Comment by housseindjirdeh** [comment]
Perfect okay I have a feeling it's the Samsung S8 edge I'm testing on that's giving me a hard time clicking things that show on the edge :joy: 

Will close this and can reopen if needed. Agreed the clickable area increasing would be nice if possible.
