### ISSUE TITLE
Menlo font not applied to all code files [Android]

### ISSUE THREAD

**Issue by housseindjirdeh** [gitpoint/git-point#121]
Although the `Menlo` font comes with default in iOS devices, it doesn't for Android hence why I recently linked it to the app. Noticing something very weird where some files (`yarn.lock` for example - it seems applied but not for others 🤔 )

![image](https://user-images.githubusercontent.com/12476932/28349887-7430e9a4-6c13-11e7-8709-d8aa89b826fc.png)

![image](https://user-images.githubusercontent.com/12476932/28349906-89f1cd30-6c13-11e7-8267-fd16a2b25c70.png)

The same applies for repository code files as well as pull request diff screens

**Comment by Antoine38660** [comment]
I'll take a look during the afternoon, maybe it's caused by #60

**Comment by housseindjirdeh** [comment]
Cheers it might be but I wasn't sure - thanks matey 🙌

**Comment by Antoine38660** [comment]
Are we sure every custom fonts are rendered in Android ?

From https://github.com/gitpoint/git-point/blob/master/src/config/fonts.js#L11-L17 :
```javascript
const androidFonts = {
  fontPrimaryLight: { fontFamily: 'OpensSans-Light', fontWeight: '300' },
  fontPrimary: { fontFamily: 'OpensSans-Regular' },
  fontPrimarySemiBold: { fontFamily: 'OpensSans-SemiBold', fontWeight: '600' },
  fontPrimaryBold: { fontFamily: 'OpensSans-Bold', fontWeight: '700' },
  fontCode: { fontFamily: 'Menlo' },
};
```

All `OpenSans` fonts have a weird `s` in the javascript declaration that doesn't exist in fonts name (https://github.com/gitpoint/git-point/tree/master/android/app/src/main/assets/fonts).

**Comment by Antoine38660** [comment]
I removed these extra `s`, results are here :

| Before | After |
|:-:|:-:|
| ![screenshot_1500504737](https://user-images.githubusercontent.com/9287184/28396444-d19c3774-6cd1-11e7-8377-800f8de77b54.png) | ![screenshot_1500514090](https://user-images.githubusercontent.com/9287184/28396445-d19d00aa-6cd1-11e7-98a4-453467ff9d5a.png) |

`g` of `gitpoint` (Owner section) is different!

(Menlo is still buggy...)

**Comment by housseindjirdeh** [comment]
:disappointed: :disappointed: :disappointed: :disappointed: How did I not catch that extra S :disappointed: :disappointed: :disappointed: :disappointed:

Thanks so much for noticing mate - let me know if you notice anything fishy about the Menlo font as well

**Comment by Antoine38660** [comment]
I created a _test view_ for the fonts: 

<img width="334" alt="capture d ecran 2017-07-19 a 23 25 15" src="https://user-images.githubusercontent.com/9287184/28397691-91352f80-6cd9-11e7-91bb-add5409b2d41.png">

Menlo seems to be applied, but in a ugly way... Corrupted or incompatible`ttf`?

**Comment by housseindjirdeh** [comment]
It does look ugly :thinking: 

I can try switching it up for another `.ttf` (but feel free to try and find one if you like). I found this one here so I guess that probably wasn't a good idea :joy: https://github.com/hbin/top-programming-fonts
