### ISSUE TITLE
Render issue markdown correctly

### ISSUE THREAD

**Issue by andrewda** [gitpoint/git-point#127]
Currently issue markdown isn't rendered correctly. For example, `### Header` is shown instead of the styled header.

![0](https://user-images.githubusercontent.com/10191084/28382665-d12d856c-6c73-11e7-991c-844796f0b9f0.jpg)
*(sorry for low-quality screenshot, still working out some iOS 11 issues)*

**Comment by machour** [comment]
Implemented in #326

**Comment by machour** [comment]
Fixed in #326 !
