### ISSUE TITLE
Don't show merge button if merge is not possible

### ISSUE THREAD

**Issue by andrewda** [gitpoint/git-point#128]
Not sure how much of this data is available from the API, but the green merge button is still shown even if a PR is unable to be merged (due to conflicts or required tests not passing, for example). My suggestion would be to grey-out the merge button with a tooltip explaining why it's not mergeable.

**Comment by housseindjirdeh** [comment]
I think this is a great thing to have and _hopefully_ isn't too complicated using an API endpoint. To start things, we can just have it greyed out/disabled and if the person working on this wants to add a tooltip of sorts we can discuss that after 🙌

**Comment by chinesedfan** [comment]
The official PR API provides `mergeable` field. And now, GitPoint often treats PRs as issues.

I can fit this case based on current design, but a better way is to refactor and distinguish PRs with issues completely.
