### ISSUE TITLE
Show starred repositories

### ISSUE THREAD

**Issue by lex111** [gitpoint/git-point#129]
It was nice to show them on the profile page after the repositories :star: 

![image](https://user-images.githubusercontent.com/4408379/28383148-2c247c00-6cc9-11e7-8b08-9ee9bfbe9d82.png)

**Comment by housseindjirdeh** [comment]
An extra item to show `Stars` that takes the user to a `RepositoryListScreen` of all their starred repos? I like it, my only concern is maybe 4 items on the user profile might be cluttering things up a bit?? More than happy to see how it looks before anyone starts adding the logic 🙌

**Comment by RolfKoenders** [comment]
It will look like this:

![Star count](http://preview.ibb.co/iL5p4k/Screen_Shot_2017_07_20_at_18_41_52.png)

With more then a thousand we can do something like:

![Star count](http://preview.ibb.co/iDztVQ/Screen_Shot_2017_07_20_at_18_44_31.png)

I think it still looks good and not to cluttered, the clickable areas are still easily touchable.

**Comment by housseindjirdeh** [comment]
Nice agreed that does look good 👌🏾

**Comment by housseindjirdeh** [comment]
If it's not too difficult, let's also add navigation functionality so the user can click it and view what another user has starred as part of this ticket, hopefully the API makes this straightforward 🙌🏾

**Comment by adrianhartanto0** [comment]
Has anyone worked on this? I am more than interested to do so.

**Comment by lex111** [comment]
@adrianhartanto0 fine! We will be only happy if you do it :smiley:

**Comment by RolfKoenders** [comment]
@adrianhartanto0 Would be awesome if you do it 😉 
This can probably help you: 
https://stackoverflow.com/questions/30636798/get-user-total-starred-count-using-github-api-v3

**Comment by andrewda** [comment]
Good link @RolfKoenders! Wish GitHub would return explicit counts, though.

**Comment by adrianhartanto0** [comment]
Getting an error saying ```
"Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist".
``` while building. Tried following [here](https://github.com/facebook/react-native/issues/7308) but to no avail. Some advice?

**Comment by RolfKoenders** [comment]
@andrewda I haven't checked the v4 api yet. Maybe its in there?
