### ISSUE TITLE
Star count display

### ISSUE THREAD

**Issue by RogerAbyss** [gitpoint/git-point#136]
It`s just a small improve.
I think that star count display counld be improve like github do on website.
star:81220 shows 8.1k may look better, just like thist:
![dc8b5680-a6e1-4893-a16a-c0ec75143e18](https://user-images.githubusercontent.com/8122587/28445870-b9542b8a-6df9-11e7-847b-07badea2d50e.png)

**Comment by housseindjirdeh** [comment]
Agreed, it's a small detail but I like it 😊
