### ISSUE TITLE
Repository list for logged in user doesn't show private repos

### ISSUE THREAD

**Issue by housseindjirdeh** [gitpoint/git-point#15]
When clicking `Repositories` on the authenticated user profile screen, the list of repositories that shows is only public (unless actually searched for --> that call will show a private repo)

This is most likely due to endpoint that's hit by `getRepositories` in the `user.actions`. Although `/users/${user}/repos` is correct for other users --> we'll have to conditionally set the endpoint to be `/user/repos` for the authenticated user in order to see private repos in the list.

**Comment by krsjoseph** [comment]
Hey I'll take this issue on 👋

**Comment by housseindjirdeh** [comment]
Thank you so much, but it looks like there's a PR up for it already! Please don't hesitate to work on anything else if you would like however, and I appreciate it :)

**Comment by krsjoseph** [comment]
No worries I was view from mobile web. didn't see the referenced pr. was just looking at the tags.

**Comment by krsjoseph** [comment]
Is there a 'being worked on' or 'taken' tag? I think it'd be great so see from the issue list which issues were taken etc.

**Comment by housseindjirdeh** [comment]
There is - there's an assigned tag. Will make sure to keep them all updated :raised_hands:
