### ISSUE TITLE
Have a better 'loading' screen for users when initially loading

### ISSUE THREAD

**Issue by SammyIsra** [gitpoint/git-point#157]
When a user is initially loaded, the Repositories number is shown as `NaN` and the other counters don't even show up. They are later shifted down when the number is fetched.

![Loading User](http://i.imgur.com/GarxGmL.png)

We could probably have a `&nbsp` to avoid the shifting, and finding where the `NaN` is calculated and redoing that operation. 

The `NaN` I have not seen anywhere else when loading, but the shifting happens every time a repo or user is initially loaded.

**Comment by FlorianTaut** [comment]
We could just add a big loader in the center screen, put everything else in the background with a grey overlay. 

When everything is correctly loaded in the background we can show the user/repo. 

What about that? @Sammylsra

**Comment by andrewda** [comment]
@FlorianTaut that sounds good assuming we do it for other components too in order to maintain consistency. :+1:
