### ISSUE TITLE
Have an icon for Fork on the Repo ActionSheet menu

### ISSUE THREAD

**Issue by SammyIsra** [gitpoint/git-point#158]
The repository ActionSheet menu currently has Star/Ustar and Fork. The first option has a Star icon to accompany it, but there isn't one for Fork.

![Fork in ActionSheet](http://i.imgur.com/7ad2sD0.png)

**Comment by RolfKoenders** [comment]
I would suggest we go for the 'git-branch' icon since its really similar and there is no octicon for fork :disappointed:
https://octicons.github.com/icon/git-branch/

**Comment by andrewda** [comment]
@RolfKoenders How about [`repo-forked`](https://octicons.github.com/icon/repo-forked/)?

**Comment by SammyIsra** [comment]
Is there an example of using octicons in the project? Does anything need to
be imported?

**Comment by andrewda** [comment]
Here's [one place](https://github.com/gitpoint/git-point/blob/9ec41cf73e49c16a5a9035c49c7d7c874610614f/src/components/entity-info.component.js#L76-L80) where we use them. Not sure about getting an octicon into this text area though.

**Comment by RolfKoenders** [comment]
For some reason i couldn't find it on this page: https://octicons.github.com/ :neutral_face: :sweat_smile:

**Comment by andrewda** [comment]
@RolfKoenders yea it's not listed with the other ones that looks like it haha

**Comment by RolfKoenders** [comment]
@andrewda I seriously went 3 times through the list thinking i'm becoming blind :sweat_smile:

**Comment by RolfKoenders** [comment]
@SammyIsra Appending the icon [here](https://github.com/gitpoint/git-point/blob/master/src/repository/screens/repository.screen.js#L153) would do the Trick.

**Comment by housseindjirdeh** [comment]
So I simply append a unicode star icon for the Star action and will definitely prefer using `octicons` instead. However I'm okay if that's going to be a little more work (can ActionSheet take in a component?) to just use an appropriate 'fork' or 'branching' unicode icon for now

**Comment by housseindjirdeh** [comment]
@SammyIsra as @andrewda mentiones its quite simple to use them for `ListItem` components as well as placing `Icon` components in our app (React Native Elements, the UI library we're using, leverages `react-native-vector-icons` to have all these icons available).

But like I mentioned I'm not sure how simple it would be to have it as part of the ActionSheet hence why I think a simpler unicode icon might just be easier for now

**Comment by andrewda** [comment]
> just use an appropriate 'fork' or 'branching' unicode icon for now

Pretty sure this is the only official `fork` icon currently on unicode: 🍴

Jokes aside, I think it's probably worth the time to find an easy way to include octicons (or other icons) in the ListItem component.

**Comment by housseindjirdeh** [comment]
Haha if that's the only available unicode icon for `fork` then I agree. Will appreciate if anybody can take a look and see if adding octicons (`Icon` component) to action sheet is possible

@andrewda `ListItem` components do accept icons including octicons but you're probably referring to ActionSheet list items :)

**Comment by zcei** [comment]
Sadly, the underlaying [`UIAlertAction`](https://github.com/facebook/react-native/blob/master/Libraries/ActionSheetIOS/RCTActionSheetManager.m#L102) class (for iOS) only supports [custom images via an undocumented property](https://gist.github.com/AppleBetas/6d707e244680e2f071c09e1c9dcf478f). This is what [`react-native-actionsheet`](https://github.com/beefe/react-native-actionsheet) uses internally.

So for the unicode character I throw [OCR Fork](http://www.fileformat.info/info/unicode/char/2442/index.htm) into the discussion.

**Comment by housseindjirdeh** [comment]
Thanks a million @zcei :raised_hands: I think that icon should suffice just fine in that case

**Comment by zcei** [comment]
Fixed in https://github.com/gitpoint/git-point/commit/023c7f4ae52694f75a1bc9748b072f6f66687b0a

**Comment by housseindjirdeh** [comment]
Was just about to tag the commit :) Thanks @zcei appreciate it!
