### ISSUE TITLE
Change green number status for following/starring repos

### ISSUE THREAD

**Issue by housseindjirdeh** [gitpoint/git-point#159]
Currently if you follow a user _or_ star a repo, the followers/stars count becomes green as an indicator.

Probably not the best design decision :P - I think a simpler approach would be having a little text field underneath that shows (`Following` or `Starred`) as @Antoine38660 suggested. Definitely open to other ideas however so suggestions are welcome 🙌

**Comment by sasongkoadi** [comment]
is this issue still open? @housseindjirdeh

**Comment by housseindjirdeh** [comment]
@sasongkoadi yes it is! Please feel free to work on it if you would like :)

**Comment by sasongkoadi** [comment]
oke i handle this :) thank you @housseindjirdeh oh ya if you have any idea about this issue, you can tell me.

**Comment by sasongkoadi** [comment]
is it okay, if i'm using something like toast to solve this issue? we can use toast component from [native base](https://docs.nativebase.io/Components.html#Toast)

**Comment by reyhansofian** [comment]
@housseindjirdeh I've created a PR for this issue. please take a look

**Comment by sasongkoadi** [comment]
![screenshot from 2017-08-16 15-05-58](https://user-images.githubusercontent.com/23546252/29353666-31e63c64-8295-11e7-9fe5-68c17bd6c882.png)

How about this? @housseindjirdeh @lex111 @andrewda 
Can you give me some suggest? :smile: I'll try my best

**Comment by chinesedfan** [comment]
Hi @housseindjirdeh, I know you may be very busy everyday. But can you close those solved issues?

**Comment by machour** [comment]
Closed by #260
