### ISSUE TITLE
Crash when accessing user from main screen

### ISSUE THREAD

**Issue by andrewda** [gitpoint/git-point#162]
![unnamed](https://user-images.githubusercontent.com/10191084/28558875-c8b1b5ee-70c8-11e7-8dae-2cdea87266cf.jpg)

To replicate:

1. Go to main/home screen.
1. Click on user.

Not sure what the source is, will investigate more tomorrow.

**Comment by junedomingo** [comment]
Apologies, this was caused by #155 . It should work now :)

**Comment by andrewda** [comment]
Thanks!
