### ISSUE TITLE
Use async/await

### ISSUE THREAD

**Issue by housseindjirdeh** [gitpoint/git-point#167]
I think using async/await will be nice, should make things easier to digest in `api/index.js` 😊  

Shouldn't be too much trouble to refactor everywhere in the app that uses promises to leverage `async/await` instead but will definitely take a bit of time.

**Comment by caudaganesh** [comment]
hello Mr. @housseindjirdeh , i am new to react native and want to try to contribute to this issue, so what i have to do is to convert all promises to async/await in api/index.js is that correct? thanks before

**Comment by andrewda** [comment]
@caudaganesh Welcome! And yep, doing that should make the code a lot easier to read and process. Comment here if you have any difficulties!

**Comment by housseindjirdeh** [comment]
Thank you @caudaganesh, welcome :)

Yep just like @andrewda mentioned it's just some nice sugar over promise syntax. This ticket is pretty much replacing all the promises in that file with async/await but there are also some parent promises in some component files/action files. Just searching for `.then` should show you all the instances in the app but there are just a few that aren't in the `api/index.js` file.

**Comment by caudaganesh** [comment]
@housseindjirdeh @andrewda 
Thank you sirs, I will start working on this :) 
definitely will need some advice but i will try to work on it first. cheers

**Comment by housseindjirdeh** [comment]
I think we can close this thanks to your awesome work @caudaganesh :)
