### ISSUE TITLE
User profile description is missing

### ISSUE THREAD

**Issue by alejandronanez** [gitpoint/git-point#17]
When you open your profile, the user description is missing.

I'd love to work on this feature, let me know if I can do it.

Also, thanks for making this project, it's awesome!!!

**Comment by housseindjirdeh** [comment]
I would _love_ to have you help out with that :)

**Comment by housseindjirdeh** [comment]
Let me know how you're envisioning showing that on the screen. Also we don't show user location and I think that would be a nice to have to :) But don't worry about it if you would rather only just try showing the user profile first.

**Comment by housseindjirdeh** [comment]
User profile description* (writing these comments through the app - being able to edit posts would definitely be something we'll need to add in the future :P)

**Comment by alejandronanez** [comment]
Sounds good! Let me work on this over the week! Thanks!

**Comment by alejandronanez** [comment]
I think you should open some issues with those feautres too :)

**Comment by housseindjirdeh** [comment]
Just did :) #24

**Comment by alejandronanez** [comment]
I think you can create a label like `Assigned` or something, so people don't lose time opening issues that already have someone assigned. Just saying :)

**Comment by alejandronanez** [comment]
https://github.com/gitpoint/git-point/issues/29
