### ISSUE TITLE
Missing repository in added collaborator event

### ISSUE THREAD

**Issue by andrewda** [gitpoint/git-point#171]
What GitHub shows:

![untitled](https://user-images.githubusercontent.com/10191084/28631410-fdad8ce0-71e1-11e7-8506-3bbb56b01e49.png)

What GitPoint shows:

![0](https://user-images.githubusercontent.com/10191084/28631426-09cb2bea-71e2-11e7-9628-2a3cd46d9117.jpg)

**Comment by RolfKoenders** [comment]
I thought #149 would take care of that? Maybe its a different type of event?

**Comment by andrewda** [comment]
Forgot about this, whoops. Looks like I was using the released version of the app and not my test version which is synced with master :laughing:
