### ISSUE TITLE
Does not load all PR/Issue comments if there are too many

### ISSUE THREAD

**Issue by SammyIsra** [gitpoint/git-point#179]
When looking at the comments of a PR/Issue, there is a limit on how many comments you can see on the app. To see an example, find PR #132. 

There doesn't seem to be a way to load more comments from the app.

**Comment by andrewda** [comment]
This should be easily done with GraphQL

**Comment by housseindjirdeh** [comment]
Ah this a good catch :+1: 

So like most of the endpoints, it defaults to 30 per page and although with GraphQL this would be easier, we can add a filter it to 100 in the meantime. https://api.github.com/repos/gitpoint/git-point/issues/132/comments. Will put up a PR for this soon.

Note: Pull request comments are still not visible #6 and definitely something we need to integrate in the near future (looks like half of the conversation is missing in the app :joy: :sob: )

**Comment by housseindjirdeh** [comment]
[Extended to 100 issue comments](https://github.com/gitpoint/git-point/commit/82fcd62c281ac61ac09f1975841a85f7d57c9736)

**Comment by housseindjirdeh** [comment]
Closing this since I've extended to 100 comments. _However_, that doesn't help if issues contain more than 100 comments so definitely open to discuss how we can solve that 🤔 

Similar issue #217 open for managing how many issues/PRs show for repositories.
