### ISSUE TITLE
Show if a user is watching a repo or not

### ISSUE THREAD

**Issue by alejandronanez** [gitpoint/git-point#185]
After merging #184 you should be able to tell if you're watching a repo or not, it will be good to add a visual indicator for it.

**Comment by housseindjirdeh** [comment]
@zollero are you suggesting that we should show a list of the repositories that the user has starred?  There's an open issue to show the number of stars a user has given #129 - getting the star count isn't too trivial so I don't know how easy it would be to show the list of repositories (but definitely open to having an issue for that where we can discuss).

Also are you thinking of functionality to show previous search results? We have an open issue for that #55 :)

**Comment by SammyIsra** [comment]
So how about something simple like this? 

![Simple watching](http://i.imgur.com/SNfQ5WF.png)

But maybe under the description? Or maybe an icon somewhere else?

**Comment by alejandronanez** [comment]
I like it!
