### ISSUE TITLE
error: bundling failed: "Unable to resolve module `config`

### ISSUE THREAD

**Issue by loretoparisi** [gitpoint/git-point#189]
I can run on simulator via `yarn`, but through **Xcode** on device I get this error:

```
Loading dependency graph, done.
Bundling `index.ios.js`  0.0% (1/1130), failed.
error: bundling failed: "Unable to resolve module `config` from `/Users/loretoparisi/Documents/MyProjects/git-point/App.js`: Module does not exist in the module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\n
To resolve try the following:
\n  1. Clear watchman watches: `watchman watch-del-all`.
\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
\n  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`."
```

A link to known issue https://github.com/facebook/react-native/issues/4968 is provided in the logs.

I have tried `rm -fr $TMPDIR/react-*` but it does not work. The other suggestion was `yarn start:ios -- --reset-cache` but this to run on simulator.

**Comment by loretoparisi** [comment]
I have cleaned everything, removed the app on the **simulator** and I tried again:

```
rm -fr $TMPDIR/react-*
git clone https://github.com/gitpoint/git-point.git
cd git-point/
yarn
yarn run link
 yarn start:ios
```

The **simulator** worked. 

**NOTE**. Have an existing app on the device will cause the `red screen` seen in this bug in a fresh install. Cleaning the app from the **simulator** will fix this.

Then I have opened **Xcode** on `git-point/ios/` iOS project and run on the device. The first run it works. From the second build I get the famous `red screen`. Deleting the app on the device, does not solve the issue this time. So I had to do again from scratch to make it working on device via `Xcode`.

**Comment by housseindjirdeh** [comment]
Thanks for logging this @loretoparisi 🙌 

Have you tried running these [steps](https://github.com/gitpoint/git-point/blob/master/CONTRIBUTING.md#troubleshooting) and were you still seeing the issue? And now does the app only work when you build from XCode and not by running normally through the terminal? That's definitely an issue and we'll find out why that's happening if that's the case.

**Comment by machour** [comment]
Don't know if this might help, but I was having the exact same message on Android.

The only way to go around it was : 
```
yarn
npm install # <-- this
yarn run link
yarn start:android
```

**Comment by housseindjirdeh** [comment]
Interesting, you had to `npm install` after running `yarn` 🤔 

@loretoparisi please let us know if you're still experiencing this issue. Will close this ticket but happy to reopen it if you're still noticing it!
