### ISSUE TITLE
README Font

### ISSUE THREAD

**Issue by jstrobel** [gitpoint/git-point#196]
When i open a README file (not md) the font doesn't look like the other fonts used in the app.

**Comment by jstrobel** [comment]
![img_8142](https://user-images.githubusercontent.com/1428396/28945985-0da9ad36-78a9-11e7-9797-48126c3ead1e.PNG)

**Comment by Antoine38660** [comment]
Hey @jstrobel you're right. This one is already logged here : #85  :smile:

**Comment by housseindjirdeh** [comment]
Cheers thank you @jstrobel - we'll definitely find out why styles aren't being rendered here before our next update. Closing this since we have the duplicate :)

**Comment by jstrobel** [comment]
Sorry haven't found the other one on my search.

**Comment by housseindjirdeh** [comment]
@jstrobel no worries at all - there are a _bunch_ of issues so no need to apologize, I have a heard time finding issues on search at times :)
