### ISSUE TITLE
Non-aligned text on the home screen

### ISSUE THREAD

**Issue by introwit** [gitpoint/git-point#200]
- It would be great if the text is aligned as shown below in the image.
- The all of a sudden bulging text on the left looks odd & messy creating a bad experience.
- Aligning the text as shown would make it look neat & even.

![gpi](https://user-images.githubusercontent.com/11228182/28995796-451a7242-7a10-11e7-9d2c-104053b74fac.jpg)

PS: Please ignore the editing, did that on my phone :smile:

**Comment by lex111** [comment]
It seems to me, so it was conceived, that for the text all available width was taken away. I see it so: the `header` is the avatar and the information about the event and the `body` is the text of the event. I would leave it as it is, because then there will be a lot of free space, whereas now everything looks rather harmonious.

**Comment by introwit** [comment]
- Some free space is needed to let content breath and make it readable for the user. 
- When your text is left aligned, a straight left edge appears. Users can read each line by simply moving their eyes to the left edge each time. This makes your paragraphs faster and easier to read because the user’s eyes don’t have to work as hard to find where the line starts each time.

**Comment by lex111** [comment]
Well maybe, possibly I'm just used to how it looks now.

**Comment by introwit** [comment]
I know, that's why I am bringing the perspective of how fresh eyes would want to look at it to the table :innocent:

**Comment by housseindjirdeh** [comment]
Thanks for this @introwit, I too actually like the way it is currently as @lex111 mentioned _but_ I definitely see how aligning things might make more sense to keep things consistent.

Would love to get other people's feedback on this - suggestions/opinions are welcome 💬

**Comment by FlorianTaut** [comment]
I think it's better as it is at the moment than the opportunity suggested by @introwit

**Comment by introwit** [comment]
One needs to adapt according to the platform. Rather than writing reasons I would love if you all can spend time in other apps like twitter, YouTube , etc. and can notice the consistency yourself. If you already use such apps you would surely be able to differentiate.

**Comment by RolfKoenders** [comment]
I like the design suggestion from @introwit although we have less characters to display. I agree that it looks much better to the eye also for reading. This is actually a common pattern in other apps like you suggested. I like it! :100:

**Comment by housseindjirdeh** [comment]
@introwit thank you but I'm sure everyone here spends a decent amount of time on different platforms. Design isn't black and white - there can be different opinions :)

I happen to prefer the former look of things but we seem to have some mixed opinions :O. @andrewda , @alejandronanez , @patw0929, @Antoine38660  will love to get your quick inputs on this. If majority leans one way we'll go with that route.

**Comment by andrewda** [comment]
Not sure how I feel, tbh. I could really go either way. I think making them unaligned emphasizes that the text is the body of the issue and not an extension of the title, but I can also see how aligning them makes it look slightly more clean.

This should be like 2 lines of code changes max, so I'd love to see someone make a PR if possible with screenshots of what this might actually look like. The main thing that's turning me off from this idea is having the lines be too long, and, as @RolfKoenders having fewer characters to work with. If that's now a significant problem, I'm basically 50/50.
