### ISSUE TITLE
Code renders without newline in markdown

### ISSUE THREAD

**Issue by rkkautsar** [gitpoint/git-point#202]
I'm writing this on GitPoint so I can't upload a screenshot, but I got no-newline code when I open keajs/kea readme, for example

**Comment by rkkautsar** [comment]
[keajs/kea](https://github.com/keajs/kea)

![Screenshot](https://lh3.googleusercontent.com/XCD9K-e-IXqhmQvgyj3txlvfSsLgP2chzkLlim3wY5f96R3pzhU8RGzTNlAXqeLTE70905L15QmN_EnzO8FfKMTVy1tgNZGTuA8y3YxwRCWiaWeSjzd1qzkf3MD332pLw4SzPYdKYf0lbihSjDxkyFZkmfhCoecRrYrg2YUWgoTWrV9IFwT_6VH5SL4_Ax0EuiieVR1qqnejJ_AmE2G-Cp89gGSf2hhHrzNuCj1Xbzgm-9XVXccyMVp6wbAPY3NrysqIOiqrk0hJPIVFGmI-GD5SZK5umtE7diEtdkhwe-yM_w97hFwL8le3QsjXZiQ7_gFeAZJ4XJY7-B2xAwmkXjOX__AOO_9UyKFpdiRfID8Js5sBiMOkRST4HuRXmfWjJXXSpY3R823LQFjIatw_V4DwuxwcLouegtxLeBcr8qUu0HCaDNdc3Upk5oaBTyKlT0nyYWtuOalwEaJaTeterF7ZC2bF93NxQB7e6c8oGajF9Lf3u6iZa1dbT6Qmw3yWW7xSQYFeQUdGWlpJS8SNnNK1wCCq6cbe1o4qoTzswyAwRsvqDxWhCnHwli6mk6Ra8W9QIRYvWf1JuLVZzHFFzXFVC83GOtqu5J2lJykuz1rtcRgTbBxM-g=w540-h960-no)

**Comment by wlisrausr** [comment]
Is this issue happened in android? Because in iOS, the codes in README looks good @rkkautsar

**Comment by rkkautsar** [comment]
Yes it happened in android

**Comment by machour** [comment]
Thanks a lot for your report.
This have been fixed in #236, it will be live in the next release.
