### ISSUE TITLE
Repositories on profile page not mine

### ISSUE THREAD

**Issue by RolfKoenders** [gitpoint/git-point#205]
I have an issue with the repositories shown on my profile page. It's showing 32 which is correct. When i click on 32 its listing 33 repositories where i have push access to in alphabetic order, but it's not showing the ones I created.. and those are the ones I want to see / expect there. _I created this issue through the app and it's a bit annoying I cannot insert new lines.._

**Comment by housseindjirdeh** [comment]
Haha inserting new lines is something I struggled with as well 😂 Thank you for mentioning that here I just opened an issue for that: #206

And thanks for this, we'll find out why this is happening and it's again most likely due to our check for `push` access specifically for the authenticated user's repositories.

**Comment by blakegong** [comment]
Just saw this issue (why didn't I see this before making the PR 😂)

I had the same issue where the number on profile page does not match the number of repos in the list, and also in the list some are just repos I have push access to but not mine.

Thus #281 was made and it should have solved your issue as well (it's not released to App Store yet). Could you help to verify using latest `master` if possible?

**Comment by machour** [comment]
@RolfKoenders can you confirm this is working since #281 was merged? Thanks!

**Comment by RolfKoenders** [comment]
@machour Yes, i will check it tonight and let you know!

**Comment by RolfKoenders** [comment]
@machour Correct! It shows the correct list of repositories.

**Comment by machour** [comment]
Perfect, thanks!
