### ISSUE TITLE
Cannot add new lines when writing issue comments

### ISSUE THREAD

**Issue by housseindjirdeh** [gitpoint/git-point#206]
Feels weird that pressing return immediately posts the issue comment and there seems to be no way to insert new lines 🤔

**Comment by lex111** [comment]
@RolfKoenders how I understand this problem is relevant only for Android? This is similar to the RN bug, see details in [#12717]( https://github.com/facebook/react-native/issues/12717)

In the Android emulator, this problem can not be reproduced, because the standard keyboard is used there, but if it is not used, the addition of new lines does not work, instead a comment is sent.

On iOS, I do not know if there is such an bug, but I _think_ not, because the issue in the RN repository was only for Android.

**Comment by housseindjirdeh** [comment]
True that issue only seems to reference Android but I was actually experiencing it on my iPhone. Pressing `return` just sends the post instead of adding a new line.

I'm okay with having two separate issues if the problem is platform specific 👍

**Comment by lex111** [comment]
@housseindjirdeh on iOS it is possible to change the standard keyboard, as on Android?

**Comment by RolfKoenders** [comment]
@lex111 Im using iOS. And yeah its possible to change the behavior of the 'return' key, at least native. Probably with react-native as well.

**Comment by lex111** [comment]
@RolfKoenders ie you created the issue #205 through iOS? So, I was wrong, thinking that this is a problem of inserting new lines only on Android. I just have Android, and there's a non-standard keyboard, and I did not insert new lines either, I fixed it in #207, but this only applies to Android.

And my question was not about changing the behavior of `return` key, but changing the _keyboard_, for example in Android, I can use another keyboard (install the application and I will have another keyboard).

**Comment by RolfKoenders** [comment]
@lex111 Oh sorry, i misunderstood. Yeah its possible to change 'keyboard' i tried with the native 'dutch' & 'english' keyboards and also with the Giphy keyboard :see_no_evil: but i had no luck of new lines :disappointed:

**Comment by lex111** [comment]
@RolfKoenders but just on a standard keyboard, is there such a bug? It's strange, just on iOS should be all right, because there were problems registered only for Android, I'll look again, but I can not check :confused:

**Comment by Antoine38660** [comment]
Found it 😄 

According to the [doc](https://facebook.github.io/react-native/releases/0.47/docs/textinput.html#bluronsubmit), the `blurOnSubmit` prop disable the ability to add a newline in TextInput ([comment-input.component.js#L116](https://github.com/gitpoint/git-point/blob/master/src/components/comment-input.component.js#L116)).

I'll submit a PR
