### ISSUE TITLE
https://gitpoint.co SSL certificate broken

### ISSUE THREAD

**Issue by kamasheto** [gitpoint/git-point#21]
Getting a `NET::ERR_CERT_AUTHORITY_INVALID`

**Comment by jjperezaguinaga** [comment]
Are you talking about the website? That's weird, could you provide more info on which browser are you using? I don't have that issue on Chrome Version 59.0.3071.115 (Official Build) (64-bit).

![image](https://user-images.githubusercontent.com/1128312/28119460-39bed6bc-6715-11e7-97d2-1c895af1b208.png)

**Comment by kamasheto** [comment]
Our corporate network auto blocked it and it was not able to verify the certificate. 😅

**Comment by housseindjirdeh** [comment]
🙌  glad it wasn't something more serious :) Thanks for pinpointing this folks 👍
