### ISSUE TITLE
Show issue events

### ISSUE THREAD

**Issue by tautf** [gitpoint/git-point#212]
Hey guys,

What about adding the issue events and pr events to gitpoint?

![img_0494](https://user-images.githubusercontent.com/18403881/29004836-ab46b01c-7ace-11e7-9fa6-e25e34f34829.PNG)

So anybody knows who added the labels und requested the views and stuff.

Found this area in the api docs, that should be what is needed: https://developer.github.com/v3/issues/events/

**Comment by dzulfahmi** [comment]
Hallo, I'm interested with this issue. Can I help you?

**Comment by housseindjirdeh** [comment]
Thank you @FlorianTaut this is something we should definitely include :) Yes we would love your help @dzulfahmi!

**Comment by housseindjirdeh** [comment]
Please don't hesitate to leave screenshots/ideas/suggestions on how you think it should look - definitely open to suggestions if any kind

**Comment by housseindjirdeh** [comment]
Still think this issue is up for grabs :) Definitely something that would be awesome to have!

**Comment by brandly** [comment]
@housseindjirdeh [i started working on this](https://github.com/gitpoint/git-point/compare/master...brandly:patch-1?expand=1). does the general approach look okay?

at this point, the plumbing is in place, but the styles need some work:

![screen shot 2017-10-05 at 2 44 29 am](https://user-images.githubusercontent.com/820696/31213980-23a0fe10-a977-11e7-9126-38395c5d0738.png)

also, i have some uncommitted changes to `ios/GitPoint.xcodeproj/project.pbxproj` and `ios/GitPoint/Info.plist` involving a `Feather.ttf` file. i haven't run anything besides the regular `yarn` commands, so i'm not sure where those changes came from.

all feedback is appreciated. i'm familiar with `react`/`redux` but fairly new to `react-native`, so i bet i'll have some styling/packaging hurdles to get over. thanks in advance 🌟

**Comment by andrewda** [comment]
Looks great @brandly! One thing I'd suggest is moving the text further to the left, removing the space for the image (unless we want an image there?). Also, the "2mo" is cut off on the third event, but it shouldn't be too hard to wrap those lines!

**Comment by brandly** [comment]
what do you think of this design approach? i've still got implementation details to sort out, but i like this direction.

![screen shot 2017-10-06 at 2 33 02 am](https://user-images.githubusercontent.com/820696/31265825-c7f29240-aa3e-11e7-97fa-26b6e9643330.png)

**Comment by lex111** [comment]
@brandly Good! Why in the screenshot there is no title change event? And @andrewda  add three labels at a time, so this should be one event with three labels?

![image](https://user-images.githubusercontent.com/4408379/31267456-e06fdad4-aa80-11e7-9ad6-fb29b20c3ebc.png)

**Comment by brandly** [comment]
> Why in the screenshot there is no title change event?

it hasn't been built yet! i just wanted to confirm the approach before i did too much more.

> And @andrewda add three labels at a time, so this should be one event with three labels?

the api treats them as separate events. we could combine them if we'd like.

**Comment by lex111** [comment]
@brandly sorry, I just wanted to see what a multi-line event line would look like.

It is better to combine, of course, if several labels have been added at one time.

**Comment by brandly** [comment]
no worries! current styles aren't handling multi-line events well at all. i'll fix that before i send screenshots. i'll figure out how to combine the label events too.

now that i've got some UI pieces in place, it shouldn't take long to build out the other event components. i'm taking a break tho ✌️

**Comment by lex111** [comment]
@brandly ok, then this issue will be assigned to you.
