### ISSUE TITLE
Issue is created twice when having slow internet

### ISSUE THREAD

**Issue by FlorianTaut** [gitpoint/git-point#215]
Hey, as you can see at #213 and #214 the issue has been created twice because I'm in Italy and have a slow internet connection.

**Comment by RolfKoenders** [comment]
And you only clicked the submit button once?

**Comment by FlorianTaut** [comment]
No I clicked twice because I thought it wasn't clicked yet. Maybe we should catch the "Submit"-Signal and than disable it for 30 seconds so only one issue is created. What do you think @RolfKoenders

**Comment by RolfKoenders** [comment]
Disabling the button when its making a request is something we could definitely add and will probably help with this. It will be enabled again if there was a network timeout. I actually can't remember if there is a loader or spinner shown when the submit button is pressed, that also gives the user the feeling that there is something going on and may prevent the user from clicking again.

**Comment by FlorianTaut** [comment]
@RolfKoenders there is nothing shown to the users. Because the click isn't really visible because the onclick "color change" is just in a light grey and not really got recognize

**Comment by FlorianTaut** [comment]
@RolfKoenders we could show a loading spinner till the result of the POST is there. What do you think
