### ISSUE TITLE
GitPoint has stopped

### ISSUE THREAD

**Issue by frodinm** [gitpoint/git-point#219]
I found a bug when attempting to understand issue #109 . I was able to make the app crash 3 times using similar sequences of actions.

Video demonstration 
https://youtu.be/twoeLb9rhXU

Are we able to force close the webview window one the signout call is done?

**Comment by frodinm** [comment]
The first time i encountered this bug it was on the development app, which gave me this error screen : 
![screenshot_20170807-151855 2](https://user-images.githubusercontent.com/24626633/29045215-ba0cef36-7b90-11e7-8a02-315f5f36d110.jpg)

I dont think the webview is the issue here anymore.

**Comment by lex111** [comment]
> Video demonstration
https://youtu.be/twoeLb9rhXU

@frodinm thanks for the demo! This bug has already been described in #182.

**Comment by frodinm** [comment]
oh prefect :smile:

**Comment by machour** [comment]
Closing in favor of #182
