### ISSUE TITLE
NavBar margin-bottom is missing?

### ISSUE THREAD

**Issue by nikolaevigor** [gitpoint/git-point#22]
Seems like labels here is not centered vertically imo
iOS 11, latest public beta atm.

![2017-07-12 17 50 18](https://user-images.githubusercontent.com/3702281/28124125-78d9076c-672b-11e7-8785-ef904b23b662.jpg)
Nice app though :)

**Comment by housseindjirdeh** [comment]
Cheers that's a good catch - definitely a tiny thing we can fix

And thank you :)

**Comment by miotke** [comment]
I'll try and look at this today, probably on the bus ride home 🚌

**Comment by andrewda** [comment]
#125 should have fixed this :)
