### ISSUE TITLE
Implement use of the in-app web view on Android

### ISSUE THREAD

**Issue by introwit** [gitpoint/git-point#221]
**Current process:**
- Right now, when a user clicks on the `Sign In` button, the browser is fired up and the user needs to complete the GitHub authentication in the browser window.

**Problem:**
- In the practical sense using this flow, GitPoint is dependent on an another app to let users start using it.
- This creates problems for our app which are out of our own control.
- What if the browser doesn't fire up for some reason or there are any other issues?
- @mathieutu have faced one such [issue](https://github.com/gitpoint/git-point/issues/199) already.
- There might be others who haven't reported it and directly uninstalled our app.

**Solution:**
- Using the [Android System Webview](https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en)
- There are alternatives for this as well, which I won't suggest because as @housseindjirdeh says things are not always black and white so would leave this upto the developer's preferences :smile:

**Comment by andrewda** [comment]
Not sure if this is about what we want: https://github.com/lucasferreira/react-native-webview-android

**Comment by housseindjirdeh** [comment]
I was looking for something _exactly_ like this. I agree - opening a separate application to allow the user to login is definitely not the smoothest flow :)

Opened a separate issue to address this earlier #109 but will close that one and leave this open. @introwit thank you, and not at all please don't hesitate to leave as many alternatives as you like!! The more we discuss, the more we discover.

Not sure if that exact library would suit our needs exactly but it looks very promising 🎉

**Comment by housseindjirdeh** [comment]
If no one picks it up sooner, this will be the next thing I work on. Hopefully will have it implemented within the next few days 🙌

**Comment by machour** [comment]
Fixed in #323
