### ISSUE TITLE
Change ordering of repository actions

### ISSUE THREAD

**Issue by andrewda** [gitpoint/git-point#224]
At the moment, the order goes:
- `Star`
- `Fork`
- `Share`
- `Watch`

`Share` is the only one that's different from the others in that it doesn't take any action on the repository itself. It would be good to move `Share` to the bottom, beneath `Watch` to organize them correctly.

Probably best suited for another PR, but maybe take away the emojis from the Repository Actions menu. Until we get a way to use actual icons, these look weird IMO.

![unnamed](https://user-images.githubusercontent.com/10191084/29092278-b41babd0-7c3a-11e7-821a-0f7af2d647e6.jpg)

**Comment by lex111** [comment]
I agree, good suggestion :+1: 

Btw, my `Share` and `Watch` icons are displayed like this:
![image](https://user-images.githubusercontent.com/4408379/29133140-2d514234-7d3b-11e7-87a4-f5870e559f65.png)

**Comment by housseindjirdeh** [comment]
Agreed, let's remove the icons entirely for the moment. They do look kind of funky since the icon formats don't match. I'm okay with having it as part of this PR or a separate one. I also
