### ISSUE TITLE
Unexpected reload the app

### ISSUE THREAD

**Issue by lex111** [gitpoint/git-point#225]
Using an application on Android, I encountered one unpleasant thing: with active use, the application suddenly restarts, without displaying any error.

I tried to shoot a video, what actions lead to this, it turned out not a complete video because when the GitPoint reloads (crashed), [application for record video](https://play.google.com/store/apps/details?id=com.mobeyoapps.screenrecorder) cease to work, but the video was saved when it was crashed (which is good, not many applications are so able). This is probably an error, due to which the application reloads, I think.

Look, please, [the video](https://drive.google.com/file/d/0Bw7RZCtgPVjiUWtuSmFZckV2NjA/view?usp=sharing) (video suddenly breaks due to a crash app). I just look at the user profiles and look at the issues on the event screen, just like that, in a random order, to show that the application is rebooting due to the fact that too much I'm browsing through users and issues.

Why is this happening? Lack of memory? As I assume, there is not enough memory, because the storage is full of information (user's browsing history and issues? Can not the store contain data about all users viewed and issues?) And the system does not have enough memory and the application crashes and restarts. What other options are there?

Try also, just open the problems and user profiles that you within 3-4 minutes, will you have to restart (crash) the application? In the simulator, there is no such problem.

**Comment by lex111** [comment]
The application reloaded again, but this time I looked through only one user profile and 2 issues. It's unclear why this happens, only I have this one problem?

**Comment by lex111** [comment]
@housseindjirdeh @andrewda @alejandronanez what do you think about that? Do you have a similar problem?

**Comment by chinesedfan** [comment]
@lex111 I notice that you visited issue#8054 of some repository at the last part of the video, which has no issue description. Maybe #320 helps.
