### ISSUE TITLE
Crashing on PR opening

### ISSUE THREAD

**Issue by nikolaevigor** [gitpoint/git-point#23]
App has crashed on taping on "Add carousel"
iOS 11, latest public beta atm

Video attached
[2017-07-12 17.54.24.MOV.zip](https://github.com/gitpoint/git-point/files/1142389/2017-07-12.17.54.24.MOV.zip)

**Comment by housseindjirdeh** [comment]
Oooh do you know what might be triggering this by any chance? Hard to tell from the video but I assume this happens when you tap to open the PR right?

Thanks so much for logging this 🙌

**Comment by nikolaevigor** [comment]
Yes, I tapped here
![screenshot at jul 13 00-36-54](https://user-images.githubusercontent.com/3702281/28141011-67b186ca-6763-11e7-864e-f0a1dbd6d174.png)

**Comment by housseindjirdeh** [comment]
Sorry for keeping this open for so long @nikolaevigor :disappointed: 

So I think we resolved this as a `RawText ''` error was popping up in numerous screens. Clicking more than a few pull requests and it seems to work fine now. Please let me know if you happen to see it crashing at any screen
