### ISSUE TITLE
Add French translations

### ISSUE THREAD

**Issue by housseindjirdeh** [gitpoint/git-point#230]
:fr:

@Antoine38660: @machour has asked to work on French translations, let us know if that's okay :)

**Comment by housseindjirdeh** [comment]
Instructions to add a new language are [here](https://github.com/gitpoint/git-point/issues/233#issuecomment-321917690} 🎉

**Comment by machour** [comment]
@Antoine38660 I did a first translation in my fork (I might have missed a spot or two, and some contexts).

Could you review it? I'll provide a PR if you're okay with my work on it: 
  https://github.com/machour/git-point/tree/230-add-french-translations

Some french translation that you might want to discuss:

Kept the english form for:
  * pull request
  * followers
  * following

Used franglishe for:
  * forké
  * squasher

Translated:
  * repository => dépôt
  * merge => fusionner

**Comment by Antoine38660** [comment]
Nice, Good work ! 👍 😄 

Could you submit the PR ? It'll be easier to comment line by line.

**Comment by Antoine38660** [comment]
I agree with *repository => dépôt* mais **fusionner** pour **merge** ça fait bizarre... Je pense qu'on peux laisser celui-ci en Anglais 😄

**Comment by machour** [comment]
The translation looks pretty good to me, and is in sync with last work conducted on #193 
Maybe it's time to merge the first translation ? 😄
