### ISSUE TITLE
Add Dutch translations

### ISSUE THREAD

**Issue by housseindjirdeh** [gitpoint/git-point#232]
🇳🇱 

@RolfKoenders tagged this as assigned but please don't worry about working on this until whenever you like. Also please don't hesitate to not do this at all if you don't want to :)

Instructions to add a new language are [here](https://github.com/gitpoint/git-point/issues/233#issuecomment-321917690) :)

**Comment by SammyIsra** [comment]
Quick comment, I don't know Dutch.

**Comment by housseindjirdeh** [comment]
Haha I'm so sorry I meant to tag @RolfKoenders 😭 

I was hoping you didn't get the notification when I tagged you, my apologies :O. Meant to tag you in the Spanish translations ticket

**Comment by SammyIsra** [comment]
Makes sense lol, no worries!

**Comment by RolfKoenders** [comment]
Hehe, :) I will take this one!

**Comment by lex111** [comment]
I note that there are problems with localization (see #193), and until we fixed them, I would not do the translation (or rather send it to `master`), because later I will have to redo it.

**Comment by RolfKoenders** [comment]
@lex111 I just pushed my branch. I fixed a untranslated field and im almost done with the dutch translations. Let me know when the issues are fixed so i can merge those changes in.

**Comment by lex111** [comment]
@RolfKoenders You can help with this :smiley: 

It is also desirable that all untranslated messages in this PR be resolved (I could miss something in my checklist)
