### ISSUE TITLE
Add Spanish translations

### ISSUE THREAD

**Issue by housseindjirdeh** [gitpoint/git-point#233]
🇪🇸 

@SammyIsra tagged this as assigned but please don't worry about working on this until whenever you like. Also please don't hesitate to not do this at all if you don't want to :)

**Comment by SammyIsra** [comment]
Not sure where to *add* the translation or where to actually translate things, where should I go for that?

**Comment by housseindjirdeh** [comment]
Yess my apologies for not actually explaining things.

1. In the `locales` directory we'll just need to add a new file for a new language. You can just copy the `en.js` file (to sp.js for example) and swap out all the English text for Spanish.
2. We'll need to export that newly added file as well [here](https://github.com/gitpoint/git-point/blob/master/src/locale/languages/index.js)
3. Then it's just adding the new lang object [here](https://github.com/gitpoint/git-point/blob/023c7f4ae52694f75a1bc9748b072f6f66687b0a/src/locale/index.js#L7)
4. The last thing is just simply adding a new list item for Spanish in the options screen [here](https://github.com/gitpoint/git-point/blob/master/src/auth/screens/user-options.screen.js#L61-L68) that switches the language.

Step 1 is the only step that will take a little time (actually doing th translations). The rest is thankfully just a matter of exporting the language and allowing the user to select it :)

Again - don't hesitate to ask questions about anything at anytime my friend.

**Comment by lex111** [comment]
@housseindjirdeh In fact, it is still better not to translate into other languages, until we close #193.
It is important to do it, and then start translating.

I will try to work on the weekend over it, although now who wants, can start translating what is, but do not send PR, but rather wait until the current localization errors are fixed.


Perhaps it makes sense to put the label `on hold` on the issues related to translations?

**Comment by RolfKoenders** [comment]
@housseindjirdeh thanks for that explanation. Im currently adding the dutch translations and found the following hardcoded string `effectiveDate: 'Last updated: July 15, 2017',` we have to update this in every language file if we don't make it dynamic.

**Comment by housseindjirdeh** [comment]
Thanks a million @lex111 for #193, glad that's merged in now :)

@RolfKoenders Hmmmm so are you noticing it's only the events screen not updating with a new language? And that's a good catch, happy to have an issue open to fix that copy line

**Comment by lex111** [comment]
> Hmmmm so are you noticing it's only the events screen not updating with a new language

@housseindjirdeh I checked it, it was updated. It's possible more in detail?

**Comment by alejandronanez** [comment]
I'm a native spanish speaker, if you need help reviewing this ping me directly! :)

**Comment by SammyIsra** [comment]
Hey! Sorry I haven't been able to work on this. You are welcome to take it over if you want, or we can probably work in parts too.

**Comment by alejandronanez** [comment]
Sounds good to me @SammyIsra, hopefully, I'll create a PR this weekend 👍
