### ISSUE TITLE
Don't allow back after submitting issue 

### ISSUE THREAD

**Issue by FlorianTaut** [gitpoint/git-point#236]
Hey, it should not be possible to go back to the "new issue" page with the contents after I submitted it.

**Comment by RolfKoenders** [comment]
You mean, the fields are still filled in and not cleared after you submitted?

**Comment by Antoine38660** [comment]
@RolfKoenders We are able to go back (top left "back" button) to the `SubmitNewIssue` screen after submitting a new issue (`IssueScreen`).

![simulator screen shot 12 aout 2017 a 18 04 52](https://user-images.githubusercontent.com/9287184/29242201-f1e6fd88-7f88-11e7-867e-27fd16c755fa.png)
