### ISSUE TITLE
Display more information for "Commented on commit" event

### ISSUE THREAD

**Issue by machour** [gitpoint/git-point#238]
At the moment, the event screen only displays "[user] commented on commit. [time ago]" for the `CommitCommentEvent` event.

We need to append the commit link to that, and maybe an excerpt of the commit message. 

I'll handle the PR :)

**Comment by Antoine38660** [comment]
I'm currently working on displaying commits (#5) ! So you won't be able to link a link atm...

But I like the idea of append an excerpt of the comment !

**Comment by machour** [comment]
It's the way GitHub web does it ;)
Feel free to close this issue along with your work on commits !

**Comment by housseindjirdeh** [comment]
I like this 🎉 Definitely okay with having a static message until the commit linking functionality is in place (or we can wait until we can link to a commit: I'm okay either way :))

**Comment by housseindjirdeh** [comment]
Whoever takes this on: please take a look at #270 as well as they sort of tie together :)

**Comment by machour** [comment]
Closed in favor of #270
