### ISSUE TITLE
Allow for editing and deleting issue comments

### ISSUE THREAD

**Issue by housseindjirdeh** [gitpoint/git-point#24]
Would definitely be awesome to have the ability to edit and delete issue comments!

**Comment by FlorianTaut** [comment]
I have to options how it looks possible and smooth to me:

- What  about enabling this by holding the comment for about 3 seconds then show the opportunities. 
- What about show 3 small dots in the right top corner and then show the opportunities. 

What do you think @housseindjirdeh

**Comment by RolfKoenders** [comment]
Does this include adding labels and or assignees / reviewers? That would be really helpful as well.

**Comment by housseindjirdeh** [comment]
@FlorianTaut I think both options are amazing. I think having both would be awesome :heart_eyes: 

I think we can start with the 3 small dots approach and when tapped - it opens an action sheet with all the options (Edit/Delete comment). We'll need to make sure that people with admin access on a repo can `edit and delete` anybody's comment in a thread but can only edit and delete theirs on repositories they don't have that type of access with. 

**I'm definitely okay with just being able to edit/delete the current user's comment and then deciding if we should expand to other user comments as well**. Still think it's quite weird that we have the ability to edit other user's comments.

Once that's done, we can close this ticket and then explore adding hold functionality (I think that would just be awesome). I don't know how things will work here however with the different platforms but still think it would be great to have if we could only add it to iOS for example.

What do you think @FlorianTaut ? I have an iOS device so happy to test alongside with you :man_dancing:

**Comment by housseindjirdeh** [comment]
@RolfKoenders GitPoint already has that functionality for issues in a repository you have access to :) Little cog icon top right of the issue screen!

**Comment by RolfKoenders** [comment]
@housseindjirdeh wow, i didn't even notice :sweat_smile: oops.

**Comment by FlorianTaut** [comment]
@housseindjirdeh sounds good for me! I would take a look at it when I come back from my holidays on Wednesday if that's not to late yet

**Comment by housseindjirdeh** [comment]
@RolfKoenders haha that's a little surprise for you :)

@FlorianTaut Enjoy your vacations and take as _long_ as you need my friend, will never be too late

**Comment by jouderianjr** [comment]
Hey, has someone working on this issue? If not, I would like to work in it :)

**Comment by housseindjirdeh** [comment]
Not at the moment!! Will love it if you can take it on :) :) @FlorianTaut please let us know if you're still interested in taking it however

**Comment by jouderianjr** [comment]
Cool, I started yesterday, I will create a pull request in a couple days. :D

**Comment by jouderianjr** [comment]
Hey @housseindjirdeh, Do you have ideas for how we should do this edit flow? Should we open a new screen? Or maybe show a prompt with a text field? 

I already did the delete action in this [branch](https://github.com/jouderianjr/git-point/tree/issue_comment_actions_%2324), then as soon we I finish the edit option I will open a pull request 😄

**Comment by SammyIsra** [comment]
What would the prompt with a text field look like?

**Comment by jouderianjr** [comment]
Hey, I just realize that React Native doesn't expose Alert/Dialogs with text input :/ So I did as a normal screen:

<image width="500" src="https://user-images.githubusercontent.com/1559013/30240455-155f8ea0-9547-11e7-942c-b39f0e3cd939.png">
