### ISSUE TITLE
Can't display PR/Issues anymore

### ISSUE THREAD

**Issue by machour** [gitpoint/git-point#248]
Seems like #193 broke PR/Issues display.

If you click on a PR in the list of PRs of a Repo, you'll get a red screen with : 
`undefined is not an object (evaluating '_this.props.language')` in `issue-list-item-components.js:51:29`

**Comment by lex111** [comment]
@machour thanks, my mistake, fixed in [the commit](https://github.com/gitpoint/git-point/commit/59c9ccbfd0812833953d3fbc8b36d6b49ab4f90b).
