### ISSUE TITLE
Wrong PR status reported

### ISSUE THREAD

**Issue by machour** [gitpoint/git-point#251]
GitPoint displays PR #242 as merged, but it's not merged yet

![Wrong PR status](https://machour.idk.tn/uploads/gitpoint-wrong-pr-status.png)

**Comment by lex111** [comment]
I can not reproduce this, I updated the `master` branch, I look at the Android simulator.

@machour give please more details (and check again).

![image](https://user-images.githubusercontent.com/4408379/29281235-ddb1306e-8126-11e7-84b1-cb961520594a.png)

**Comment by andrewda** [comment]
My guess is that the status was unsuccessfully fetched and did not update from a previous PR. Very strange.

**Comment by lex111** [comment]
Yes, perhaps we need to figure out how to step-by-step reproduce this bug.

**Comment by housseindjirdeh** [comment]
Yeah I think @andrewda is right, it's probably persisted data from the previous PR you just visited in the app @machour which was merged. Will try to reproduce this myself as well

**Comment by Antoine38660** [comment]
I reproduced this one earlier today! And luckily, I was using reactotron :

<img width="648" alt="capture d ecran 2017-08-14 a 13 29 09" src="https://user-images.githubusercontent.com/9287184/29282924-efecb156-8124-11e7-965c-d6f82e456d94.png">

Step:
- Last repository I opened was Antoine38660/100pompes (private one, without any PR). 
- I relauched the app (shift+c and `yarn start:ios`) 
- I looked at #250

**I think** it's a "cache" issue, is it possible?

**Comment by machour** [comment]
There's definitely issues with the cache. For example, if you browse to a Repository informations, then to another one, contributors & owner from the previous repository are displayed while the new informations are being loaded.

**Comment by Antoine38660** [comment]
But, as you can see in the screenshot, some other API endpoint are not affected (`GET /repos/gitpoint/git-point/issues/250/comments`). 

In the `.actions.js` files, repo information aren't getted in the same way

**Comment by andrewda** [comment]
Huh, very strange. Another place I've noticed is repository contributors.

**Comment by chinesedfan** [comment]
I guess it is something like #315, and I try to solve it in #332. Please check.
