### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by housseindjirdeh** [gitpoint/git-point#26]
Would be nice to have syntax highlighting for repository and pull request code in the app. For pull request diffs - this probably isn't trivial at all with they way I've set it up but worth looking into if we have the time :)

Definitely not a high priority however.

**Comment by callodacity** [comment]
We could use a webview and make use of the excellent [CodeMirror](https://codemirror.net) library 👍

**Comment by housseindjirdeh** [comment]
Thank you so much @callodacity. I've never heard of CodeMirror before and it looks promising!!

If anybody wants to take a stab at this - don't hesitate to let us know :)

**Comment by Antoine38660** [comment]
Hey, just tried your app for the first time today : very nice !
The first improvement I was thinking about was Syntax Highlighting :)

I'll try to integrate CodeMirror, I'll let you know if I have some trouble or anything else.

**Comment by housseindjirdeh** [comment]
Thank you I'm glad you liked it :)

**Comment by Antoine38660** [comment]
Some news: :smiley: 

I tried a today to integrate CodeMirror inside a ReactNative WebView. I think it's a bit complicated and will not be easy as we think.

After some search, I found this lib : [https://github.com/conorhastings/react-native-syntax-highlighter](react-native-syntax-highlighter). 
As it's my first experience with ReactNative, I prefer to use this one. What do you think about it @housseindjirdeh ?

**Comment by housseindjirdeh** [comment]
Cheers thanks so much @Antoine38660 - yes that looks promising! More than happy to give that a go and see how it turns out 😄 

Appreciate you taking the time to look into using CodeMirror as well!

**Comment by Antoine38660** [comment]
This is it : 😄
<img src="https://user-images.githubusercontent.com/9287184/28233166-499c979c-68cb-11e7-8b36-c92f15416f52.png" width="300" alt="Screenshot of some syntax highlighting" />

One last thing before I'll be able to make the PR: I have some trouble with scrolling vertically inside the code viewer, do you have some tips or advices? (I already tried to add another `ScrollView`).

**Comment by housseindjirdeh** [comment]
Cheers appreciate all the details and everything, I'm so glad you managed to fix it :)
