### ISSUE TITLE
Wrong wording for "commented on pull request"

### ISSUE THREAD

**Issue by machour** [gitpoint/git-point#261]
Currently, it's displayed as "User created on pull request" : 

![wrong wording](https://machour.idk.tn/uploads/gitpoint-commented-on-pr.png)

it should be "commented on"

**Comment by Antoine38660** [comment]
Same bug here

<img width=300 alt="simulator screen shot 16 aout 2017 a 16 59 30" src="https://user-images.githubusercontent.com/9287184/29369959-5aad6fb4-82a4-11e7-9d53-f3f97bed9669.png"> <img width=300 alt="simulator screen shot 16 aout 2017 a 16 59 16" src="https://user-images.githubusercontent.com/9287184/29369960-5af6e61c-82a4-11e7-998e-cd515b5cf085.png">

**Comment by lex111** [comment]
This is because GitHub gives the `created` status in case a comment has been added, so it should be `commented`.
