### ISSUE TITLE
Add Indonesian translations

### ISSUE THREAD

**Issue by sasongkoadi** [gitpoint/git-point#264]
I Will Take care of this :smile:

**Comment by housseindjirdeh** [comment]
Thank you so much matey ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by lex111** [comment]
@sasongkoadi hi! write please if you are ready to translate.

**Comment by chinesedfan** [comment]
Close first and please feel free to reopen it in #439.
