### ISSUE TITLE
Current user avatar never updates

### ISSUE THREAD

**Issue by machour** [gitpoint/git-point#265]
I changed my GitHub avatar some days ago, but GitPoint keeps on showing me the old one (bearded me).

I even tried to sign out & sign in again, but the old avatar stays.

**Comment by lex111** [comment]
This is bug [RN](https://github.com/facebook/react-native/issues/12606).

URL is the same, so it is not updated. As a solution (not very good), append a random number (or timestamp) into a URL, i.e. there will be something like avatars2.githubusercontent.com/u/4408379?v=4&**c=666** instead of avatars2.githubusercontent.com/u/4408379?v=4

Although in the documentation for [Image](https://facebook.github.io/react-native/docs/image.html), there is a mention of the cache property, maybe this will help us?

**Comment by machour** [comment]
We could also append the profile update time which is provided by GitHub ;)

**Comment by andrewda** [comment]
@machour That's a good idea - would prevent unnecessary refetches of the same image.

**Comment by housseindjirdeh** [comment]
I think that's a great idea @machour if GH provides us that in the response :)

**Comment by machour** [comment]
It does. I'll handle the PR tomorrow !

**Comment by lex111** [comment]
@machour did not know this, then I'm fine. Although still changing the URL itself is not a good decision for me, but considering that there are no other solutions, it's better that way. Although try to use the property cache of the Image component, okay?

**Comment by machour** [comment]
Sadly, the `updated_at` property isn't affected if the user only changes his profile image.

However, the headers in the image response (especially `Last-Modified`) are correctly updated. 

@lex111  : The `cache` property seems to be iOS only, and to be doing everything except what is needed for our case: https://facebook.github.io/react-native/docs/images.html#cache-control-ios-only

So, unfortunately, RN doesn't seem to handle this header properly for now, and I fail to find any library out there that would do. (or maybe my understanding is wrong)

This is the proposed fix for now, that would at least bind the image url to the profile last udpate time .. or we can mark this as wonfix and wait for RN to provide a better support for server-side cache directives.

```diff
diff --git a/src/components/user-profile.component.js b/src/components/user-profile.component.js
index 8545af6..0a4e057 100644
--- a/src/components/user-profile.component.js
+++ b/src/components/user-profile.component.js
@@ -86,8 +86,8 @@ export const UserProfile = ({
       <ImageZoom
         uri={{
           uri: initialUser.avatar_url
-            ? initialUser.avatar_url
-            : user.avatar_url,
+            ? initialUser.avatar_url + '&cache=' + initialUser.updated_at
+            : user.avatar_url + '&cache=' + user.updated_at,
         }}
         style={[
           styles.avatar,
```

**Comment by andrewda** [comment]
Maybe we could also suggest that GitHub update the `updated_at` value when a user changes their profile image. Would make sense to me.

**Comment by andrewda** [comment]
Also, I think your change is better than nothing. At the very least we can tell people to update their profile for their image change to take effect.

**Comment by machour** [comment]
Good idea to ask GH. Do you know on what repository the issue must be filled ?
Ok for the PR, does the provided diff looks ok to you or should I not rely on the current URL format and check for the "?" in url and act accordingly ?

**Comment by andrewda** [comment]
Best place to ask would probably be here: https://platform.github.community/

For the PR, I'd say it looks fine as-is. Might want to use template tags though so ESLint doesn't get mad:
```diff
diff --git a/src/components/user-profile.component.js b/src/components/user-profile.component.js
index 8545af6..0a4e057 100644
--- a/src/components/user-profile.component.js
+++ b/src/components/user-profile.component.js
@@ -86,8 +86,8 @@ export const UserProfile = ({
       <ImageZoom
         uri={{
           uri: initialUser.avatar_url
-            ? initialUser.avatar_url
-            : user.avatar_url,
+            ? `${initialUser.avatar_url}&cache=${initialUser.updated_at}`
+            : `${user.avatar_url}&cache=${user.updated_at}`,
         }}
         style={[
           styles.avatar,
```

**Comment by machour** [comment]
There you go @andrewda 

I also got in touch with GitHub support which opened an internal issue for the API and will keep me posted 🤞

**Comment by machour** [comment]
This should be completely fixed now 😃

"Hey Mehdi,

Just wanted to let you know that the team deployed some changes so that the updated_at for a user is updated after a new avatar is uploaded.

Hope this helps.

Cheers,
Ivan"
