### ISSUE TITLE
Add support for Android O's Adaptive Icons

### ISSUE THREAD

**Issue by JacobDB** [gitpoint/git-point#275]
I'd love it if you could add Adaptive Icon support to this app; it's very easy to implement, [here's the documentation](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html). I could try submitting a pull request with this change, but I'm a web developer, and I've never worked with Android, so I can't guarantee quality.

**Comment by housseindjirdeh** [comment]
Didn't even know what adaptive icons were until you submitted this issue, so thank you :)

I think this will be awesome to have, it really doesn't look too complicated at all so definitely something I think we can have!!

https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html#creating_adaptive_icons_in_xml

**Comment by machour** [comment]
Closed in #340, thanks a lot for the suggestion!
