### ISSUE TITLE
Issue markdown render is incorrect

### ISSUE THREAD

**Issue by gythialy** [gitpoint/git-point#276]
Android 7.1.1, download from Google Play Store, and GitPoint version is v1.1

Expect like this
![snapshot_expect_li](https://user-images.githubusercontent.com/773400/29646346-78fd4004-88b5-11e7-87d9-7db9d47adb94.jpg)

but GitPoint render like this.
![snapshot_gitpoint_li](https://user-images.githubusercontent.com/773400/29646417-f35dc4d6-88b5-11e7-89c4-feec6fc1f861.jpg)

**Comment by housseindjirdeh** [comment]
Cheers thanks for logging this :raised_hands: Definitely worth taking a look and we may have to selectively take care of handling checkbox outputs but it's something we should do
