### ISSUE TITLE
Add Swedish translations

### ISSUE THREAD

**Issue by Jacalz** [gitpoint/git-point#278]
Would be awesome with Swedish as a language

**Comment by Jacalz** [comment]
I have translated Brave browser to Swedish, I would love to help you guys translate this to Swedish 👍🇸🇪

**Comment by RolfKoenders** [comment]
Hee @Jacalz! You are more then welcome to translate the app to Swedish! I followed these instructions on how to add a new language: https://github.com/gitpoint/git-point/issues/233#issuecomment-321917690 

Would like to ask @housseindjirdehor @lex111 if that is still the way to go. If so, maybe we could write a Wiki page for it on how to add a new language.

**Comment by lex111** [comment]
The instruction is already [written](https://github.com/gitpoint/git-point/blob/master/CONTRIBUTING.md#translations), so welcome!

**Comment by housseindjirdeh** [comment]
We would _love_ to have you help us add Swedish to GitPoint @Jacalz, that would be amazing :)

**Comment by lex111** [comment]
@Jacalz hi! write please if you are ready to translate.

**Comment by Jacalz** [comment]
I have a LOT to do with school 😒 Will nit have any time to translator it any time soon 😞 Sorry guys 😅

**Comment by FlorianTaut** [comment]
@lex111 If @Jacalz is not able to translate it at the moment unforunately we should probably not add it to the next milestone because it then could block the release of 1.4.

What do you think?

**Comment by Jacalz** [comment]
That is ok for me

**Comment by chinesedfan** [comment]
Let's add translations in #439. If someone pick the same language, we can reopen it.
