### ISSUE TITLE
Add brazilian portuguese translations

### ISSUE THREAD

**Issue by arthurdenner** [gitpoint/git-point#280]
Hi, guys! I would love to contribute adding brazilian portuguese as a language option.

**Comment by lex111** [comment]
Hi, that's great, instructions for adding a translation [here](https://github.com/gitpoint/git-point/blob/master/CONTRIBUTING.md#translations).

**Comment by housseindjirdeh** [comment]
We would love that @arthurdenner 😍 Thank you so much.

**Comment by machour** [comment]
Implemented in #284
