### ISSUE TITLE
Open in browser feature

### ISSUE THREAD

**Issue by randy3k** [gitpoint/git-point#285]
It would to nice to have a button to open safari to perform anythings gitpoint is not (yet) able to perform, e.g. editing comment and look at commit history.

**Comment by RolfKoenders** [comment]
Good point! Yesterday i had exactly the same thought. It would be nice to have a 'open in browser' button on the readme page for example.

**Comment by CameronSamuels** [comment]
I have used another GitHub client, and I love that/this feature. This should be added.

**Comment by housseindjirdeh** [comment]
I agree, this is something we should definitely have and shouldn't be too complicated. Here's where I'm thinking:

- Issues screen: an `Open in browser` ListItem in the settings screen.
- Repository Screen: an `Open in browser` action in the action list
- User Profile Screen: an `Open in browser` action in the action list
- Organization Screen: an `Open in browser` action in an action list. Will need to add action list icon just like we have it in the user profile screen.
- Auth User Profile Screen: an `Open in browser` action in the user settings screen.
- ReadMe screen: an `Open in browser` action in an action list. Will need to add an action list icon on the top right as well.

If there are any other screens that anyone think we can have this, please let us know :raised_hands: 

In terms of implementation, we should be able to just use `openURLInView` [in utils](https://github.com/gitpoint/git-point/blob/master/src/utils/method-helpers.js#L8-L18) and pass the URL we need. Hopefully, the URL we need is in state for each of the screens when we need it.

**Comment by jouderianjr** [comment]
Hey everyone, I'm almost finishing this issue, probably today I will open a pull request, but I think this should go after the 1.3 version 💃

**Comment by housseindjirdeh** [comment]
@jouderianjr :raised_hands: 

Happy to have this in the 1.4 release :tada:
