### ISSUE TITLE
Order repos by date updated

### ISSUE THREAD

**Issue by CameronSamuels** [gitpoint/git-point#286]
This is what github.con does, and will be good to do instead of alphabetical order.

**Comment by andrewda** [comment]
Date updated, that is. Yes I totally agree that they should be ordered this way rather than alphabetically (by default, at least).

**Comment by CameronSamuels** [comment]
@andrewda, I like how you said "by default". Maybe there could be an option in settings to change this.

**Comment by andrewda** [comment]
That's what I was thinking. Though I'm not sure how useful it'd be.

**Comment by housseindjirdeh** [comment]
Agreed, let's start with just sorting it by date updated. If whoever takes this on wants to go ahead and add an option to toggle between the two in the `user settings screen` that would be awesome, but something we can do at at a later point :)

**Comment by chinesedfan** [comment]
I just submitted my first PR, [#300](https://github.com/gitpoint/git-point/pull/300), to this project by changing the sort method, but without a new option in `user settings screen`. Hope it can help. :)
