### ISSUE TITLE
Display issue/pr number in list

### ISSUE THREAD

**Issue by CameronSamuels** [gitpoint/git-point#298]

**Comment by chinesedfan** [comment]
Do you mean the id number? I want to do that, as well as comments count.

**Comment by CameronSamuels** [comment]
I meant pull request `#51` and issue `#52` for example. This issue has number 298. Maybe that’s the id number?

**Comment by chinesedfan** [comment]
@CameronSamuels OK, we share the same target.

**Comment by nersoh** [comment]
@CameronSamuels it would be something like this?

<img width="375" alt="screen shot 2017-09-09 at 2 25 51 pm" src="https://user-images.githubusercontent.com/1930729/30242390-f255dafc-956b-11e7-9c8c-6c0e5c78f0ba.png">

**Comment by CameronSamuels** [comment]
Perfect. That’s exactly what I was talking about.
