### ISSUE TITLE
Error in profile screen stars number

### ISSUE THREAD

**Issue by jouderianjr** [gitpoint/git-point#312]
<img width="400" alt="app" src="https://user-images.githubusercontent.com/1559013/30176840-24a2150e-93da-11e7-8d89-28fe16361e2b.png">

This happens when the fetchStarCount request fails. Looks like the app tries to get the stars using the display name (In my case is: Jouderian Nobre Junior) instead of user account login (In my case: jouderianjr)

<img width="600" alt="screen shot 2017-09-07 at 14 31 29" src="https://user-images.githubusercontent.com/1559013/30176952-9614d262-93da-11e7-91a7-aa26ae762dae.png">

**Comment by jouderianjr** [comment]
Nevermind guys, that was already fixed in 1cba55f868458dfea2005050e75b825ac35287fb. I think this issue could be closed.

**Comment by andrewda** [comment]
No problem, thanks for submitting!
