### ISSUE TITLE
How about `bindActionCreators`

### ISSUE THREAD

**Issue by chinesedfan** [gitpoint/git-point#316]
`bindActionCreators` is a useful method exported by `redux`. With it, we can simplify codes like following:

```
// src/user/screens/profile.screen.js
+import { bindActionCreators } from 'redux';

-const mapDispatchToProps = dispatch => ({
-  getUserInfoByDispatch: user => dispatch(getUserInfo(user)),
-  getUserStarCountByDispatch: user => dispatch(getStarCount(user)),
-  changeFollowStatusByDispatch: (user, isFollowing) =>
-    dispatch(changeFollowStatus(user, isFollowing)),
+const mapDispatchToProps = bindActionCreators({
+  getUserInfo,
+  getStarCount,
+  changeFollowStatus,
 });
```

Just personal suggestion, waiting for your reply.

**Comment by housseindjirdeh** [comment]
Yep absolutely :handshake: @alejandronanez was kind enough to start implementing it as part of a refactor step to include cleaner binds, reselect, etc... https://github.com/gitpoint/git-point/pull/269/files

Most definitely think we can leverage this in each component that we dispatch actions.

**Comment by alejandronanez** [comment]
@chinesedfan go for it!!!
