### ISSUE TITLE
App store device compat

### ISSUE THREAD

**Issue by staabm** [gitpoint/git-point#32]
At the moment the phone app is available in the appstore also for ipad.

As the app on ipad is only a scaled up version of the phone version (at the time of writing) the app should instead define that its only compatible for iphone not ipad

**Comment by jiaaro** [comment]
All iPhone apps can be installed and run in scaled mode on iPads

**Comment by housseindjirdeh** [comment]
Cheers, there's another issue for iPad support so I'm going to keep the discussion there (+ there's an open PR as well) :dancer:

**Comment by staabm** [comment]
> Cheers, @staabm are you thinking that the app should not support iPad whatsoever if there's no actual designed UI for it?

as long as the app does not provide a "built for ipad UI" I would not list it in the app-store as a universal app but a iphone only app.

adding iPad support itself is of course even better.
