### ISSUE TITLE
Auto fill in pull request merge commit title and description

### ISSUE THREAD

**Issue by CameronSamuels** [gitpoint/git-point#337]
This is a good think to do because I like to keep the default pr merge title and description because I can easily tell it’s a merge commit. I don’t have that memorized and it would be easier to keep it automatically filled in.

**Comment by andrewda** [comment]
Can't autofill the title. PR description is done by adding a `.github/PULL-REQUEST-TEMPLATE.md` file.

**Comment by andrewda** [comment]
Wait maybe that's not what this issue is about – if not could you clarify?

**Comment by CameronSamuels** [comment]
@andrewda, I am talking about the merge commit, not the pull request itself.

**Comment by andrewda** [comment]
Usually it should just be `action(scope): description (#<PR_number>)`, and the description should be the list of significant commits (i.e. only commits that add features or fix bugs, not styling changes, unless that's the point of the PR).

**Comment by CameronSamuels** [comment]
I am talking about this:
![merge commit example](https://user-images.githubusercontent.com/25394678/30570617-e37b9722-9ca7-11e7-9763-73afb8cf8318.png)

That should be the name of the commit which is the default GitHub merge commit title (`Merge pull request #id from username/branch`.

**Comment by andrewda** [comment]
Merge commits are gross 😆  We disabled those in favor of squash and merge. Pull requests should be for only one feature or bug fix, meaning that one commit makes sense. Merging in all the changes makes a _really_ messy commit history.

Sorry for the rant, haha, I just really value clean commit histories. I'll close this for now but mark it as a discussion.

**Comment by CameronSamuels** [comment]
Ok, sounds good. I might even try squashing instead. I have just always done a merge commit for everything. Thanks for the suggestion!
