### ISSUE TITLE
Hide contributors section if it only contains the owner

### ISSUE THREAD

**Issue by machour** [gitpoint/git-point#342]
Currently a repo where the owner is the only contributor looks like this:

<img width="316" alt="screen shot 2017-09-19 at 8 12 32 pm" src="https://user-images.githubusercontent.com/304450/30610693-eabe1148-9d76-11e7-97e5-8a69ff03d368.png">

The screen seems kind of empty and uninformative. Hiding the contributors part would make the code section visible right away.

What do you think about this?

**Comment by lex111** [comment]
A controversial moment, I would perhaps have left everything as well as now.
