### ISSUE TITLE
Execution failed for task ':app:prepareGitPointReactNativeConfigUnspecifiedLibrary'

### ISSUE THREAD

**Issue by ahmetzeybek** [gitpoint/git-point#353]
I am getting this error while build process
```
* What went wrong:
Execution failed for task ':app:prepareGitPointReactNativeConfigUnspecifiedLibrary'.
> Could not expand ZIP 'C:\Users\ahmetzeybek\Documents\reactJS\GitPoint\node_modules\react-native-config\android\build\outputs\aar\react-native-config-rele
ase.aar'.
```
apk file looks installed in emulator but not starting...

**Comment by machour** [comment]
Hi @ahmetzeybek and thanks for reporting this issue.

Can you try the following steps ?
```
cd android 
gradlew clean 
cd ..
react-native run-android
```

Also, did you run `yarn run links` after initially running `yarn` ?

**Comment by ahmetzeybek** [comment]
I will try thanks :)

**Comment by machour** [comment]
@ahmetzeybek for future users facing the same issue, could you tell us how did you fix it?

**Comment by ahmetzeybek** [comment]
Built with [buddybuild](https://buddybuild.com), i couldn't build on my computer, but tried to build release version then succeeded
