### ISSUE TITLE
Authentication problem on old devices

### ISSUE THREAD

**Issue by machour** [gitpoint/git-point#354]
Logging this issue reported on gitter by @MrZhang123:  

I use genymotion to run git-point , but when i hope authorise github to login , it give me "no longer supports your web browser , please upgrade chrome or firefox "( i install chrome in simulator ), how to solve this problem and Continue to develop ？

![____-2017-09-25-__2 49 01](https://user-images.githubusercontent.com/304450/30809630-a8b67a52-a202-11e7-8bd9-0d89ef5b84da.png)

**Comment by machour** [comment]
Hey @MrZhang123, can you try adding userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.91 Safari/537.36" in login.screen.js line 259 ?

Let me know if it works 🙏

**Comment by MrZhang123** [comment]
@machour Thanks for your help , add this code
```JS
userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.91 Safari/537.36"
```
can fixed the `not support in your browser`, but not use in button disabled 
I guess my Genymotion run slow cause this problem , when i run client in android device for develop , the button can touch and login . github authorise just once and then can develop , so I can give authorise and then login the Genymotion to fixed this problem.

**Comment by FlorianTaut** [comment]
@MrZhang123 i had this problem and tried a lot of things.
The only solution i found was installing chrome and fix it that way.

**Comment by machour** [comment]
@FlorianTaut was that on a real device or an emulator? I'm a bit worried by the problem :/

**Comment by MrZhang123** [comment]
@FlorianTaut I installing chrome x86 , but not fix it , I have to use real device.

**Comment by machour** [comment]
@MrZhang123 should I go ahead and close this issue?
You got me a bit worried about old (real) devices.. is there a way you can test on a physical device with an old OS ?

**Comment by FlorianTaut** [comment]
@MrZhang123 @machour i had this issue on Android emulator. Searched the hole internet and even asked github for support.

They told me the same as the browser. Its not supported and i should use chrome instead.
Downloaded the apk and installed it with drag and drop to the emulator.

Then set the default browser in settings and it should work.

**Comment by machour** [comment]
Closing this for now, as it seems to only affect the emulator
