### ISSUE TITLE
Move contributors to CONTRIBUTING.md

### ISSUE THREAD

**Issue by housseindjirdeh** [gitpoint/git-point#359]
@andrewda made a good suggestion to move the contributors images in the README to CONTRIBUTING.md since it's getting quite long 🗒

**Comment by machour** [comment]
@andrewda was suggesting a new file called `CONTRIBUTORS.md`. It makes sense to me to keep `CONTRIBUTING.md` for contribution/build instructions, and the new file only for contributors.

**Comment by vitalkanev** [comment]
Also let's add an instructions how to add a contributor (I actually did `npm install -g all-contributors-cli`, then `all-contributors` and followed instructions)

**Comment by machour** [comment]
@vitalkanev these instructions are currently in the Setup section of the CONTRIBUTING.md file.

**Comment by andrewda** [comment]
Maybe adding those instructions to a Pull Request Template wouldn't be a bad idea, either!

**Comment by housseindjirdeh** [comment]
Perfectly okay with having a separate file, `CONTRIBUTORS.md`.

Also might be worth to have a pull request template as well! Happy to defer that to a separate ticket however

**Comment by andrewda** [comment]
#368 👍

**Comment by acurat** [comment]
I think this can be closed.

**Comment by machour** [comment]
Yes, thanks @acurat
