### ISSUE TITLE
Markdown rendering issues

### ISSUE THREAD

**Issue by machour** [gitpoint/git-point#363]
Spotted by @Antoine38660 <3

When viewing #360 in the app, it crashes with the following error : Views nested within a <Text> must have a width and height.
This is due to the use of images in a table.

We also discovered a weird markdown in this case caused by https://github.com/gitpoint/git-point/blob/master/src/components/markdown-htmlview.component.js#L142

Also, the table headers content should be HTML decoded : 
<img width="416" alt="screen shot 2017-09-26 at 12 42 54 pm" src="https://user-images.githubusercontent.com/304450/30860293-f92968cc-a2c6-11e7-833c-186cae3ad134.png">

There's also a, less critical, rendering issue for #361 : 
<img width="488" alt="capture-d_e_cran-2017-09-26-a_-13 46 44" src="https://user-images.githubusercontent.com/304450/30860382-3ae07922-a2c7-11e7-8093-bd31cb35ef0b.png">

**Comment by housseindjirdeh** [comment]
Cheers thanks so much for logging this @machour. Definitely something we'll address before our next update

**Comment by machour** [comment]
Fixed in #370 !

![screen shot 2017-09-26 at 7 58 10 pm](https://user-images.githubusercontent.com/304450/30878617-75d7fcae-a2fd-11e7-9d0c-213b176a319f.png)
![screen shot 2017-09-26 at 7 57 44 pm](https://user-images.githubusercontent.com/304450/30878618-75dd3aca-a2fd-11e7-97dd-e3d2a7245a6d.png)

**Comment by brandly** [comment]
i think i found another issue like this! viewing [this comment](https://github.com/gitpoint/git-point/pull/438#issuecomment-334860883) shows the `Views nested within a <Text> must have a width and height` error. the embedded image within a checklist seems to be the source of the error.

**Comment by machour** [comment]
Thanks for logging this @brandly, I'll tackle it tomorrow!

**Comment by machour** [comment]
Fixed!
