### ISSUE TITLE
Add PR and issue templates

### ISSUE THREAD

**Issue by andrewda** [gitpoint/git-point#368]
Would help walk people through adding themselves to the contributors list (for a PR) and also help with titling.

**Comment by jsroyal** [comment]
Hi! Can I send PR for contributor list?

**Comment by FlorianTaut** [comment]
I think we should add a question about the OS-Type and real device or emulator to the Issue template.
Because not all bugs happen on every device and os.

What do you think @andrewda, can i send a pr for this?

**Comment by Roshanjossey** [comment]
This is the issue template I use in my project
https://github.com/Roshanjossey/first-contributions/blob/master/ISSUE_TEMPLATE.md

We could tweak this to suit git-point

Here's a sample issue
Roshanjossey/first-contributions#802

🐞 Problem

🎯 Goal

💡 Possible solutions

📋 Steps to solve the problem

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - Addresses #<put issue number here>
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

This is working extremely well for me. I've written a blog post about it
https://medium.com/@roshanjossey/how-better-issues-improve-collaboration-5a4e6ff95e90

**Comment by andrewda** [comment]
We can now use multiple PR templates, too! Maybe one for feature requests and one for bug reports or something like that.

> We don't have docs or UI exposure for this at the moment (we're working on it!), but you can create an ISSUE_TEMPLATE/ directory in any of the currently supported places (repository root, /.github, or /docs) and specify a template via a query parameter in the URL:
>
> https://github.com/melonsong/issue-templates/issues/new?template=template1.md
>
> If you don't specify a template, the standard ISSUE_TEMPLATE.md is used by default:
>
> https://github.com/melonsong/issue-templates/issues/new

**Comment by machour** [comment]
For issues, we should be requiring : 
  * OS
  * Phone model
  * GitPoint version
