### ISSUE TITLE
iPad support

### ISSUE THREAD

**Issue by jiaaro** [gitpoint/git-point#37]
I don't know how much work it is to support iPad size classes but I would absolutely love to pay $10 for this conditional on supporting iPad (where I do most of my team communication - and development on my desktop). I get that it's a free download but I so badly want there to be a good iPad client :)

**Comment by housseindjirdeh** [comment]
I appreciate this so much, thank you <3 Wasn't sure how complicated it was either to support iPad classes, but @pate0920 has a PR up!
