### ISSUE TITLE
Make notifications list takes all screen height

### ISSUE THREAD

**Issue by machour** [gitpoint/git-point#385]
Currently, it doesn't, so the notifications to the bottom gets hidden when we pull to refresh

![](http://g.recordit.co/brQLoVZZ4n.gif)

**Comment by lex111** [comment]
@machour oh no, I noticed this, and fixed it in #371.

**Comment by machour** [comment]
Perfect <3

**Comment by lex111** [comment]
I think this PR will go into the 1.3 release, because everything is ready there.
