### ISSUE TITLE
add logout functionality

### ISSUE THREAD

**Issue by housseindjirdeh** [gitpoint/git-point#40]
So we can't logout of the app right now :). Currently users have to delete the app and redownload in order to sign in with another account.

We can just navigate the user to the initial welcome screen (might be worth clearing our persisted store too).

**Comment by alejandronanez** [comment]
Any steps for the new people to the repo to follow? Also, any thoughts about the design? I think a logout link in the profile page would be enough.

**Comment by housseindjirdeh** [comment]
Thank you @alejandronanez, I had it all in mind and just realized I didn't actually write it down 😞 .

So the `UserProfile` screen has a menu icon on the top right that lets you follow/unfollow users. We don't have this for the `AuthUserProfile` screen and I think we can just add this to open an Action Sheet with a Logout button.

2 caveats:

1. `ActionSheetIOS` is being used and will be changed soon: https://github.com/gitpoint/git-point/issues/2#issuecomment-315032689 to allow for Android functionality. Will appreciate if we use `react-native-actionsheet` here as well
2. There's another ticket open (#8) to allow editing user profile details. If that gets merged in prior --> it probably will make more sense to have `Log Out` included in that screen. But in the meantime the approach mentioned above will work fine

**Comment by RolfKoenders** [comment]
I started to play with logging out a bit and at the moment i have the following.

<a href="http://ibb.co/mZLdSv"><img src="http://thumb.ibb.co/mZLdSv/Screen_Shot_2017_07_17_at_20_31_15.png" alt="Screen_Shot_2017_07_17_at_20_31_15" border="0"></a> <a href="http://ibb.co/c9fpZa"><img src="http://thumb.ibb.co/c9fpZa/Screen_Shot_2017_07_17_at_20_31_25.png" alt="Screen_Shot_2017_07_17_at_20_31_25" border="0"></a>

By clicking yes you would navigate to the 'Login' screen. At this moment i'm trying to figure out how to clear the userData (log the user out).
Till there will be an editing button (Maybe a cogwheel icon next to the profile image will do?) this will do the job i think?

Let me know if i should push my branch and create a pr or its better to combine this with a possible editing feature.

**Comment by housseindjirdeh** [comment]
@RolfKoenders that looks amazing 😍 

Yep so I had the idea for another ticket #8 for updating profile details to have a little cog wheel icon to navigate to the screen where the user can update their info. I was thinking of having Log Out there but I actually really what you did there. I think this is great for now and when the user profile details screen is created --> we can decide if we want to just move the listitem there or leave it where it is now.

Couple of tiny tiny nitpicks I can see (and I know I could have waited for a PR to put this):
 
1. Since the login screen there's a button for `Sign In`, maybe we should call this `Sign Out` instead of `Log Out` (I know - very nitpicky 😂 )
2. Think it might look a little nicer if we leverage `SectionList` and put your new list item within it. `SectionList` title can also be called `Sign Out`
3. Unsure but are you using `octicons` for the icon on the left like [this](https://github.com/gitpoint/git-point/blob/master/src/user/screens/profile.screen.js#L150). If you are, disregard this point 😂 but if not - definitely makes sense to leverage GitHub icons like we do everywhere in the app (feel free to pick any icon that you think makes sense - like an arrow or something)!
4. Would probably say we can `hideChevron` as a prop (like [this](https://github.com/gitpoint/git-point/blob/master/src/user/screens/profile.screen.js#L135) to hide the right chevron icon as well since we don't navigate to a separate page

Aside from these tiny things, this is awesome matey. More than happy to have you submit a PR with a dummy `ListItem` for now and I can show you exactly how we can clear user data if you like (should be really straightforward). Since we use `redux-persist` in the app to persist the entire user data to AsyncStorage, the idea is pretty much we use [`persistStore.purge`](https://github.com/rt2zz/redux-persist#persistor-object) or simply `AsyncStorage.clear()` when we navigate to the login screen

**Comment by RolfKoenders** [comment]
As referenced above i created a pr and here are the other answers.
1. Agree, these things give the overall feeling of the app.
2. I thought it would look bad, but it isn't.
3. This is a `octicons` icon.
4. I'm trying :smile:

**Comment by Antoine38660** [comment]
Can be closed (#131) 😄
