### ISSUE TITLE
Write action/API tests

### ISSUE THREAD

**Issue by andrewda** [gitpoint/git-point#406]
I'd like to keep this separate from #148 – ideally we'd get that merged in first. Afterwards, we can work on testing actions and GitHub API interactions. Obviously we won't want to use the production GitHub API as we'd get rate limited very quickly, so we might want to run our own mock GitHub API, similar to https://github.com/mzabriskie/mock-github-api.

**Comment by machour** [comment]
Just came across [jest-fetch-mock](https://www.npmjs.com/package/jest-fetch-mock) which may come really handy too

**Comment by machour** [comment]
@andrewda Could we integrate tests for now without upgrading to React 16?

From what I understand, enzyme is the show stopper here, and we have to wait for all our dependencies to be R16 compatible being able to use it.

Jest snapshots could be a quiet solid alternative while waiting for packages to be upgraded by their maintainers. The only thing that we won't be able to test for now, as far as I understand it, is clicking/touching elements & their callbacks. 

I would happily live without that for now, and we'd finally have tests implemented in master.

🙏  🙏  🙏  ❤️

**Comment by andrewda** [comment]
@machour Actually, #407 should be almost ready to go. Only thing that's missing there is more tests, but we can add those as we go. There should be enough there for people to get started writing more tests.

**Comment by machour** [comment]
@andrewda when I pull the `tests` branch and run it on the simulator, I get this error

![screen shot 2017-10-17 at 12 43 31 pm](https://user-images.githubusercontent.com/304450/31663141-49ba6c34-b341-11e7-912b-512b9c2f9cf2.png)

rn-app-intro uses a really old fork & unmaintained fork of react-swiper. Is that the problem?

**Comment by andrewda** [comment]
:thinking: Yea looks like that's caused by something in `rn-app-intro`. It looks like there's a new version out (`0.0.5`), so could you try upgrading to that?

**Comment by machour** [comment]
That new version is completely broken: https://github.com/Ernoff/rn-app-intro/issues/1

**Comment by andrewda** [comment]
:frowning: Alright, hopefully that can be fixed soon! As for snapshot tests which you mentioned earlier, I'm not a huge fan primarily because it requires redoing the tests after every minor change to a component. This could be fine to prevent unwanted changes, but eventually people will get into a habit of automatically re-snapshotting without testing first. It's better than nothing, I guess, but I'd like to get Enzyme tests incorporated as soon as possible.

**Comment by soytjan** [comment]
Hi there! I'm new to open source and really like testing! I've had some experience testing API calls with Jest and Enzyme and would love to take on some of these. Let me know if there's anything I should know before moving forward!

**Comment by machour** [comment]
Hi @soytjan and welcome! 🎉 

Nothing special to know before diving in I think. Make sure you're able to initially set up the project and run the tests successfully. Our [contributing](https://github.com/gitpoint/git-point/blob/master/CONTRIBUTING.md) guide should get you started, and we're available on gitter if any problem arise.

**Comment by chinesedfan** [comment]
Let's track in #518.
