### ISSUE TITLE
Add forking

### ISSUE THREAD

**Issue by mikekavouras** [gitpoint/git-point#41]
Add "fork" to Repository Actions

![](https://rpl.cat/uploads/2dDGIcgieTvOJDalgisM3uitPwCoP_EbaAcrpu-Vp-w/public.png)

**Comment by housseindjirdeh** [comment]
Cheers this can be useful without a doubt - and it can be right part of the Action Sheet 👍 

Here's what I'm thinking: Click Fork and get navigated directly to the newly created forked instance. I think we should only worry about forking to the user's direct profile for now and not worry about trying to fork to any of the user's organizations (unless that happens to be trivial :))
