### ISSUE TITLE
Add Galician translation

### ISSUE THREAD

**Issue by siderio2** [gitpoint/git-point#421]
I would like to see a [Galician](https://en.wikipedia.org/wiki/Galician_language) (my native language) version of the app.

**Comment by siderio2** [comment]
I would love to contribute with this translation, please.

**Comment by machour** [comment]
Hey, thanks you so much @siderio2.
Here's how translations are added in the app: https://github.com/gitpoint/git-point/blob/master/CONTRIBUTING.md#translations

And don't forget to add yourself as a contributor! 🙌

**Comment by siderio2** [comment]
Yes, I already watched at it and will also go to gitter in case I found any problem. Thanks.

**Comment by housseindjirdeh** [comment]
We would love to have Galician support, thank you so much @siderio2 <3

**Comment by siderio2** [comment]
I'm almost done with the translation, but looking at the other files I must change, I have found that we are using  emojicode flags, but there's no emojicode for [Galicia...](https://en.wikipedia.org/wiki/Galicia_(Spain))

**Comment by lex111** [comment]
@siderio2 how well will it be if we use the Spanish flag (for it there is emoji)? Or can we take the Galician flag and stylize it under the emoji flag so that they look similar like emoji flags?

cc @housseindjirdeh

**Comment by housseindjirdeh** [comment]
@siderio2 THANK YOU so much mate 🎉 🎉 

It's unfortunate that autonomous regions don't have their own emojis 😞 

I'm perfectly fine with just using the Spanish flag if that's okay? @siderio2. If not, more than happy to rewrite our logic slightly and show circular flag images on the left hand side like this :)

![image](https://rlv.zcache.com/galicia_spain_flag_classic_round_sticker-r79c390697ded48dd83dfaee0d97a4626_v9waf_8byvr_630.jpg?view_padding=%5B285%2C0%2C285%2C0%5D)

Happy to take this on as a separate ticket however (think that would be easier than trying to stylize images to emojis @lex111). Either option works well with me 👍

**Comment by lex111** [comment]
@housseindjirdeh Why circular flag? Then we will have different flags in style, you can make the same, by analogy with emoji, right?

**Comment by siderio2** [comment]
@housseindjirdeh, I don't think the Spanish flag is a good option: there are four official languages in Spain, same in  much more countries, so once we have all the translations it would be very confusing, in terms of UX.  I really don't know if it is a very big challenge, but the more we wait, the more flags we will need to change. A small image (shape doesn't mind) would be better. I've never worked with react, neither react native, but I can help with the changes if I get some guidance.

**Comment by D40661195** [comment]
hey @siderio2, what do you think about from now use 🏳️  then we could start to work in another PR this custom flag feature 😄

**Comment by jouderianjr** [comment]
hey @siderio2, what do you think about from now use 🏳️ then we could start to work in another PR this custom flag feature 😄

**Comment by siderio2** [comment]
It's ok. I'm pretty busy this days, but tomorrow evening or maybe Saturday I'll send the PR.

**Comment by lex111** [comment]
@housseindjirdeh let's then discard the emoji flags and use icons? Only we need to find such a icons package where there is a flag of Galicia. I want the style of the flags to be the same.

**Comment by housseindjirdeh** [comment]
@siderio2 thank you, and you're 100% right. Definitely makes sense to not have to use the same flag throughout.

This is what I was envisioning about circular images:

![image](https://user-images.githubusercontent.com/12476932/31303682-d75f00a0-aadf-11e7-9f9e-61eb822b655f.png)

Shouldn't be too complicated and seems pretty okay in my opinion :). Let me know what you folks think.

**Comment by lex111** [comment]
@housseindjirdeh icons for other languages will also be replaced?

**Comment by housseindjirdeh** [comment]
@lex111 yep that's the idea, just use circular avatars for each flag :)

**Comment by lex111** [comment]
@housseindjirdeh ok, let's do it, but where can I find them for all languages?

**Comment by housseindjirdeh** [comment]
@lex111 sweet. So we can find flags for mostly all major countries [here](http://flagpedia.net/) for example. I _hope_ rounding off each flag should look okay?

For autonomous regions (like Galicia or Catalonia for example), we'll have to search for images of them separately. Their [wiki pages](https://en.wikipedia.org/wiki/Flag_of_Galicia) should have them however.
