### ISSUE TITLE
Add Spanish translation

### ISSUE THREAD

**Issue by siderio2** [gitpoint/git-point#422]
I've noticed that theres no spanish translation yet, and I think is a basic one.

**Comment by siderio2** [comment]
I would like to go ahead with this too.

**Comment by machour** [comment]
Hi @siderio2 and thanks for reaching out!

There's an ongoing PR for Spanish translations: https://github.com/gitpoint/git-point/pull/282, maybe you can finish on it?

**Comment by siderio2** [comment]
I think so, will look how is ti going.

**Comment by andrewda** [comment]
Thanks for this @siderio2! We've already got a ticket for this: #233 - you can move discussions to there if you'd like!
