### ISSUE TITLE
Crash in Comment list

### ISSUE THREAD

**Issue by jouderianjr** [gitpoint/git-point#429]
The app crashes when the user goes into this [issue](https://github.com/jouderianjr/awengular-generator/issues/1)

I've talked with @machour and the problem is related with markdown rendering

**Comment by SammyIsra** [comment]
It seems to be that it crashes on every issue. I tried opening issues on my notifications and from the Issues page and I got the same result.

Example here:

![Gif of app crashing](https://i.imgur.com/oFtWHhC.gif)

**Comment by machour** [comment]
@SammyIsra the problem is supposedly only with some edge cases when using images in a comment. 
Are you unable to open any issue *at all* ? If some, you may have a problem with your working copy.

**Comment by SammyIsra** [comment]
You're right - it crashes when the issue has images. I tried opening this issue and I had no problem. Gif was not playing, but I don't see why that would be related.

**Comment by machour** [comment]
Oh correct, GIFs doesn't seem to be animated on Android.
Opening a separate issue for that!

**Comment by machour** [comment]
@jouderianjr your issue should be fixed now.
@SammyIsra GIF support was added in a different PR !

**Comment by jouderianjr** [comment]
@machour Nice job mate :D I'll test it right now 💃
