### ISSUE TITLE
Crash if the device language is Chinese

### ISSUE THREAD

**Issue by chinesedfan** [gitpoint/git-point#436]
Bad news! After updated to 1.3, I can't open GitPoint any more on my iPhone. It's my mistake that only testing in simulator.

The following [function](https://github.com/gitpoint/git-point/blob/master/src/locale/index.js#L24) is the culprit. In my iPhone, `I18n.locale` returns `zh-Hans-CN`, but `zh` is not a valid locale for `moment`.
```
export const getLanguage = () => I18n.locale.substr(0, 2);
```

Then it causes a crash.

![11507295307_ pic](https://user-images.githubusercontent.com/1736154/31279165-a74e8b14-aa6d-11e7-8db3-78209d8d4222.jpg)

A workaround is to set device language to English first, open GitPoint successfully and choose any language in options manually. Then recover the device language.

@housseindjirdeh I find it's hard to implement `getLanguage`, so I suggest to just return `en` in it.

**Comment by lex111** [comment]
Thanks for the report. I think we can not trim the locale, it does not solve the problem, so we need to create a `map` or `switch`, like this:

```js
switch (locale) {
  case 'zh-Hans-CN':
    return 'zh-CN';
  // ..
  default:
    return locale;
}
```

And rename `language` to `locale`, so it will be more correct. What do you think?

**Comment by chinesedfan** [comment]
@lex111 Sure. But the problem is that we don't know all possible `I18n.locale`.

**Comment by lex111** [comment]
@chinesedfan This is yes, in part, therefore, you need to log errors in the application, such as Sentry (cc @housseindjirdeh ). But this should not be a frequent problem.

And we can check if the support for this locale is in `moment`, and if not, then use English. Then there will be no such cases.
