### ISSUE TITLE
Descriptions of some issues are missing

### ISSUE THREAD

**Issue by chinesedfan** [gitpoint/git-point#437]
For example, #433, #434.

<img width="374" alt="2017-10-06 10 53 30" src="https://user-images.githubusercontent.com/1736154/31283802-43663bba-aa7c-11e7-8e59-3a15c89f2748.png">

@machour I am afraid that it is related with markdown rendering. I got the familiar error when visiting these 2 issues in simulator.

<img width="373" alt="2017-10-06 10 54 29" src="https://user-images.githubusercontent.com/1736154/31283850-623a1d04-aa7c-11e7-8eba-2ed3e3f63424.png">

**Comment by machour** [comment]
Thank you for reporting it, will be fixed soon hopefully
