### ISSUE TITLE
Using OAuth or Personal Access Tokens rathen than username/password

### ISSUE THREAD

**Issue by GMouron** [gitpoint/git-point#45]
Hi,

Thanks for this nice app. I was wondering if it would be possible to use OAuth authentication or Personal Access Tokens to access my account rather than the username/password combo ?

Thanks again for your work.

**Comment by housseindjirdeh** [comment]
Thank you so much @GMouron :)

**Comment by housseindjirdeh** [comment]
Interesting, do you think that would be something you would like to do and we can provide the option in the sign in screen?

**Comment by GMouron** [comment]
Hey, thanks for proposing. Unfortunately, react native is not really my area of expertise :-/

**Comment by machour** [comment]
I think there was a little confusion, as we are using oAuth, not login/password authentication.
The username/password combo are requested in the GitHub oAuth screen, not on our side.

Closing this for now, feel free to re-open if the confusion is on my side :)
