### ISSUE TITLE
App crashes on PR comment

### ISSUE THREAD

**Issue by tautf** [gitpoint/git-point#450]
Hey,

I tried to comment at #445

I wanted to write the following:
Hey, i can review this, my native language is German @lex11 @houssaindjirdeh

Sorry I don’t know you exact names atm😂

But when I submitted it the app crashed. 

When i only added @lex11 i was able to submit the comment.

**Comment by machour** [comment]
@FlorianTaut was that on android or ios?

**Comment by FlorianTaut** [comment]
@machour it was iOS 11.0.2 on a real device. I only had it once yet.

**Comment by tautf** [comment]
Update on this, i have crashes at nearly every issue & pr comment.
OS: iOS 11.0.2 iPhone 7
GitPoint: of course latest 😄

**Comment by andrewda** [comment]
Me too @tautf

**Comment by machour** [comment]
Hopefully this will be fixed in 1.3.1 🤞 
I suspect #429 which was also affecting iOS in some cases

**Comment by vidhill** [comment]
Me too, try to leave a comment on an issue, app crashes, iOS real device

**Comment by machour** [comment]
I think this is a duplicate of #201

**Comment by machour** [comment]
Closing this issue as the PR for it have been merged.
