### ISSUE TITLE
Prettier usage

### ISSUE THREAD

**Issue by machour** [gitpoint/git-point#453]
Hey all,

Since I started working on git-point, I've always been bugged by prettier, leaving me with staged modified files **after** I commit & push: 

```shell
🍺  ~/git-point (test-pretty)*$ vi root.store.js
🍺  ~/git-point (test-pretty)*$ git diff root.store.js
diff --git a/root.store.js b/root.store.js
index f45bb1b..c3e683e 100644
--- a/root.store.js
+++ b/root.store.js
@@ -10,7 +10,7 @@ import { rootReducer } from './root.reducer';
 const getMiddleware = () => {
   const middlewares = [reduxThunk];

-  if (__DEV__) {
+        if (__DEV__) {
     if (process.env.LOGGER_ENABLED) {
       middlewares.push(createLogger());
     }
🍺  ~/git-point (test-pretty)*$ git commit -m "chore: test prettier" root.store.js
husky > npm run -s precommit (node v8.5.0)

 ✔ Running tasks for *.js
husky > npm run -s commitmsg (node v8.5.0)

⧗   input: chore: test prettier
✔   found 0 problems, 0 warnings

[test-pretty 0abc139] chore: test prettier
🍺  ~/git-point (test-pretty)*$ git push -u origin test-pretty
Counting objects: 1, done.
Writing objects: 100% (1/1), 189 bytes | 189.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0)
To github.com:machour/git-point.git
 * [new branch]      test-pretty -> test-pretty
Branch test-pretty set up to track remote branch test-pretty from origin.
🍺  ~/git-point (test-pretty)*$ git status
On branch test-pretty
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   root.store.js
```

After some digging into that issue with the precious help of @chinesedfan, it seems to be caused by the fact that I have other modified files (that I **don't** want to commit) and that I don't use `git add` in my workflow.

Instead, working on existing files, I pass them as parameter in my `git commit` call.

The way it's implemented right now, it seems to be working only on explicitly git added files:
```json
  "lint-staged": {
    "*.js": [
      "prettier --single-quote --trailing-comma es5 --write",
      "git add",
      "eslint --cache --max-warnings 0"
    ]
  },
```

That `git add` doesn't know what files I want and don't want in my commit, so it is ran on files that were `git add`ed by hand, which is none in my case.

Considering that I have this issue, and that I simply **hate** when a process modify my commit without me knowing it and seeing **exactly** what it does, I tried yesterday to have VS Code do the prettier thing on file save.

I was able to do that by installing a plugin, and adding a `prettier` section in my `package.json` file for VSCode to read. (I did slightly change the options, that's why my PR had weird changes).

Could we consider using the IDE with written options in `package.json` instead of that `lint-staged` thingy that doesn't work without `git add` ? We could have a small documentation about how to setup majors IDE to work on GitPoint.

Or I can try to force myself to use `git add` on every file I want to commit before doing my actual commit (but I already forsee myself doing a machinal `git add -A` and then banging my head on my desk :D )

Opinions?

**Comment by chinesedfan** [comment]
@machour I made a mistake in #448 reviews. The reason why those tail commas are removed by Prettier is that they belong to function arguments. It is not a kind of inconsistency between ESLint and Prettier.

Our `.eslintrc` sets `comma-dangle` to `always-multiline`, which means ignoring [function arguments](https://eslint.org/docs/rules/comma-dangle#options). But in precommit script, prettier uses `--trailing-comma es5`, which means no tail commas in function arguments.

If we update it as `--trailing-comma all`, those tail commas will be kept.

**Comment by machour** [comment]
@chinesedfan no worries, there still was a problem with my commit ;)

Personally, I prefer not to have trailing comas in functions arguments, as this kind of make *visually* no sense to me. If a function takes 4 args, I should have 3 comas.

Here's the configuration I used for prettier in my commit:
(I included settings that are defaults to have an explicit config across configs)

```json
{
  "printWidth": 80,
  "tabWidth": 2,
  "useTabs": false,
  "semi": true,
  "singleQuote": true,
  "trailingComma": "es5",
  "bracketSpacing": true,
  "jsxBracketSameLine": true,
}
```

**Comment by chinesedfan** [comment]
@andrewda #482 added the prettier config file, but if I ran `yarn run prettier`, lots of files will be modified.

**Comment by machour** [comment]
@chinesedfan I had the same issue before I realized that I wasn't using the good  prettier version. Make sure you run the one from node_modules

**Comment by chinesedfan** [comment]
@machour I think `yarn run prettier` should use the one in node_modules. Does your dev environment work well?

**Comment by machour** [comment]
@chinesedfan As far as I understand it does. Changed the command to look like this:
  `which prettier && prettier --write "**/*.js"`

output: 
```
/Users/didou/git-point/node_modules/.bin/prettier
.commitlint/index.js 42ms
App.js 95ms
__tests__/data/issue.js 23ms
__tests__/data/label.js 3ms
```

it's correctly using prettier from node_modules.

I do however see a bunch of files changed after running it:
```
	modified:   routes.js
	modified:   src/auth/screens/user-options.screen.js
	modified:   src/components/issue-description.component.js
	modified:   src/issue/screens/issue-settings.screen.js
	modified:   src/issue/screens/issue.screen.js
	modified:   src/issue/screens/new-issue.screen.js
	modified:   src/locale/languages/es.js
	modified:   src/organization/screens/organization-profile.screen.js
	modified:   src/repository/screens/issue-list.screen.js
	modified:   src/repository/screens/pull-list.screen.js
	modified:   src/repository/screens/read-me.screen.js
	modified:   src/repository/screens/repository.screen.js
	modified:   src/user/screens/profile.screen.js
```

All changes seems legit to me

**Comment by chinesedfan** [comment]
@machour Same with me. Maybe all of above should committed to solve prettier problem completely.

**Comment by machour** [comment]
Yes, you can do a PR for this. Generally I avoid doing this kind of PRs as it may introduce annoying conflicts in the existing ones. And the would eventually be prettied in a future commit

**Comment by chinesedfan** [comment]
Right. Hope this time the styled-component refactor will prettier each file. 😆

**Comment by machour** [comment]
Closing this issue since it was taken care of.

Also note, for the hook to work properly and not leave you with unstaged changes, use `git add` on your files before issuing `git commit`.
