### ISSUE TITLE
Question about seeing changes while developing

### ISSUE THREAD

**Issue by cheshire137** [gitpoint/git-point#454]
Hi! I've got the app running locally via `yarn start:ios:logger` but I'm wondering what's the fastest way to see changes I make in the app. When I've generated a React Native app via the [create-react-native-app script](https://github.com/react-community/create-react-native-app), as soon as I save a source file, the app rebuilds and I see the changes in the Simulator. Is Ctrl-C'ing in the terminal and then re-running the yarn command the fastest way to develop? Thanks!

**Comment by cheshire137** [comment]
Follow-up question: what's the best way to log data or debug the app while developing it?

**Comment by cheshire137** [comment]
Cmd-D was the trick! See https://stackoverflow.com/a/29365378/38743.

**Comment by housseindjirdeh** [comment]
Yep Cmd+D will be your friend :)

Enabling `Live Reload` will have the app rebuild as soon as you save any changes. If you prefer, you can have it disabled and use Cmd+R to reload the application to see you newer changes. `Hot Reload` is supposed to actually render your application _without_ a reload which is awesome, but haven't noticed it working too well with our navigation stack :raised_hands:
