### ISSUE TITLE
Crash on issue comments

### ISSUE THREAD

**Issue by FlorianTaut** [gitpoint/git-point#462]
Hey guys,

i tried to open a notification with gitpoint.
The app crashed immeditely.

I tried it with 2 different notifications.

Somebody can reproduce this crash?

Have iOS 11.0.2 on an iPhone 7 running latest GitPoint version

**Comment by FlorianTaut** [comment]
Update: I reinstalled gitpoint because everything crashed from this point on.
Everything is working smooth now and i can open one notification of the two i recieved.

Number 1, which broke gitpoint, is a notification about a comment in https://github.com/octokit/discussions/issues/7 when i try to open this notification gitpoint crashes and everything is "broken" from this point. I cant open issues, notifications and pr's anymore.

Probably something inside of this issue brings gitpoint to crash because it cant handle something.

**Comment by FlorianTaut** [comment]
Probably we could test this if somebody else subscribes to this issue and waits to recieve a notification.
If gitpoint crashes then we know where the issue comes from.

**Comment by machour** [comment]
Seems to be caused by this exact comment: https://github.com/octokit/discussions/issues/7#issuecomment-327616339

**Comment by machour** [comment]
Here's the error screenshot:
<img width="360" alt="screen shot 2017-10-10 at 1 42 25 pm" src="https://user-images.githubusercontent.com/304450/31387056-4e7d1bae-adc9-11e7-8bd2-3bdfaeb43443.png">

Seems to be related to this issue in RN: https://github.com/facebook/react-native/issues/10635

**Comment by FlorianTaut** [comment]
Do you want to take a look at this?

**Comment by FlorianTaut** [comment]
@machour probably I should change the issue title, because this is not related to notifications. It will happen also if I open the issue directly.
