### ISSUE TITLE
Show repository topics

### ISSUE THREAD

**Issue by ftaut** [gitpoint/git-point#470]
Hey,

It would be very smooth if we could show the topics a repository uses. 

Not sure where we could add this part but I think this is something we should add for 1.5 or 1.6.

**Comment by housseindjirdeh** [comment]
Agreed don't think it would hurt to have. Open to suggestions as well!

**Comment by vitalkanev** [comment]
So, here is what I found: We can *only* use v3 API, and the `topics` [is currently in ***preview stage***](https://developer.github.com/v3/repos/#list-all-topics-for-a-repository) and requires this header to be set:

| `Accept`
| ----------
| `application/vnd.github.mercy-preview+json`

`EXAMPLE`:
``` zsh
% curl -H "Accept: application/vnd.github.mercy-preview+json" 'https://api.github.com/repos/hubotio/hubot/topics'
{
  "names": [
    "hubot",
    "chat",
    "bot"
  ]
}
```

**Comment by nersoh** [comment]
I'll try this one.

**Comment by machour** [comment]
Let's ship this one in 1.5 🎉
