### ISSUE TITLE
Bug/Crash possibility in src/components/code-line.component.js

### ISSUE THREAD

**Issue by ericadamski** [gitpoint/git-point#483]
Looking through the code came across this line:

https://github.com/gitpoint/git-point/blob/e81f301eb5a6574b9c7f6bafe15c40d81ad34a87/src/components/code-line.component.js#L79

if `filename` is `undefined` or `null` this would cause a crash. Wondering if this should be:

```javascript
const language = (filename || '').split('.').pop();
```

**Comment by D40661195** [comment]
Yeah, I just saw this issue testing flow in our project, do you want open a pull request to fix it? 😄

**Comment by ericadamski** [comment]
@D40661195 can do

**Comment by jouderianjr** [comment]
> Yeah, I just saw this issue testing flow in our project, do you want open a pull request to fix it? 😄

Sorry, I've posted with a wrong user hahah that's my personal account
