### ISSUE TITLE
Fix build due to linter errors

### ISSUE THREAD

**Issue by alejandronanez** [gitpoint/git-point#496]
We have some errors in our build due to Esperanto language file. This is a good issue for beginners!
You can find the file in `src/locale/languages/eo.js`

**Comment by andrewda** [comment]
What are the issues?

**Comment by alejandronanez** [comment]
That's weird, https://travis-ci.org/gitpoint/git-point/builds/289317716

**Comment by andrewda** [comment]
I think that tests was run on old code. This should have been fixed in 3ab5a5b5f270321e59a46f0ab2ba8e92f021843e and all current tests are passing 👍
