### ISSUE TITLE
View commits

### ISSUE THREAD

**Issue by housseindjirdeh** [gitpoint/git-point#5]
As of currently, actual commit information can't be viewed anywhere in the application. You may have already noticed that you can't even click a commit in the notifications screen to view it's details.

Would definitely be nice to:

* have the number of commits when viewing the diff of a pull request be clickable
* have commits that show in the notifications screen be clickable
* add number of commits in the repository screen - also clickable

Clicking either would navigate to a list of commits screen (`CommitsListScreen` for example) and clicking each commit would take you to a commit details screen (`CommitScreen`for example which can look the same as `PullRequestDiff` screen).

Showing commit comments might be a bit more tricky and it's something we can do as a separate ticket once this gets added in.

**Comment by Antoine38660** [comment]
Can you assign me to this one? I think I'm ready after the `Submit new issue` feature. 
I do things gradually 😄

**Comment by housseindjirdeh** [comment]
Absolutely 🎉 🎉 This is really needed in the app so thank you :)

**Comment by rancidfrog** [comment]
Also, to view a repository commit history would be nice
