### ISSUE TITLE
Add onboarding swiper as welcome screen

### ISSUE THREAD

**Issue by housseindjirdeh** [gitpoint/git-point#51]
Our current welcome screen before a user logs in:

<p align="center">
<img src = "https://user-images.githubusercontent.com/12476932/28197852-8e7fdd14-6827-11e7-8e90-577282962db0.png" width=250>
</p>

I quite like it, but I think having a welcome swiper explaining the different things the app could do would be even better 🤓 

For example: the Slack mobile app

![image](https://user-images.githubusercontent.com/12476932/28197910-0437ee66-6828-11e7-93c6-7861c82d9b0a.png)

The Product Hunt app

<p align="center">
<img src = "https://user-images.githubusercontent.com/12476932/28197942-3f34c96c-6828-11e7-8ed5-6bd0c3a611ca.png" width=250>
</p>

Doesn't have to be as anything as complicated as those options - they're just for reference.

Some points however:

1. [react-native-swiper](https://github.com/leecade/react-native-swiper) seems to be an excellent library that can do just this
2. I like the idea of having the Sign In button at the bottom always so even though the user can continue to swipe, they can always just click the sign in button
3. I'll leave the floor open for design suggestions. Something simple with a top title (`Control your notifications` for example, a GitHub [octicon](https://octicons.github.com/) in the middle and a mini blurb below (`View and control all of your unread and participating notifications.` for example is what I'm envisioning. Feel free to just lift copy from [the landing page](https://gitpoint.co)

Always open to further ideas and suggestions of course <3

**Comment by FlorianTaut** [comment]
Definetily nice to have!!!

**Comment by housseindjirdeh** [comment]
Current progress

![currentprogress](https://user-images.githubusercontent.com/12476932/28603140-58b2238c-7190-11e7-871b-ee8a74337ecf.gif)

Will have a PR up for it tomorrow (needs a little more color I think :thinking:)

I'm thinking the slides will be in this order:
1. `Welcome`
2. `Notifications`
3. `Repository/User`
4. `Complete issue and pull request control`

Let me know if anyone has any suggestions!

**Comment by andrewda** [comment]
Wow that looks awesome!

**Comment by lex111** [comment]
I would also list the main features, add more icons, and maybe make an animation?

**Comment by housseindjirdeh** [comment]
Cheers thanks mateys @andrewda @lex111, yep plan on showing the main features in each of the slides with an icon for each. How are you envisioning an animation? I'm thinking a slowly bouncing logo might be nice so I'll play around with it :)
