### ISSUE TITLE
Different font for create event

### ISSUE THREAD

**Issue by chinesedfan** [gitpoint/git-point#521]
Just a little curious. Is it set on purpose?

![createevent](https://user-images.githubusercontent.com/1736154/31806327-8efb3c50-b52c-11e7-930b-7271f611783f.png)

**Comment by andrewda** [comment]
GitHub displays branches in the `code format` in the event list, so this replicates that.

**Comment by chinesedfan** [comment]
OK. The branch styles in Github are much better, while ours is, em, a little wired. 😆

Hope someone can improve it. (cc @housseindjirdeh)

<img width="695" alt="2017-10-20 14 36 59" src="https://user-images.githubusercontent.com/1736154/31808073-4100a4d0-b537-11e7-9b80-27134d457337.png">

**Comment by housseindjirdeh** [comment]
Haha yeah I _tried_ to replicate it :P

Definitely think we can mimic the way it actually looks on the site :+1: 

Will tag this for the 1.5.0 release :+1:

**Comment by ZahraTee** [comment]
Can I pick this up? :)

**Comment by chinesedfan** [comment]
@ZahraTee Of course! Glad to hear that.
