### ISSUE TITLE
Do not work on IOS 11.1.2

### ISSUE THREAD

**Issue by wangzongxu** [gitpoint/git-point#522]

**Comment by tautf** [comment]
Hi @wangzongxu, could you please provide some more information.

Correct me if im wrong but iOS 11.1.2 isn't even out yet.
Are you using beta software?

**Comment by wangzongxu** [comment]
I'm so sorry, my iphone system version is 11.1(15b5086a),
but git-point does't work when I open it.

**Comment by chinesedfan** [comment]
I guess you are a Chinese like me, please check #436. The bug has fixed, but have not released yet.

**Comment by wangzongxu** [comment]
thank you at first, but I had a flashback problem,I can't open it.

**Comment by WittBulter** [comment]
@chinesedfan same error.
> version: 11.1.3, iPhone: 6s, lang: zh-CN

**Comment by chinesedfan** [comment]
@wangzongxu I know. Can you try the workaround described in #436?

**Comment by wangzongxu** [comment]
@chinesedfan that's great! thank you very much , I tried this method and It opened successful!

**Comment by machour** [comment]
@chinesedfan was this addressed by @lex111 recent work on locales?

**Comment by chinesedfan** [comment]
@machour Yes, already fixed by #479.
