### ISSUE TITLE
Markdown: Add support for <details>

### ISSUE THREAD

**Issue by machour** [gitpoint/git-point#528]
It would be nice to add support for `<details>` tag in GithubHtmlView:

## Title
<details>
  <summary>
    The following subheadings are hidden by default.
    Click to expand them.
  </summary>

### Sub header 1

Hello there.
</details>

**Comment by ArvinH** [comment]
Hi, I want to take care of this one!
First time for React-native but I'm trying 😄 
![demo](http://g.recordit.co/1EIxv3Kyfr.gif)

**Comment by machour** [comment]
@ArvinH awesome, thank you!! 🎉 
You may find our `<ToggleView />` component handy: https://github.com/gitpoint/git-point/blob/master/src/components/toggle-view.component.js
Could you also try to use the same arrow as github?  ► ▼

**Comment by housseindjirdeh** [comment]
@ArvinH thank you <3

Any questions about anything - don't hesitate to ask 🙌
