### ISSUE TITLE
Images not rendering

### ISSUE THREAD

**Issue by FlorianTaut** [gitpoint/git-point#53]
Hey,

It would be nice to be able to create issues with GitPoint. 

Another point is that rendering is not working correctly. Images are not displayed only the code behind the image is displayed. 

Great app!

Thank you!

**Comment by alejandronanez** [comment]
Hey @FlorianTaut thanks for reporting this issue.
About `Another point is that rendering is not working correctly. Images are not displayed only the code behind the image is displayed.` do you have a screenshot or some steps to reproduce?

Thanks!

**Comment by housseindjirdeh** [comment]
Cheers thank you folks so much.

Just created a separate issue to add new issues #58. We can use this ticket to analyze the image bug you're seeing @FlorianTaut

**Comment by FlorianTaut** [comment]
Hey,

@alejandronanez
Here is a Screenshot:
![image](https://user-images.githubusercontent.com/18403881/28237851-783dfc08-6948-11e7-97b3-f5f47147cedb.png)

**Comment by machour** [comment]
Handled in #326
