### ISSUE TITLE
Help getting started in a Windows machine

### ISSUE THREAD

**Issue by SammyIsra** [gitpoint/git-point#54]
Hey! I am trying to get this project started on my Windows machine to see if I could tackle an issue or two. RIght now I am having issues with the installation process, `yarn run link`:

```
Looks like you installed react-native globally, maybe you meant react-native-cli?
To fix the issue, run:
npm uninstall -g react-native
npm install -g react-native-cli
```

Running those two npm commands fixed nothing. Before forking the application, I did not have anything React Native installed on my machine. Any suggestions will help, thank you!

**Comment by alejandronanez** [comment]
Hey @SammyIsra I don't have a windows machine but the error you're seeing is:
`Looks like you installed react-native globally, maybe you meant react-native-cli?` ?

**Comment by alejandronanez** [comment]
Also I think you won't be able to run the ios app in windows. Thoughts about this @housseindjirdeh ?

**Comment by housseindjirdeh** [comment]
Thanks for logging this @SammyIsra, and I appreciate that you want to tackle a few issues :)

Unfortunately you need a Mac to be able to run native iOS code using the CLI (although I'm not sure why `yarn run link` is failing - it looks like you may need to install the CLI globally as well [`yarn global add react-native-cli`).

So if we were using [`create-react-native-app`](https://github.com/react-community/create-react-native-app) then you would be able to run iOS native code in your machine. However we're just using the CLI. A possible solution may just be installing a Mac virtual machine and/or working on Android related tickets. We're currently looking to have a beta of the Android build merged in #2 and once that's done you are definitely welcome to work Android specific tasks :)

Steps to get Android running on your windows machine is [here](https://facebook.github.io/react-native/docs/getting-started.html)

**Comment by SammyIsra** [comment]
@housseindjirdeh is there any way I can help now, or should I wait until the Android version is in the main repo if I only have a Windows machine and an Android phone?

**Comment by alejandronanez** [comment]
Hey @SammyIsra! Android version is already in the master branch, you can start working in there.

**Comment by SammyIsra** [comment]
Oh that was quick, thank you! @alejandronanez

**Comment by housseindjirdeh** [comment]
<3 please feel free to pull it down and anything you notice - log an issue for it!!! Going to put some further information in #2
