### ISSUE TITLE
Migration inline-label component to styled-component

### ISSUE THREAD

**Issue by binkpitch** [gitpoint/git-point#540]
Based on issue #532

I am new to working with open source project but I have write some code with React Native and styled component before. Can I take this issue ?

**Comment by machour** [comment]
With great pleasure @binkpitch, welcome to GitPoint!
I've added you to the list, let us know if you need any help with your PR.

**Comment by binkpitch** [comment]
@machour The PR has been merged, do I have to close this issue or just leave it open ?

**Comment by chinesedfan** [comment]
@binkpitch Sure, I can close it. Done by #544.
