### ISSUE TITLE
Setup code quality metrics

### ISSUE THREAD

**Issue by lex111** [gitpoint/git-point#541]
[Codecov](https://github.com/marketplace/codecov) or [Coveralls](https://github.com/marketplace/coveralls), which one is better?

сс @housseindjirdeh @machour @andrewda @alejandronanez

**Comment by machour** [comment]
I personally used and liked coveralls

**Comment by alejandronanez** [comment]
I’ve worked with both and I think coveralls os way better.

**Comment by lex111** [comment]
Ok, then @housseindjirdeh need to set up coveralls in the repository.

**Comment by machour** [comment]
Done in #571
