### ISSUE TITLE
Start using GitHub Projects again

### ISSUE THREAD

**Issue by andrewda** [gitpoint/git-point#551]
GitHub Projects are a great way to keep us organized on what's done, what's being worked on, and what's available to be claimed. It'd be great to start organizing issues and PR's there again.

**Comment by alejandronanez** [comment]
I agree, this will help us to get a little more organized. I think Github projects will be good enough, but if we want something a little more _fancy_ we can use https://waffle.io/pricing, it is free for open source projects.

**Comment by housseindjirdeh** [comment]
Was thinking about this early :)

I closed it since we weren't really relying on it earlier. Definitely open to using it once more if we all decide to rely on it nicely. 

How are you guys envisioning it? Split it by version releases and group issues and PRs in each section?

**Comment by andrewda** [comment]
Maybe have the name of the Project be the name of the release (so like `1.4.0`) and within the project have `To Do`, `In Progress`, and `Completed`.

**Comment by housseindjirdeh** [comment]
Done :)

I've added separate projects for `v.1.4.0`, `v.1.4.1` and  `v.1.5.0`. I think once we have everything in for 1.4.1 for example for bug fixes, we can add a new one for v.1.4.2 and so forth. 

Once we have `1.4.0` merged in, we'll align this project roadmap with separate branches in the repo as well to keep things streamlined.

Also please let me know if you have edit access to projects. I would really like all of you folks to be able to add/modify the project timeline @alejandronanez @machour @andrewda @lex111 @chinesedfan

**Comment by andrewda** [comment]
@housseindjirdeh works like a charm!

**Comment by machour** [comment]
Works fine for me :)

**Comment by chinesedfan** [comment]
@housseindjirdeh No problem. I love tasks!

**Comment by housseindjirdeh** [comment]
Beautiful <3

Feel free to move things to any of the releases you see fit folks. We can always clarify further in our gitter channe; 🎉
