### ISSUE TITLE
Watch repos

### ISSUE THREAD

**Issue by alejandronanez** [gitpoint/git-point#56]
I see that right now is not possible to watch any repos (only star repos is available)

I'd like to work on this feature too.

Thanks!

**Comment by housseindjirdeh** [comment]
Awesome this will be great, thank you!

If it's possible will love to have number of watchers show in the repository profile as well (watchers + stars + forks). Of course we can move that to a separate ticket if you prefer. Watching/unwatching can be just like we do starring currently. 💃
