### ISSUE TITLE
v1.4.0 Release - Final Checks

### ISSUE THREAD

**Issue by housseindjirdeh** [gitpoint/git-point#569]
Releasing `1.4.0` has been long overdue, and my apologies :O. Let's have this out before the end of this week ⭐️ 

Couple of things I've noticed so let's use this issue to track down all the changes we'll need before release 🚀 

**For any thing mentioned on the list here and on this issue you want to tackle, just tag this issue number on your PR.**

On iOS && Android:
----

### Profile images don't seem to be showing on profile screens

![image](https://user-images.githubusercontent.com/12476932/31921322-da7eaf0a-b83c-11e7-8878-17ae8188be2f.png)

### A few list items throughout the app have borders bolded a lot more

![image](https://user-images.githubusercontent.com/12476932/31921499-ac0b161c-b83d-11e7-96f4-cba1b7dd6494.png)

### Notifications badge count has styling issues

View both screenshots above

Anything else anybody sees, please add it to this ticket. Shouldn't be too much regressions (and now that we're adding tests we should definitely be seeing less)

**Comment by alejandronanez** [comment]
@housseindjirdeh I can take a look at the profile picture bug.

**Comment by housseindjirdeh** [comment]
Thank you matey @alejandronanez <3

**Comment by housseindjirdeh** [comment]
⚠️ Thanks for logging this one @machour:

## Android

![image](https://user-images.githubusercontent.com/12476932/31922003-875a78be-b840-11e7-8573-2b9017c9f550.png)

App intro buttons not showing smoothly

**Comment by machour** [comment]
@housseindjirdeh The app intro button should have been fixed by #527 
Are you still getting this?

**Comment by machour** [comment]
@jouderianjr did you fix the cropped buttons for issues and pulls? I don't remember anymore :D

**Comment by jouderianjr** [comment]
yeah, #545 😄  Sorry for don't help much in this release, I'm pretty busy in this days 😢

**Comment by housseindjirdeh** [comment]
Thanks @machour, didn't run it and thought it was still showing for Android users. Thank you <3

**Comment by housseindjirdeh** [comment]
@yannbf was kind enough to log this in #536. Not sure if it's still occurring but logging it here to remind us to double check if it hasn't been resolved yet :)

![image](https://user-images.githubusercontent.com/12476932/31967362-af1a608a-b8db-11e7-83df-3dbf6f4e1429.png)

**Comment by alejandronanez** [comment]
If anything related to `1.4` comes up we should add it to this board https://github.com/gitpoint/git-point/projects/2 I think it's easier to take a look there instead of an issue thread. What do you think guys?

**Comment by housseindjirdeh** [comment]
Create separate issues for each of these and put it on my board? Yep I think that's a good idea as well

**Comment by chinesedfan** [comment]
@housseindjirdeh I got a little confused about milestones. What's the relationship between projects and milestones

**Comment by andrewda** [comment]
@chinesedfan Yea the line gets a little blurry. I'd say milestones are for tracking what issues we want in each release, whereas projects are for the current status of each issue (in progress, etc.) though I think we would be fine only using projects.

**Comment by housseindjirdeh** [comment]
^ Yep that's how I see it. Honestly perfectly fine with sticking to one as long as we all adhere as much as we can (and that can be projects).

Having milestones laid out as well shows the release number in the issues list screen which is pretty cool but isn't essential of course :)

**Comment by machour** [comment]
Just ran the app from master after a few days away, and I'm seeing a lot of obvious UI problems:

<img width="431" alt="screen shot 2017-10-26 at 10 46 21 am" src="https://user-images.githubusercontent.com/304450/32046711-18e1f488-ba44-11e7-9762-9329a43867b6.png">
<img width="447" alt="screen shot 2017-10-26 at 10 47 42 am" src="https://user-images.githubusercontent.com/304450/32046712-1902ae1c-ba44-11e7-889a-ceb1f1f92a2e.png">

I think the problem is that we've been accepting a lot of PRs for hacktoberfest, from people eager to contribute (and that's just great) but a bit sloppy with testing. 

I believe its the responsibility of the person who decide to click the merge button to:
- checkout the proposed branch
- carefully test *everything* that was impacted by this PR
- only merge it if it's fully functional, or give a constructive feedback to the submitter (who will learn a lot from it)

Could we all take some deep breaths before merging ? ❤️

**Comment by housseindjirdeh** [comment]
:(

Thank you @machour I appreciate it. I definitely think a lot of the folks submitting PRs to change our components styling aren't actually testing it on their simulator (maybe because it's simple to quickly grab an issue that requires a quick styling change?)

I'm going to add a note to the contributing guidelines that asks for a screenshot of the changed component/screen before submitting. If any PR comes up that changes any JSX and/styles, please let's not merge it in unless there's a screenshot first.

After that - I agree. I would like the person who actually approves the PR to test it locally on their device/simulator and at least give a nod to other reviewers that it looks good. And I'm guilty here for merging PRs without having tested it with the assumption that other reviewers have, so my apologies 😞  

If not a single person who approves it has tested it on their device/simulator - then I agree we should hold off merging.

**Comment by alejandronanez** [comment]
+1 on adding a screenshot before merging. I think the screenshot should be submitted by the person who creates the PR not by any of the people with merge permissions though, it can be really time consuming + and people that send a PR should be responsible for their work.

@housseindjirdeh You can update the PR template with a checklist requiring the screenshot and some other goodies.

**Comment by andrewda** [comment]
@alejandronanez I agree that the person submitting the PR should be responsible for creating screenshots. There should also be exceptions, obviously, such as if a person can't get their environment setup correctly, and need help testing their changes.

**Comment by machour** [comment]
I fixed the user information list, but I encountered some difficulties with styled-components & react-native-elements. (More details in #586). Same things goes for the second screenshot of my previous comment, so I'm holding off on changes til we figure it out.

On a side note, I'm noticing contributors using styled-components names like `ContainerBorderBottom`. Same as CSS, I propose that we avoid names representing the layout as it will become incoherent as soon as we change the layout and use something more semantical like `IssueDescriptionContainer`. (this should be in the contributing guide as well IMHO).

**Comment by alejandronanez** [comment]
@gitpoint/maintainers do we have a list of all the regressions that happened after the SC refactor?

**Comment by andrewda** [comment]
@alejandronanez Good idea. That's probably the most thorough way to go about this.

**Comment by machour** [comment]
@alejandronanez I think we only mentioned what we've seen so far. The only way to get an exhaustive list would be to go through *all* merged PRs and test them one by one :/

**Comment by jouderianjr** [comment]
Hey everyone, I've noticed this change ( I have almost 100% sure that is related to react-native-elements update)

### Before

![screen shot 2017-10-28 at 20 27 02](https://user-images.githubusercontent.com/1559013/32139417-6c6f0092-bc1e-11e7-804a-3d785b33ffa1.png)

### After

![screen shot 2017-10-28 at 20 16 01](https://user-images.githubusercontent.com/1559013/32139387-3a4708fe-bc1d-11e7-83f1-d20def32ea23.png)

Should we fix for the old style?( normal font weight and without ellipsize)

**Comment by chinesedfan** [comment]
> @gitpoint/maintainers do we have a list of all the regressions that happened after the SC refactor?

I checked the merged 12 styled-component. Thank goodness that only 3 issues(#614, #615, #616) were added. For all [SC related PRs](https://github.com/gitpoint/git-point/pulls?q=is%3Apr+is%3Aopen+label%3Astyled-components), you can view by the `styled-component` label or #532.

**Comment by SammyIsra** [comment]
@jouderianjr Because Bios are usually longer than a line, I am for using the old style with normal font weight and without ellipsis.

**Comment by andrewda** [comment]
Agree with @SammyIsra - GitHub already limits the length of bios, so let's not limit it any further.

**Comment by machour** [comment]
@gitpoint/maintainers Just went through the various issues discussed in this thread and cleaned up the project board for 1.4.0: https://github.com/gitpoint/git-point/projects/2

I'm all in favor of starting to use the project board over milestones, as it gives a neat glimpse of the release status. 👌

**Comment by housseindjirdeh** [comment]
PR #665 open to cover a few styling updates

**Comment by housseindjirdeh** [comment]
There are a few things I'm noticing I would like to get to by tomorrow before releasing:

I'm noticing a weird flash when I navigate to the profile page:

![flash](https://user-images.githubusercontent.com/12476932/33866830-e32ad5ec-dec6-11e7-8463-17a864900fc1.gif)

I also think issues seem to load/unload/load a bit much - should be able to simplify to show one loading indicator until screen is fully loaded:

![stagger](https://user-images.githubusercontent.com/12476932/33866869-ffffca92-dec6-11e7-8958-4de5d3c7b6c1.gif)

Definitely not major and okay to hold these off to the next release if need be, but will be nice if we can cover them as well :)

**Comment by machour** [comment]
Yes, issue screen is getting really heavy (7 requests for a PR I think).
I do however like to see comments right away when they are available (I'm on a poor connection and it sometimes can take up to 5 seconds to fully load).

This needs GraphQL sooo bad :)

**Comment by jouderianjr** [comment]
> This needs GraphQL sooo bad :)

Totally agreed, GraphQL should be top priority for us 💃

**Comment by housseindjirdeh** [comment]
We really do :O

I am going to HAVE to dedicate sometime in the next few months implementing graphql where applicable. Fingers crossed 🙏 

With that being said - just deployed v1.4 so going to close this.

**Comment by machour** [comment]
:tada: :tada:

**Comment by rancidfrog** [comment]
1 small inconvenience:
![](https://i.imgur.com/ktOIqhf.png)
But, in preference it displays incorrectly:
![](https://i.imgur.com/StZa7OI.png)

**Comment by machour** [comment]
Thank you for noticing it @rancidfrog !
@housseindjirdeh could you update the composer.json file and release 1.4.1? (or else it will be nightmarish to understand the current version when the user reports a bug :D)

**Comment by ocarreterom** [comment]
package.json version is `1.3.0` in master :/

**Comment by machour** [comment]
yes, we need a step by step release guide to make sure we don't make this mistake again 😆

**Comment by rancidfrog** [comment]
Quick question,
Is the [apk  in release section](https://github.com/gitpoint/git-point/releases/tag/1.4.0) debug apk or release?
Because, there is considerable lag which can be seen in video attached.
Lag results in clicks being registered multiple times, for example near the end of video you see me clicking back 6 or more times from options only to have another options appearing repeatedly due to multiple clicks being registered when screen lagged.
Might need a new issue, but just making sure.
https://github.com/rancidfrog/project-info/raw/master/gp0.mp4

**Comment by housseindjirdeh** [comment]
@machour @rancidfrog apologies for missing that step during the release 😞 I just pushed out v.1.4.1 fixing that

@rancidfrog interesting - that should be the release apk 🤔. Thank you for logging this. I just put out 1.4.1 and this is how it renders on my simulator:

![android](https://user-images.githubusercontent.com/12476932/34137824-bac48dd6-e43a-11e7-8ab2-bbdd5cfda3d1.gif)

If it's not too much trouble, can you give v.1.4.1 a shot and let us know? Happy to open a separate issue if you're still experiencing it. Moreover, can anyone else please let me know if they're experiencing lag on their Android device with the latest version from the Play Store.

**Comment by housseindjirdeh** [comment]
Will close this for the meantime, let's address anything in newer tickets if we need to (but we can continue the discussion here :))
