### ISSUE TITLE
Backlog!

### ISSUE THREAD

**Issue by alejandronanez** [gitpoint/git-point#57]
Hey @housseindjirdeh I've seen quite some new issues in the project, what do you think about having a Roadmap with the most urgent features? I think we can use `Github projects` to make this happen.

Thanks!

**Comment by alejandronanez** [comment]
I'm seeing you're already making some good progress @housseindjirdeh in the [projects](https://github.com/gitpoint/git-point/projects/1) tab. I'm closing this then.

**Comment by housseindjirdeh** [comment]
Thank you, I hope you have access to editing the project? Please let me know if you like the way it's structured and feel to move things around priority if you think I'll be okay with it.

We can discuss on this issue on process improvements at any point too 🙌

**Comment by alejandronanez** [comment]
That's all right! I think I have enough permissions already =] Will let you know if I need something.
