### ISSUE TITLE
Add submit new issue functionality

### ISSUE THREAD

**Issue by housseindjirdeh** [gitpoint/git-point#58]
Thank you @FlorianTaut for suggesting this :)

Will be awesome to be able to do this. Here's what I'm envisioning on the `IssueListScreen`:

<p align="center">
<img src = "https://user-images.githubusercontent.com/12476932/28227618-c98502e6-68a8-11e7-8e2e-7a8e81f6b6b7.png" width=250>
</p>

Only in the that screen --> add a + icon to the top right corner and when clicked it takes you to a form type screen that looks just like `PullDiffScreen`. An issue title input and an issue description input and a simple list item for `Submit new issue`. 

Please take a look at how I added a `cog` icon to the top right in the `PullDiffScreen` to get an idea of how I added a top right icon with actions in the navbar.

Once the API is hit and successful - we can use the response to navigate directly to the newly submitted issue. We can rely on the awesome work done by `@mikekavouras` and show the `loading-modal` until the call is complete similar to how he handled forking in #50.

**Comment by Antoine38660** [comment]
I have some time next week to do this one. Can you assign me to this one if it's ok for the roadmap?

As I said, I'll need some help, specially for the API request :)

**Comment by andrewda** [comment]
Awesome @Antoine38660! I can definitely help out, too, if you need it :)

**Comment by andrewda** [comment]
That's great @Antoine38660! I think a new PR would probably be best so we can move discussion there :)
