### ISSUE TITLE
Notifications badge count has styling issues

### ISSUE THREAD

**Issue by chinesedfan** [gitpoint/git-point#581]
Separated from #569.

![image](https://user-images.githubusercontent.com/12476932/31921499-ac0b161c-b83d-11e7-96f4-cba1b7dd6494.png)

**Comment by JSLinn727** [comment]
So you want it to be a complete circle? I will take this issue just need to know exactly what you want it to look like.

**Comment by alejandronanez** [comment]
@JSLinn727 yeah it should be a full circle with the number in the middle.
Thanks for your interest!

**Comment by chinesedfan** [comment]
Fixed by #648.
