### ISSUE TITLE
Coverall badge not showing up in comments

### ISSUE THREAD

**Issue by machour** [gitpoint/git-point#584]
![screen shot 2017-10-26 at 11 11 21 am](https://user-images.githubusercontent.com/304450/32047664-fe5779d2-ba46-11e7-88cf-2c0e6e2234be.png)

Here's what it should look like:

<img width="711" alt="screen shot 2017-10-26 at 11 13 10 am" src="https://user-images.githubusercontent.com/304450/32047686-11e14406-ba47-11e7-965d-a1da83be9333.png">

**Comment by andrewda** [comment]
Is it because the badge is an SVG?

**Comment by machour** [comment]
That's probably the cause.

Images handling could benefit from a good rewrite:
- Support SVG & WEBP
- Initially display a loader, then display the images with the appropriate dimensions when they're loaded (currently it's the same height for all images, hence that big white gap in the screenshot)

**Comment by andrewda** [comment]
:thinking: SVGs seem to work fine in the README.md files. Is there any reason why they'd work there but not in comments?

**Comment by machour** [comment]
README files are displayed in a WebView, whereas comments are rendered using https://github.com/jsdf/react-native-htmlview that transforms the HTML code into native views, so we're using <Image /> here, and it doesn't support SVG out of the box.

Should be easy to implement using something like https://github.com/react-native-community/react-native-svg

**Comment by andrewda** [comment]
Gotchya. That sounds like it should work.
