### ISSUE TITLE
Remove Sinon.js

### ISSUE THREAD

**Issue by alejandronanez** [gitpoint/git-point#588]
We should remove `sinon.js` from our stack, Jest has its own way to do spies and mocks.

When you remove this, don't forget to update the tests.

**Comment by andrewda** [comment]
👍

**Comment by andrewda** [comment]
Apologies for using Sinon in the first place – I had seen it and was excited to use it without looking to Jest's prebuilt solutions 😂

**Comment by alejandronanez** [comment]
haja np!
