### ISSUE TITLE
Pull Request Review Comments

### ISSUE THREAD

**Issue by housseindjirdeh** [gitpoint/git-point#6]
Currently, pull request review comments don't show at all when viewing a PR. Not too sure how we want to include this functionality design-wise just yet, but this is definitely something we need to have. Open to all kinds of suggestions!

**Comment by ericadamski** [comment]
I would love to contribute to the implementation of this once the design has be scoped!

**Comment by housseindjirdeh** [comment]
Thanks a million @ericadamski, going to close this ticket so we can use #472 to discuss about the designs :dancer:
