### ISSUE TITLE
Integrate styled components checking tasks

### ISSUE THREAD

**Issue by chinesedfan** [gitpoint/git-point#604]
It was a pity that we introduced so many styles problems by styled components refactoring. I suggest to integrate 2 more tasks into our Travis CI.

- [`stylelint-processor-styled-components`](https://github.com/styled-components/stylelint-processor-styled-components), which guarantees basic CSS writing.
- [`styled-components-native-code-mod`](https://github.com/styled-components/styled-components-native-code-mod), which enhances unitless checking.
    - Now it adds units to all properties, but I hope to fork it and only rewrite those necessary shorthands properties.

Of course, they will increase our testing time, but the safety should be more important. And I will also fix the current code base by them at first.

**Comment by machour** [comment]
@chinesedfan I wouldn't mind adding `stylelint-processor-styled-components` as part of CI, but I'm not sure about `styled-components-native-code-mod` which looks more like a conversion utility.

Also, unless I'm missing something, current code base is broken because of an [incompatibility](https://github.com/react-native-training/react-native-elements/issues/679) with `react-native-elements`.

**Comment by alejandronanez** [comment]
I second @machour, We should integrate `stylelint-processor-styled-components` But not the other one, it looks like a conversion tool.

@machour what do you think about rolling back any changes that involve SC + `react-native-elements` (or go with a workaround) ?

**Comment by machour** [comment]
@alejandronanez was about to reply from the app but it crashed 😆 (you fixed it in #602)

A big +1 on rolling back failing PRs for now until react-native-elements is updated.

**Comment by alejandronanez** [comment]
Just to clarify, I meant only roll back changes related to RNE.

**Comment by machour** [comment]
Yes yes :)

**Comment by jamesg1** [comment]
What were the actual benefits of using styled-components? Seems to me it has some issues with supporting third party component libraries.

I use https://github.com/css-modules/css-modules with a work project and enjoy it as it keeps the CSS seperate to the JS.

**Comment by alejandronanez** [comment]
Hey @jamesg1 we already had a discussion about it (I can’t find the issue right now - on mobile) 
My 2 cents on CSS modules is that they work _ok_ but have some restrictions that styled-components address in a really good way.

**Comment by chinesedfan** [comment]
@machour @alejandronanez Right, `styled-components-native-code-mod` is not a real test tool. Adding it here is just for reminding us to have the same ability to avoid unitless shorthands properties crash.

In #612, I tried to fix problems by `stylelint-processor-styled-components`, as well as `stylelint`. Some of them are just styles preferences, and some are fatal. But I have not verified them yet. So it is marked as WIP.

**Comment by machour** [comment]
@jamesg1 the compatibility issue with react-native-elements was fixed in 0.18.1 released yesterday 🎉  You should be able to finish your PR with styled-components soon. We had the discussion Alejandro is referring to in #480.

@chinesedfan could we have a PR adding styling tests in the commit hook? It would be great to have this soon <3

**Comment by chinesedfan** [comment]
@machour Sure, the commit hook can help contributors discover problems sooner at local. I am working on integrating with `stylelint-processor-styled-components` and have sent a [PR](https://github.com/styled-components/stylelint-processor-styled-components/pull/140) to fix its issue of reporting wrong line numbers. Once my PR is accepted, we can enjoy styling lint.

**Comment by machour** [comment]
Great, thank you!
