### ISSUE TITLE
IssueDescription is not rendered very well

### ISSUE THREAD

**Issue by chinesedfan** [gitpoint/git-point#615]
It may due to #563.

Before(v1.3):

![21509632125_ pic](https://user-images.githubusercontent.com/1736154/32330618-a7a61b80-bfae-11e7-8e38-0ea2ac0843b8.jpg)

Now:

![41509632185_ pic_hd](https://user-images.githubusercontent.com/1736154/32330572-89671f5c-bfae-11e7-838c-37a29f929962.jpg)

**Comment by machour** [comment]
@chinesedfan Are you talking about the labels list?

**Comment by chinesedfan** [comment]
@machour Yes, both the repository title and the labels list, as you mentioned in #569.

**Comment by andrewda** [comment]
Yea, this might be one of the things we want to roll back and look into fixing later... There's a bunch of issues here.

**Comment by machour** [comment]
react-native-elements 0.18.1 should be out today according to @Monte9, and it should fix a lot of these issues
