### ISSUE TITLE
Move language picker into a separate screen

### ISSUE THREAD

**Issue by machour** [gitpoint/git-point#620]
Thanks to all the translations that got contributed we now have 14 languages 🎉 

![screen shot 2017-11-04 at 11 55 00 pm](https://user-images.githubusercontent.com/304450/32410221-c8599bb8-c1bb-11e7-8255-2ff8fd86b9a1.png)

I think it's about time we move language selection from the main options screen to a newly dedicated screen.

We could also take this chance to sort the language list.

**Comment by TheCodeTalker** [comment]
making new section for language by click navigate and sorting based upon first letter this what your saying IS it right ?? i want to take it

**Comment by machour** [comment]
@TheCodeTalker fantastic 🎉 yes I had in mind exactly what you described.
Don't hesitate if you need any help with this

**Comment by jouderianjr** [comment]
I think we could use Modal component for that instead create a new screen, what do you think guys?

**Comment by machour** [comment]
That could work too!

**Comment by TheCodeTalker** [comment]
@machour  it cool so is which components i can use for Modal...  reactnative model or any npm component for UI???

**Comment by machour** [comment]
@TheCodeTalker the react-native Modal will do just fine!

**Comment by TheCodeTalker** [comment]
hey @machour  sorry for the delay i update as soon as possible.

**Comment by machour** [comment]
No worries mate, just checking on you :)
