### ISSUE TITLE
Add support for <sub> in markdown

### ISSUE THREAD

**Issue by machour** [gitpoint/git-point#627]
Currently `<GithubHtmlView />` lacks support for the `<sub>` HTML tag.

For example:

<sub>This sentence is rendered as really small on github, but not in gitpoint</sub>.

If anyone wants to tackle this issue, I will gladly provide help 🎉

**Comment by AkshayIyer12** [comment]
I want to work on this issue.

**Comment by andrewda** [comment]
@AkshayIyer12 Thanks for the interest! I think we already have #629 open. It still needs some changes, though, so feel free to take a look at that code!

**Comment by machour** [comment]
Hi @AkshayIyer12 and thank you for your interest. @TheCodeTalker is already working on this one in PR #629 
Can you pick another issue?
