### ISSUE TITLE
Contributor icons being cut off at the end

### ISSUE THREAD

**Issue by CameronSamuels** [gitpoint/git-point#639]
On an iPhone SE, the contributor icons are cut off at the end (right). It only shows about half of the last icon.

**Comment by chinesedfan** [comment]
@CameronSamuels If you are using a released app, I think it has been fixed by #491.

**Comment by machour** [comment]
Yes, this was already fixed and will be shipped in 1.4.0.
Thank you for reporting it Cameron!

**Comment by CameronSamuels** [comment]
Sorry for the duplicate
