### ISSUE TITLE
Showing NaN while loading profile

### ISSUE THREAD

**Issue by junedomingo** [gitpoint/git-point#64]
Causing by adding private repos that aren't loaded yet.

![simulator screen shot 15 jul 2017 12 45 10 pm](https://user-images.githubusercontent.com/5106887/28236602-362f1f5e-695c-11e7-83d2-bdf6ac8c13f1.png)

**Comment by housseindjirdeh** [comment]
I just noticed this today and was about to put up a fix - thank you for spotting it and putting up a PR <3
