### ISSUE TITLE
Feature Request: Ability to Edit Profile picture within the App

### ISSUE THREAD

**Issue by coderste** [gitpoint/git-point#642]
Is there anyway we could change our Profile Picture from within the app? Or does the GitHub API not allow us to do this?

**Comment by jouderianjr** [comment]
Hey mate, we have a issue for that #8 I really think that's very important to have :D, do you would like to work on that? 💃

**Comment by coderste** [comment]
@josenaranjo Hey I can give it a shot after work :D

**Comment by jouderianjr** [comment]
Awesome, we are here if you want any help 😄

**Comment by vitalkanev** [comment]
And after checking [dev docs](https://developer.github.com/v3), I didn't even find this thing - We can only modify `name`, `email`, `blog`, `company`, `location`, `hireable` and `bio` ([Source](https://developer.github.com/v3/users/))

**Comment by coderste** [comment]
@vitalkanev I thought we might not be able to - that is why I asked the question in the issue whether we can actually use the API to edit the Image. As you have pointed out it seems like we can't 😞

Still be nice to have customizable bio etc. But I believe there is already an issue for such feature - so feel free to close this one 😃

**Comment by machour** [comment]
The GitHub team have been quiet responsive and welcoming to our feedbacks. Maybe you can contact them to request this feature? I usually contact them via the github.com contact form

**Comment by machour** [comment]
Reached out to GitHub, I don't think this will be available soon:

<img width="568" alt="screen shot 2018-01-16 at 4 18 46 pm" src="https://user-images.githubusercontent.com/304450/34996198-26c6b1ee-fad9-11e7-9be2-f3d7db7edf51.png">

Closing this issue as the FR is already logged in #8
