### ISSUE TITLE
Issue: GitPoint Crashes

### ISSUE THREAD

**Issue by derjoker** [gitpoint/git-point#645]
| Question         | Response    |
| ---------------- | ----------- |
| Version?         | v1.3.0      |
| Devices tested?  | iPhone 8 (iOS 11) |

---

## What Currently Happens?

Crashes 

## What Do You Expect To Happen?

It should work.

## My Reproduction Steps

1. install from app store
1. login GitHub
1. crash

I've recorded screen.
[bug_gitpoint_v1_3_0.MOV](http://ozepvqvwx.bkt.clouddn.com/bug_gitpoint_v1_3_0.MOV)

**Comment by chinesedfan** [comment]
@derjoker Thanks for reporting. Can you check #436? Hope we can release the next version as soon as possible.

**Comment by derjoker** [comment]
@chinesedfan yes, I think it's a problem with Chinese. At least when I switch to English or German, it works.

**Comment by chinesedfan** [comment]
@derjoker All right. This problem has been fixed in #479. Please use the workaround in #436 to play with GitPoint until we release 1.4.
