### ISSUE TITLE
Handle network error in login screen

### ISSUE THREAD

**Issue by machour** [gitpoint/git-point#646]
| Question         | Response    |
| ---------------- | ----------- |
| Version?         | master      |
| Devices tested?  | iPhone 7... |

---

## What Currently Happens?

I'm on a *really* poor connection these days, and just tried to login in GitPoint, this happened:

<img width="349" alt="screen shot 2017-11-23 at 12 55 47 pm" src="https://user-images.githubusercontent.com/304450/33171787-eb03f41a-d04d-11e7-9b72-11dc22d1b8f4.png">

```
2017-11-23 12:55:03.939 [warn][tid:com.facebook.react.JavaScript] 'Encountered an error loading page', { domain: 'NSURLErrorDomain',
  loading: false,
  description: 'The network connection was lost.',
  target: 84,
  code: -1005,
  canGoBack: false,
  title: 'GitHub · Where software is built',
  url: 'https://github.com/login?client_id=87c7f05700c052937cfb&return_to=%2Flogin%2Foauth%2Fauthorize%3Fclient_id%3D87c7f05700c052937cfb%26redirect_uri%3Dgitpoint%253A%252F%252Fwelcome%26response_type%3Dtoken%26scope%3Duser%2Brepo%26state%3D0.7673387498480858',
  canGoForward: false }
```

I'm forced to terminate the App and restart it, as the "CANCEL" button is disabled.

## What Do You Expect To Happen?

This error should be gracefully handled and the "CANCEL" button should be enabled back.

## My Reproduction Steps

Live in Tunisia with a bad DSL provider 😆

**Comment by alejandronanez** [comment]
Hey @machour I can take this one. Is this still happening?

Thanks!

**Comment by machour** [comment]
Hey! my ISP problem was fixed so I can't tell for sure, but I just wiped clean the app on my android device, shut down the connection and launched the app, and I'm left with a big empty gray screen with the cancel button when I try to login.

We definitely need to gracefully handle network issues (wether it's really slow or simply turned off)

**Comment by alejandronanez** [comment]
I'll take it then :)
