### ISSUE TITLE
Application crashes when user try to open a PDF file

### ISSUE THREAD

**Issue by rn4n** [gitpoint/git-point#650]
On repositories that have any PDF file, if the user try to open (or accidently open) the file, the application crashes.

### Steps to Reproduce
- using Gitpoint, open any repository that contains a .pdf file on files viewer tree.
- tap on the file, to view it.
- the app crash.

### Environment
- Android 7.0
- GitPoint 1.3.1

**Comment by chinesedfan** [comment]
@reebr Thanks for reporting! Sorry that I opened with a blank view in my iPhone 6P, iOS 11.1, GitPoint 1.3. No crash happened.

@machour Can you take a try to confirm this issue?

**Comment by jouderianjr** [comment]
I got the same error here (Nexus 5X, Android 8.0) :/

**Comment by machour** [comment]
Confirmed. On android the error message is `error calling RTCDeviceEventEmitter.emit failed to create Value from Json`.

I guess we shouldn't try to render PDF (and other binary files) through `<SyntaxHighlighter />` 😄 

Here's what currently Github provides for files:
<img width="895" alt="screen shot 2017-12-01 at 3 44 42 pm" src="https://user-images.githubusercontent.com/304450/33487822-da3303c6-d6ae-11e7-88da-4020bb36d6a7.png">

We could use `download_url` with `react-native-fetch-blob` to enable the user to download the file.

We could also implement PDF rendering using https://github.com/wonday/react-native-pdf for example, although I think we should consider something more generic and able to handle more file formats, like https://github.com/philipphecht/react-native-doc-viewer

**Comment by olegkorol** [comment]
Hi!
Is this issue still actual?
I can open PDFs from my Xiaomi Mi A1:

![android_xiaomi](https://user-images.githubusercontent.com/13587499/47109618-043a9e80-d24f-11e8-8477-6667f2a83c49.jpg)

**Comment by reebr** [comment]
@olegkorol yes, It still crashing.
Are you opening directly through the app? Did not associate any standard applications to open PDF files?

I've created a repository for tests, check it and try to open the file on tree:
https://github.com/reebr/gitpoint-pdf-issue

Error:

![](https://i.imgur.com/tSIyBtc.png)

**Comment by olegkorol** [comment]
Oh ok, now I understood the issue and could reproduce it. Thanks @reebr 👍 

So basically if you click on a link in a README file that points to a .pdf file it works.
On the other hand, when trying to open a .pdf file that is part of the source code it crashes.

Do you guys mind if I try to fix the bug?

**Comment by lex111** [comment]
Hey @olegkorol 

We will be very happy if you fix this bug :open_hands:

**Comment by housseindjirdeh** [comment]
Thanks a million @olegkorol, we would _love_ a fix for this :)
