### ISSUE TITLE
UI adjustments after commenting on issue

### ISSUE THREAD

**Issue by machour** [gitpoint/git-point#660]
| Question         | Response    |
| ---------------- | ----------- |
| Version?         | master      |
| Devices tested?  | iPhone 7, Android Nexus 5 |

---

## What Currently Happens?

While testing #658, I noticed to little glitches happening after a successful comment on an issue:

* The screen scrolls down, but just above the newly posted comment. I still have to manually scroll to display it
* Timeago says `in 2 seconds` (future), on both Android & iOS:

<img width="320" alt="screen shot 2017-12-10 at 11 04 17 am" src="https://user-images.githubusercontent.com/304450/33803920-0eb2157c-dd9b-11e7-8a52-1845ea491a5b.png">
<img width="356" alt="screen shot 2017-12-10 at 11 06 50 am" src="https://user-images.githubusercontent.com/304450/33803921-0ed990ca-dd9b-11e7-86d3-650d432ec97e.png">

## What Do You Expect To Happen?

* The new comment should be displayed on the screen, without any further scrolling
* Timeago should report a date in the past

## My Reproduction Steps

1. Comment on a issue with enough comments to have to scroll down (ex: https://github.com/machour/git-point-playground/issues/34)

**Comment by machour** [comment]
curious if any of you can reproduce the timeago issue, or if it's my simulator being out of sync with my laptop

**Comment by chinesedfan** [comment]
@machour I have some guessed explanations about it.
- Scrolling
  - Note that `this.props.postIssueComment` is an async operation. [scrollToEnd()](https://github.com/gitpoint/git-point/blob/master/src/issue/screens/issue.screen.js#L255) should be called after the api was returned.
- Time
  - The app time, as well as the device time, may be not matched with Github server time. Unless Github provides the time string directly to replace our [time calculation](https://github.com/gitpoint/git-point/blob/master/src/components/comment-list-item.component.js#L181), we can't avoid this problem.

**Comment by machour** [comment]
@chinesedfan makes perfect sense, thank you!

For time, we could at least detect that we're about to display a future date and display "now" instead, or something like that.

**Comment by machour** [comment]
GitHub uses: `just now`

<img width="433" alt="screen shot 2017-12-10 at 12 01 40 pm" src="https://user-images.githubusercontent.com/304450/33804283-eeb9439c-dda1-11e7-8b1c-306d80313257.png">

**Comment by machour** [comment]
@chinesedfan fixing the scroll was trickier than expected 😮 see the PR.
And it appears that the future-time-ago was fixed by switching to date-fns :)
