### ISSUE TITLE
LOGIN.FAILURE not defined

### ISSUE THREAD

**Issue by pallavbakshi** [gitpoint/git-point#678]
| Question         | Response    |
| ---------------- | ----------- |
| Version?         | v1.4.2      |
| Devices tested?  | Xiaomi mi 4 - Android 5.2 |

---

## What Currently Happens?
Inside file auth.reducer.js in auth folder you are using LOGIN.FAILURE and LOGOUT.FAILURE. However, if you look at in the types you will find that you have defined LOGIN.ERROR/ LOGOUT.ERROR not LOGIN.FAILURE. This is a minor bug, you can just change the names. Look at the  utils/action.helper.js to check the declaration. 

I am not getting any error therefore I cannot write steps to reproduce it. This is just a bug which I came across while going through your project. Thanks :D

**Comment by chinesedfan** [comment]
@pallavbakshi Nice catch! It's a good chance for creating your first PR if you like.

**Comment by pallavbakshi** [comment]
@chinesedfan Sure! Will do so :D

**Comment by machour** [comment]
Seems like this was addressed in #685 🎉

**Comment by pallavbakshi** [comment]
Great work! Sorry I wasn't able to get it done in time. Something personal came up which needed my attention. By the way, I found three more :bug: . This time I will find a fix first and then report the bug. Awesome work guys :D

**Comment by machour** [comment]
No worries, there are always plenty things to do around here :) Feel free to join us on gitter at anytime!

**Comment by chinesedfan** [comment]
@pallavbakshi No problem. You can also report the bug without pull request. Unless you want to hide and fix by yourself. 😆
