### ISSUE TITLE
Remove styledFonts and use fonts everywhere

### ISSUE THREAD

**Issue by ZahraTee** [gitpoint/git-point#688]
Recently, styledFonts was introduced for use in the styled-components migration for slightly nicer syntax. However, in discussion on numerous subsequent PRs it seems there is some desire to remove it and stick to using fonts only to prevent things getting out of sync.

**Comment by housseindjirdeh** [comment]
Agreed, thank you for logging this @ZahraTee 🙌

**Comment by machour** [comment]
I'm up for this today (and this will allow me to finish #533 :D )

**Comment by housseindjirdeh** [comment]
Thank you @machour for tackling this <3
