### ISSUE TITLE
Wrong info when i click on forked to

### ISSUE THREAD

**Issue by jstrobel** [gitpoint/git-point#690]
When some forked you get the info like „USER forked REPO to REPO2“
When i click REPO2 in only get a view which looks like a repo but without title etc

**Comment by machour** [comment]
Hi @jstrobel and thank you for logging this! I just ran a quick test, and I was able to reproduce what you describe only with a **deleted** fork.

Could you check on github web and confirm if the fork you were trying to access was deleted too?

My reproduce case was with this event:
<img width="671" alt="screen shot 2018-01-13 at 10 44 54 pm" src="https://user-images.githubusercontent.com/304450/34910360-79ae0614-f8b3-11e7-8c6d-370a6f333042.png">

which leads to a 404 on web:
<img width="422" alt="screen shot 2018-01-13 at 10 45 09 pm" src="https://user-images.githubusercontent.com/304450/34910363-84a4901a-f8b3-11e7-9c01-103c17674477.png">

GitPoint should definitely print an error message in that case, even though I think that there's a bug with GH API, which should not return these (obsolete) events.

**Comment by jstrobel** [comment]
@machour You are right, i verified it. Deleted i my case too
