### ISSUE TITLE
Repositories list is cropped

### ISSUE THREAD

**Issue by machour** [gitpoint/git-point#694]
| Question         | Response    |
| ---------------- | ----------- |
| Version?         | dev-master     |
| Devices tested?  | iPhone 7 |

---

## What Currently Happens?

Repositories list is cropped at bottom:

![simulator screen shot - iphone 6 - 2018-01-15 at 23 15 32](https://user-images.githubusercontent.com/304450/34963987-8ae10bfe-fa4b-11e7-9ec1-f388ae592a04.png)

## Explanation

Problem introduced in https://github.com/gitpoint/git-point/pull/683/commits/72e31fbeae4fb28d23a71a2d42cdb0cb54a49fec on PR #683, it seems that the View element was needed after all (my bad)

**Comment by housseindjirdeh** [comment]
Thanks a million for getting to this so fast @machour
