### ISSUE TITLE
Crash on viewing pull request

### ISSUE THREAD

**Issue by brettdh** [gitpoint/git-point#713]

**Comment by brettdh** [comment]
Gah, web UI ate my description. Let’s try that again.

**Comment by machour** [comment]
Hi @brettdh, thank you for logging this. 
Could you give a link to the pull request that causes the crash?

**Comment by machour** [comment]
Please use the issues template while you're at it ;)

**Comment by brettdh** [comment]
#713

**Comment by brettdh** [comment]
Agggh. #714
