### ISSUE TITLE
Gitpoint does not navigate to StarredRepositoryList screen

### ISSUE THREAD

**Issue by jarvisluong** [gitpoint/git-point#716]
| Question         | Response    |
| ---------------- | ----------- |
| Version?         | v1.4.1      |
| Devices tested?  | iPhone X |

---

## What Currently Happens?

When I go to profile view, tap to starred repositories list but the app doesn't navigate me to that StarredRepositoryList screen.

Screen record demo: https://www.youtube.com/watch?v=xGzXJhZFPNM

## What Do You Expect To Happen?

The app navigates me to StarredRepositoryList screen after tapping into the icon

## My Reproduction Steps

1. Install the app
1. Login using Github account (in my case I use two factor authentication)
1. Go to user profile screen
1. Tap into Starred Repository button

**Comment by chinesedfan** [comment]
Hi @jarvisluong, this feature is introduced by #341 and will be included in the next release.
