### ISSUE TITLE
error: Module does not exist in the module map

### ISSUE THREAD

**Issue by MrZhang123** [gitpoint/git-point#720]
### environment

macOS 10.13.3
android 7.1.0
node 6.11.2
react-native-cli 2.0.1

### describe
I run `react-native run-android` in terminal , but get `red screen`, message is `error: bundling failed: Error: Unable to resolve module `config` from `/Users/imac/Documents/file/my_fe/github/git-point/App.js`: Module does not exist in the module map`

I use [Troubleshooting](https://github.com/gitpoint/git-point/blob/master/CONTRIBUTING.md#troubleshooting) to fix it , bug it not work, how to fix it ?

**Comment by chinesedfan** [comment]
Hmm, I have met this problem several times. But usually, `yarn start -- --reset-cache` is enough for me.

Please go to our [Gitter channel](https://gitter.im/git-point) to seek more help. Glad to see a new friend.
