### ISSUE TITLE
Shall we delete `repository-section-title` completely

### ISSUE THREAD

**Issue by chinesedfan** [gitpoint/git-point#725]
This component is useless. Deleting it can avoid confusions.

**Comment by machour** [comment]
Yes we can!

<img width="765" alt="screen shot 2018-02-14 at 1 33 17 pm" src="https://user-images.githubusercontent.com/304450/36204465-aa7ee344-118b-11e8-8268-038d66161daf.png">

**Comment by chinesedfan** [comment]
@machour Thank you! It's on Gitter! That's why I didn't find anything in issues and PRs. 😆
