### ISSUE TITLE
Odd vertical spaces in markdown comments

### ISSUE THREAD

**Issue by machour** [gitpoint/git-point#728]
| Question         | Response    |
| ---------------- | ----------- |
| Version?         | v1.4.1      |
| Devices tested?  | iPhone 7 |

---

## What Currently Happens?

Markdown comments contains weird vertical spacings:

![simulator screen shot - iphone 6 - 2018-02-14 at 10 55 53](https://user-images.githubusercontent.com/304450/36198347-a28ab3bc-1176-11e8-856a-b6d03c2410ce.png)

## What Do You Expect To Happen?

Not that much spaces! It seems like Github introduced extra spaces in their HTML transformation.

## My Reproduction Steps

Check this PR: https://github.com/theliturgists/app/pull/45

**Comment by housseindjirdeh** [comment]
Just got merged in :)

THANK YOU FAM
