### ISSUE TITLE
Add support for emoji in issues labels

### ISSUE THREAD

**Issue by machour** [gitpoint/git-point#734]
GitHub now supports [emojis in labels](https://github.com/blog/2505-label-improvements-emoji-descriptions-and-more). We need to implement parsing in labels:

<img width="521" alt="screen shot 2018-02-23 at 9 19 41 am" src="https://user-images.githubusercontent.com/304450/36584637-c982d264-187a-11e8-877c-f98f41479a14.png">

**Comment by machour** [comment]
This needs to be taken care of everywhere:

<img width="323" alt="screen shot 2018-02-23 at 9 33 37 am" src="https://user-images.githubusercontent.com/304450/36585092-b69b84e6-187c-11e8-8130-9eaf5f6c629d.png">

<img width="318" alt="screen shot 2018-02-23 at 9 33 19 am" src="https://user-images.githubusercontent.com/304450/36585117-cfa7bacc-187c-11e8-9ddb-3926ae6275b7.png">

**Comment by jamesg1** [comment]
Hey I would like to do this one :)

**Comment by machour** [comment]
Please do :)
