### ISSUE TITLE
Support iPhone X

### ISSUE THREAD

**Issue by TejasQ** [gitpoint/git-point#738]
## What Currently Happens?
The app does not use the iPhone X's entire screen

## What Would You Like to Happen?
I'd like the app to look beautiful on the iPhone X.

**Comment by TejasQ** [comment]
Just saw #707

**Comment by machour** [comment]
😄 
Can you confirm that version 1.5.0 is looking good on your iPhone X? The support was developed using a simulator only, we may have missed a few things. Thank you!

**Comment by TejasQ** [comment]
Actually, it doesn't work at all on the iPhone X.

![img_56b4645b75bd-1](https://user-images.githubusercontent.com/9947422/36666597-6ee282f0-1aeb-11e8-9f29-723023367aa6.jpeg)

**Comment by TejasQ** [comment]
I can also confirm that this _is, in fact_ version 1.5.0.

**Comment by machour** [comment]
@TejasQ thank you so much for verifying! Weird, this should look like this:
<img width="418" alt="screen shot 2018-02-26 at 11 56 12 am" src="https://user-images.githubusercontent.com/304450/36666827-25985d08-1aec-11e8-8da7-f1377d293e1b.png">

@housseindjirdeh was 1.5 published with the iPhoneX PR? Any chance we missed a needed additional step when releasing? 🤔 

I see that in XCode, we still target iOS 8:
![screen shot 2018-02-26 at 12 01 05 pm](https://user-images.githubusercontent.com/304450/36667051-e9ad1364-1aec-11e8-9cb5-fc42e5a68a94.png)

Extract from https://developer.apple.com/ios/update-apps-for-iphone-x/
> Enable full screen native resolution. Your app will run in Full Screen Display Mode on iPhone X if your project’s base SDK is set to **iOS 11** and you have a Launch Storyboard or iPhone X launch image.

**Comment by housseindjirdeh** [comment]
Hmmmm I think you're right @machour - that must be it. I really thought I updated that to 11 before deploying 🤔 

Will update in the next few days and redeploy 1.5.1 with that set to the correct target

Apologies @TejasQ - we'll have this resolved as soon as possible

**Comment by coderste** [comment]
The iPhone X still doesn’t have full screen support - any chance we can get 1.5.1 published to fix this bug?

**Comment by RolfKoenders** [comment]
@coderste Im using it on my iPhone X and its using the fullscreen. The version currently in the App Store is version: 1.6.0.

**Comment by TejasQ** [comment]
Yup. Fixed.
