### ISSUE TITLE
Authorization failed

### ISSUE THREAD

**Issue by marcus-sa** [gitpoint/git-point#740]
Phone: Samsung Galaxy S8+
OS: Latest Android available

Nothing happened at first when I clicked "Authorize Gitpoint" after logging in from the Github window opened on the app.
Then I restarted the app and tried again, then after a few seconds of trying to authorize Gitpoint, it redirects to "gitpoint://welcome" which shows a 405 Not Allowed Nginx error page.

Then after restarting it again, clicking "Authorize Gitpoint" it finally works.

**Comment by machour** [comment]
Hi @marcus-sa, maybe GitHub had a little outage and couldn't process the oAuth when you tried it, and displayed an error page (using the Nginx webserver). 

We're using a WebView for authentication atm, so that would be the explanation.

**Comment by linrz** [comment]
I meet the same problem. It seems that I need an IOS device to complete the first required authorization operation.

**Comment by ShalokShalom** [comment]
There are a couple of similar issues: https://github.com/gitpoint/git-point/issues/674#issuecomment-365206090

They currently consider to add alternative login methods. 
OAuth seems to struggle with different issues since a couple of time on Githubs side.

**Comment by machour** [comment]
This issue was related to a temporary problem with GitHub that have been resolved. Closing this as the oAuth problem is already tracked in 3 other issues.
