### ISSUE TITLE
Markdown rendering issue

### ISSUE THREAD

**Issue by djavalord** [gitpoint/git-point#744]
#### Expected behavior
Launch the app, search a github repository and then read issues and there comments

#### Actual behavior
launched the app, searched a github repository, selected all issues, clicked on the issue with 25 comments (title of the issue is " Timeline doesn't restore its stat..." tag number #389) then the app tried to load, then closed.

#### How to reproduce
download the app from google play store  on the address https://play.google.com/store/apps/details?id=com.gitpoint and then launch the app, searched a github repository, (search for andstatus) select the result, then select all issues, click on the issue with 25 comments (title of the issue is " Timeline doesn't restore its stat..." tag number #389) 

* Browser: Gitpoint- Githum in your pocket. version 1.5.0
* Operating system: Android 5.1.1 Lollipop. Infinix hot 3 LTE

#### Recording Of The Bug
https://youtu.be/NJS82wuhLvw
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@javalord/bug-found-in-gitpoint-while-trying-to-open-issue-with-25-comments">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by machour** [comment]
Hi @djavalord and thank you for reporting this issue.

Testing in development mode, here's the error message:
<img width="376" alt="screen shot 2018-03-21 at 9 54 00 am" src="https://user-images.githubusercontent.com/304450/37701424-4601e054-2cef-11e8-8c49-30ec21cafff4.png">

It seems to be a markdown rendering issue of one of the comments, but I can't exactly pin point it with the debugger. I'll have a deeper look this afternoon.

**Comment by djavalord** [comment]
Okey that will be great

**Comment by machour** [comment]
Renamed the issue as the problem wasn't the number of comments.
We're able to display 100 comments here: https://github.com/npm/registry/issues/255

**Comment by chinesedfan** [comment]
Paste link here for easy testing, https://github.com/andstatus/andstatus/issues/389.
