### ISSUE TITLE
Code-push Integration

### ISSUE THREAD

**Issue by junedomingo** [gitpoint/git-point#75]
Able to update the app instantly.

**Comment by junedomingo** [comment]
I will start working on this tomorrow.

**Comment by housseindjirdeh** [comment]
For anyone who hasn't heard about codepush - [link](https://github.com/Microsoft/react-native-code-push)

Thanks so much @junedomingo, don't hesitate to let us know how things go as you work on it!

**Comment by andrewda** [comment]
Is this fully added and ready to use as of #108?

**Comment by junedomingo** [comment]
Yes! sorry, I forgot to close.
