### ISSUE TITLE
Specific issue page leads to crash 

### ISSUE THREAD

**Issue by ShalokShalom** [gitpoint/git-point#768]
| Question         | Response    |
| ---------------- | ----------- |
| Version?         | current testing  |
| Devices tested?  | Passport |

---

## What Currently Happens?

GitPoint crash

## What Do You Expect To Happen?

Marry me. 

## My Reproduction Steps

1. https://github.com/dotnet/corefx/issues/9855#issuecomment-379604828

Hint: Your template gives 1. 1. 1. 1 here instead of 1. 2. 3. 4.
Why?

**Comment by machour** [comment]
@ShalokShalom about your Hint: it's the same thing in markdown for ordered lists ;)

**Comment by ShalokShalom** [comment]
Can you explain that?

**Comment by ShalokShalom** [comment]
Oh, fine

Thanks for the explanation ^-^

**Comment by chinesedfan** [comment]
Tested after #848 merged as it was an issue with long conversation, but not sure which PR fixed it. The latest markdown related is #819.
