### ISSUE TITLE
How to debug the project?

### ISSUE THREAD

**Issue by sjtuliwei** [gitpoint/git-point#778]
Can somebody share the procedure to debug this project? 

Thanks.

**Comment by machour** [comment]
Hi @sjtuliwei! It totally depends on what you're looking into. Are you running through problems starting the app, or are you looking into a particular issue?

Did you check the CONTRIBUTING.md file?

**Comment by sjtuliwei** [comment]
I can run it on simulator following the steps in the documentation. I want to know whether I can set breakpoint and run the code step by step.

Thanks for the help.

**Comment by machour** [comment]
You will need to enable remote debugging (in the dev menu in the app) and then either use chrome, or React Native debugger

**Comment by machour** [comment]
https://github.com/jhen0409/react-native-debugger

**Comment by sjtuliwei** [comment]
Got it. Thanks.
