### ISSUE TITLE
Revert the commit about ip.txt

### ISSUE THREAD

**Issue by chinesedfan** [gitpoint/git-point#780]
@machour I am sorry it seems that we need to revert #705. The existed `ip.txt` makes `RCTBundleURLProvider.m:guessPackagerHost` returns empty string as the packager host.

And adding `ip.txt` to `.gitignore` can not prevent git from reminding about local changes. Maybe because it is already recorded by git.

Don't know why the following error is not found previously. Not sure whether related to the upgrade of RN(#757) or not.

<img width="372" alt="2018-04-22 6 28 05" src="https://user-images.githubusercontent.com/1736154/39094126-4550468c-465d-11e8-9c36-15257c61c025.png">

**Comment by machour** [comment]
Well, it was worth those past sweet days I had with this on. 😆
 I'm fine with reverting!
