### ISSUE TITLE
Icons mismatch

### ISSUE THREAD

**Issue by housseindjirdeh** [gitpoint/git-point#793]
Some minor regressions (due to #781 I think 🤔 )

A few icons are displaying incorrectly:

<img width="415" alt="screen shot 2018-04-25 at 12 55 59 pm" src="https://user-images.githubusercontent.com/12476932/39260904-ce08e740-4888-11e8-86b5-0d0ac58affa5.png">

<img width="466" alt="screen shot 2018-04-25 at 12 55 29 pm" src="https://user-images.githubusercontent.com/12476932/39260905-ce175686-4888-11e8-8487-9cb0318588f6.png">

<img width="415" alt="screen shot 2018-04-25 at 12 55 13 pm" src="https://user-images.githubusercontent.com/12476932/39260906-ce2736dc-4888-11e8-9f15-d356a55a6066.png">

CC @machour

**Comment by machour** [comment]
😂 😂 😂 

could you try rm -rf node_modules & recompile the app? I think there's something wrong with your react-native-vectore-icons local copy

**Comment by housseindjirdeh** [comment]
😅 

I did clear my node modules and `yarned` things again 🤔 But it very well could be the native bindings on my end that's behind?

Will clear it again

**Comment by machour** [comment]
Just tried on a clean fork, icons are okay:

| | |
| - | - |
|![simulator screen shot - iphone 6 - 2018-04-26 at 09 58 21](https://user-images.githubusercontent.com/304450/39296294-72aefca8-4938-11e8-9a06-86893bcfa14e.png)|![simulator screen shot - iphone 6 - 2018-04-26 at 09 58 15](https://user-images.githubusercontent.com/304450/39296295-72d2b008-4938-11e8-8dc6-a1900b6f7f1f.png)|

**Comment by housseindjirdeh** [comment]
Sweet, will close this. Will try to completely clear everything and see if I'm still experiencing things 👍
