### ISSUE TITLE
Double loading indicator

### ISSUE THREAD

**Issue by housseindjirdeh** [gitpoint/git-point#794]
Noticed this some time ago but I don't think we have an issue open.

On the issue screen, we have a loading state that shows twice can probably grouped into just one.

![two loading indicators in issue screen](https://user-images.githubusercontent.com/12476932/39264209-526ecb04-4892-11e8-9c47-33aa79e9a244.gif)

**Comment by chinesedfan** [comment]
It is due to issue events are fetched separately. We can fix temporarily or wait refactoring the issue screen with new Redux store/GraphQL.

```
     // issue.screen.js:render
     const isShowLoadingContainer =
-      isPendingComments || isPendingIssue || isPendingEvents;
+      isPendingComments || isPendingIssue;
```

**Comment by Chandrasekar-G** [comment]
Can I take this up or is this already done?

**Comment by chinesedfan** [comment]
> It is due to issue events are fetched separately. We can fix temporarily or wait refactoring the issue screen with new Redux store/GraphQL.

Done by #848.
