### ISSUE TITLE
Moving internal docs to Wiki

### ISSUE THREAD

**Issue by machour** [gitpoint/git-point#796]
Something I had in mind for quiet some time: Could we move our internal documentation to the GitPoint Wiki?

This would help us having a better development guide, maintained outside the repository, and we would have a real life wiki example when we start working on #220.

Edited a first version of the doc here: https://github.com/machour2/test/wiki

* Scavenged bits from `CONTRIBUTING.md` and `TESTS.md`
* Split the big Setup section in two: "Setup" and "Working on a PR"
* Wrote the I18n documentation

If it's okay with ya'll, I'll copy pages over the GitPoint wiki, remove TESTS.md and trim down CONTRIBUTING.md to only keep the relevant bits.

**Comment by housseindjirdeh** [comment]
All for it 🚀 🚀 

Thank you, this can clean things up nicely for our docs

**Comment by machour** [comment]
Done
