### ISSUE TITLE
Infinite loading error

### ISSUE THREAD

**Issue by cjavad** [gitpoint/git-point#798]
Version: 1.5.0
Device: iPhone se

## what happends?
GitPoint loads forever an it’s impossible to do anything

## what where you expecting?
For it to load

Steps to reproduce:
  - install and login
  - change github username
  - open app

Workaround:
Reinstall the app

**Comment by machour** [comment]
Hi @cjavad and thank you for logging this issue. Did you by any chance deauthorize git-point from your github account setting?

**Comment by chinesedfan** [comment]
Hi @cjavad, does `change github username` mean changing your logined account name in other places?

**Comment by cjavad** [comment]
I changed my username from javadsm to cjavad via github when this occured

**Comment by cedric05** [comment]
can i take this up?

**Comment by chinesedfan** [comment]
@cedric05 Sure. Please go ahead.

**Comment by cedric05** [comment]
i tried building and couldn't in my mac. someone else please take up

**Comment by chinesedfan** [comment]
Same as #477.
