### ISSUE TITLE
Emojis on Issue-Comments

### ISSUE THREAD

**Issue by jstrobel** [gitpoint/git-point#804]
I would be nice if i can see the emojis on a comment and set them.

![github-issue-emoji](https://user-images.githubusercontent.com/1428396/40667055-7d4a90bc-6361-11e8-8bef-64ae98fbcf09.png)

**Comment by chinesedfan** [comment]
Yes, but duplicated of #25. Hope someone can pick up and implement it.

**Comment by jstrobel** [comment]
Sorry hadn't found it. Thanks.
