### ISSUE TITLE
Large number of stars showing

### ISSUE THREAD

**Issue by lukakerr** [gitpoint/git-point#821]
| Question         | Response    |
| ---------------- | ----------- |
| Version?         | v1.6.0      |
| Devices tested?  | iPhone X |

---

## What Currently Happens?

On all accounts the number of stars is largely inflated. For example my account:

![](https://i.imgur.com/pdrdSqX.jpg)

And some other users account:

![](https://i.imgur.com/fDQ7mTG.jpg)

## What Do You Expect To Happen?

The proper amount of stars the user has should be shown

## My Reproduction Steps

Visit any account

**Comment by RolfKoenders** [comment]
Interesting issue. For me the number showing on my profile page in the app is exactly the same as the number on my Github profile on web. When i go to your profile in the app i also see the correct amount of starred repo's. @lukakerr Are you using the latest version?

**Comment by lukakerr** [comment]
I am using the latest version. But the issue seems to have fixed itself.. Not sure what was going on earlier
