### ISSUE TITLE
Some organization page not displayed correctly

### ISSUE THREAD

**Issue by garywill** [gitpoint/git-point#826]
| Question         | Response    |
| ---------------- | ----------- |
| Version?         | v1.6.0      |
| Devices tested?  | iPhone SE... |

---

## What Currently Happens?

Some problems opening some organization page, like [this page](https://github.com/SimpleNexus), on gitpoint.
1. Opening this page from home screen cause white blank freeze.
1. Opening this page from search won't display repo number.

### 1
1. Open gitpoint and see a news item about [SimpleNexus](https://github.com/SimpleNexus)
1. Touch SimpleNexus
1. White blank freeze

### 2
1. Search for user "SimpleNexus" on gitpoint
1. Touch SimpleNexus
1. Infomation not displayed correctly on that organization page

**Comment by chinesedfan** [comment]
This problem is due to the schema id of orgs is converted to lower case, see `api/shcemas/orgs.js`. I am not sure whether there is something similar existed. Because other entities, like repos/users, are also converted to lower case. A simple fix of this case may like,

```
--- a/src/organization/screens/organization-profile.screen.js
+++ b/src/organization/screens/organization-profile.screen.js
@@ -189,7 +189,7 @@ const mapStateToProps = (state, ownProps) => {
   } = state;
 
   const orgId = ownProps.navigation.state.params.organization.login;
-  const org = orgs[orgId] || ownProps.navigation.state.params.organization;
+  const org = orgs[orgId.toLowerCase()] || ownProps.navigation.state.params.organization;
```

BTW, we need to set `noMembersMessage` of `MemberList` in `organization-profile.screen.js` as well as `repository.screen.js`.

**Comment by chinesedfan** [comment]
@machour Did you remember why those entities idAttribute were converted to lower cases?

**Comment by machour** [comment]
@chinesedfan here's the origin of this piece of code: https://github.com/reduxjs/redux/blob/master/examples/real-world/src/middleware/api.js#L52

**Comment by machour** [comment]
Ideally the navigation parameter would already be in lowercase (it would be the key of the org entity in our store).

**Comment by chinesedfan** [comment]
@machour Thanks for your link. I found Github API accepts case-insensitive arguments and returns case-sensitive logins. For example, following 3 calls will receive the same login `SimpleNexus`.

- https://api.github.com/orgs/SimpleNexus
- https://api.github.com/orgs/simpleNexus
- https://api.github.com/orgs/simplenexus

So as long as we make sure our store ids are case-sensitive, there will be no possibility to see cases like redux example shows. In that example, it reads login from url, which is out of control. See [source](https://github.com/reduxjs/redux/blob/master/examples/real-world/src/containers/UserPage.js#L76).

> Ideally the navigation parameter would already be in lowercase (it would be the key of the org entity in our store).

Yes, but currently our store is mixed with ids from Github and entities. Maybe we should stop converting entity ids to lower cases.
