### ISSUE TITLE
Issues aren't loading properly

### ISSUE THREAD

**Issue by lukakerr** [gitpoint/git-point#849]
| Question         | Response    |
| ---------------- | ----------- |
| Version?         | v1.6.0      |
| Devices tested?  | iPhone X |

---

## What Currently Happens?

No issues load when viewing via profile/repo

## What Do You Expect To Happen?

Issues should load

## My Reproduction Steps

1. Go to a repository via search/feed repo etc
2. Click on the issue 'View All' button
3. Click on an issue

The result is the following:

![issue](https://user-images.githubusercontent.com/20056300/47981179-f5912a00-e11e-11e8-9267-d4a88e095638.png)

**Comment by chinesedfan** [comment]
Thanks for reporting. It has been fixed in #846.
