### ISSUE TITLE
Update font-family in README

### ISSUE THREAD

**Issue by FlorianTaut** [gitpoint/git-point#85]
Hey,

We could use a more modern font-family for the readme files. At least the family GitHub is using.

Thank you

**Comment by housseindjirdeh** [comment]
Agreed - so in the `README` screen, I simply use `WebView` to render the retreived HTML. I think a possible solution for this may be to just leverage `HTMLView` like I do in `CommentListItem` and apply text styles to it

**Comment by machour** [comment]
Handled in #326

**Comment by machour** [comment]
Fixed in #326
