### ISSUE TITLE
v1.7.0 lacks APK

### ISSUE THREAD

**Issue by IzzySoft** [gitpoint/git-point#863]
Could you please attach the APK to the release of v1.7.0 – for those outside of Playstore? Thanks!

**Comment by chinesedfan** [comment]
@housseindjirdeh Can you attach the file when you have time? And btw, I suggest to make a real release to AppStore/Playstore.

**Comment by IzzySoft** [comment]
@chinesedfan don't forget F-Droid, if possible :wink:

As due to the use of GMS and Firebase the app is not acceptable for the official repo, your app currently [is available in mine](https://apt.izzysoft.de/fdroid/index/apk/com.gitpoint) (but stuck at v1.5.0 due to the missing APKs here). If you can provide a flavor that comes without those, I gladly assist you to bring Git-Point to the official F-Droid Repo, just let me know then!

**Comment by IzzySoft** [comment]
@chinesedfan @housseindjirdeh any news? The APK is still missing.

**Comment by IzzySoft** [comment]
@chinesedfan @housseindjirdeh still nothing?

**Comment by IzzySoft** [comment]
Ugh, any chance – or must we give up on the app?

**Comment by chinesedfan** [comment]
@IzzySoft Be patient or forget this app temporarily. I have been ready to build a new release for several months. But without @housseindjirdeh's help/account/permissions, nothing can be done.

**Comment by IzzySoft** [comment]
Sad, but what can we do? @housseindjirdeh please don't delay this for too long!

**Comment by chinesedfan** [comment]
@IzzySoft Finally. I built a new release, [v1.7.1](https://github.com/gitpoint/git-point/releases/tag/1.7.1).

**Comment by IzzySoft** [comment]
Thanks! But you forgot to increase `versionCode` (which is still set to `7` as was v1.5.0 already). Could you please fix and replace, @chinesedfan? Let me know when it's done, as this time I need to fetch the update manually (as the APK with the wrong `versionCode` is "in the way").

**Comment by chinesedfan** [comment]
@IzzySoft Because git only contains 6(1.4.1), I increased it to be 7(1.7.1). Do you know how to determine the right next versionCode?

**Comment by IzzySoft** [comment]
@chinesedfan it must simply be bigger than any one you've used before. You can use it as "release counter", or simply use the current timestamp (I'd not really recommend the latter – but it's just to give you an idea). And it must be integer.

To find out which you've used before, you can run `aapt d badging` on the other APKs, and grep for `versionCode`. this is the result for 1.5.0 and 1.7.1:

    package: name='com.gitpoint' versionCode='7' versionName='1.5.0' platformBuildVersionName='8.0.0'
    package: name='com.gitpoint' versionCode='7' versionName='1.7.1' platformBuildVersionName='8.0.0'

**Comment by chinesedfan** [comment]
@IzzySoft Updated versionCode to 10. I guessed by the following way. :P

- 7, 1.5.0
- 8, 1.6.0
- 9, 1.7.0
- 10, 1.7.1

**Comment by housseindjirdeh** [comment]
Apologies @IzzySoft, I've been hands off this project for the past few months so I'm sorry about that. @chinesedfan has been leading the project thus far so now I'm making sure he has complete permissions/control over releases and not just me.

@chinesedfan thank you,I wish I kept note of the last versionCode but as long as it's large that's fine. Okay to start and move from 10 onwards :D

**Comment by IzzySoft** [comment]
Thanks @chinesedfan and @housseindjirdeh! I've just grabbed the APK manually and checked, it looks fine! Triggered a manual update in my repo, so it should show up in a few minutes.

Guess this issue can be closed then. Please keep up attaching the APKs to the tags, and of course increasing `versionCode` with each new release :smile:
