### ISSUE TITLE
Some repos load while others don't

### ISSUE THREAD

**Issue by wrongsyntax** [gitpoint/git-point#864]
| Question         | Response    |
| ---------------- | ----------- |
| Version?         | v1.6.0     |
| Devices tested?  | iPhone 6 |

---

## What Currently Happens?

When I attempt to view two of my repositories, they just keep loading forever. This does not happen with all of my repos.

## What Do You Expect To Happen?

I expected the repo to load.

## My Reproduction Steps

1. Go to my profile
2. Select either of the two Python repos
3. It loads infinitely

**Comment by chinesedfan** [comment]
It is a known issue, #826, and has been fixed in #846. Sorry for the inconvenience and hope we can release a new version soon. (cc @housseindjirdeh)
