### ISSUE TITLE
couldn’t navigate anywhere

### ISSUE THREAD

**Issue by gilesbowkett** [gitpoint/git-point#865]
| Question         | Response    |
| ---------------- | ----------- |
| Version?         | v1.6.0    |
| Devices tested?  | small iPad Pro mid-2018 |

---

## What Currently Happens?

After logging in, I tapped Notifications and got a list of notifications. The notifications list displayed no navigation elements of any kind, except for tapping individual notifications. There was no way to exit Notifications. I was trapped there forever, so I deleted the app.

## What Do You Expect To Happen?

I expected navigation to exist. Now, after looking at the pictures in the App Store, I specifically believe that a lower navigation bar should have been there. A lower bar was present, but it contained no icons or navigation affordances of any kind.

## My Reproduction Steps

1. Log in
2. Tap notifications

**Comment by wrongsyntax** [comment]
Did you try restarting the app?

**Comment by gilesbowkett** [comment]
no, I just deleted it. I'm only here because I thought telling you in an App Store review would be rude. I tried it for ten seconds, and then I deleted it because it didn't work.

**Comment by wrongsyntax** [comment]
This seems like a known issue, as seen here: #850 and #860
