### ISSUE TITLE
Trying to search for an issue results in blank white screen

### ISSUE THREAD

**Issue by wrongsyntax** [gitpoint/git-point#866]
| Question         | Response    |
| ---------------- | ----------- |
| Version?         | v1.6.0      |
| Devices tested?  | iPhone 6 |

---

## What Currently Happens?

Searching for an issue on any repository causes the app to show only a white screen, with no buttons or anything.

## What Do You Expect To Happen?

I expected issues that relate to the search to appear, and the rest of the app to function normally.

## My Reproduction Steps

1. Go to any repo
2. Tap `View all` on the issues
3. Search for anything
4. See results

**Comment by chinesedfan** [comment]
Refer to https://github.com/gitpoint/git-point/issues/751#issuecomment-443280057. It should be fixed by #856. And if everything goes well, there will be a new release next week.
