### ISSUE TITLE
Use App without Logging in

### ISSUE THREAD

**Issue by dpffxhad** [gitpoint/git-point#869]
## What Would You Like To Happen?
Browse without having to log in

**Comment by chinesedfan** [comment]
> We do not do anything with your GitHub information. After authenticating, the user's OAuth token is persisted directly on their device storage. It is not possible for us to retrieve that information. We never view a user's access token nor store it whatsoever.

Hi, do you concern about the security? We have made the above announcement and will always obey it. And without logging in, this app can keep very limited functionalities.
