### ISSUE TITLE
Can't star a repository from iOS device

### ISSUE THREAD

**Issue by thivatm** [gitpoint/git-point#876]
| Question         | Response    |
| ---------------- | ----------- |
| Version?         | v1.6.0      |
| Devices tested?  | iPhone 7 |

---

## What Currently Happens?
If you navigate to a repository and try to Star the repository you will get an error lie below.
![photo6253258146168547563](https://user-images.githubusercontent.com/25591638/57598671-c649f280-7571-11e9-963c-2d8334f2a2fc.jpg)

## What Do You Expect To Happen?

The user should be able to star the repository without an error.

## My Reproduction Steps

1. Navigate to any github repository
2. Press the options button in the top right corner
3. Press Star

**Comment by chinesedfan** [comment]
Fixed by #855 but not release.

**Comment by thivatm** [comment]
Closing the issue since the solution has been found already
