### ISSUE TITLE
Failed on iOS, xcode 10

### ISSUE THREAD

**Issue by dustturtle** [gitpoint/git-point#877]
Would you please upgrade the react-native version to support xcode10?

| Question         | Response    |
| ---------------- | ----------- |
| Version?         | v1.4.1      |
| Devices tested?  | iPhone 7... |

---

## My Reproduction Steps

1. XXX
1. XXX
1. XXX
1. XXX

**Comment by chinesedfan** [comment]
@dustturtle Can you give detailed error messages when running on Xcode 10?

**Comment by dustturtle** [comment]
I don't think anybody use this repo can run on xcode 10.2 without any change.

**Comment by chinesedfan** [comment]
So, can you paste the error screenshot?

**Comment by cloudy9101** [comment]
Don't know if the issue you got is as same as mine. Here is my screenshot when I run "yarn start:ios".  My OSX version is 10.14.5 and Xcode version is 10.2.1
![image](https://user-images.githubusercontent.com/5436425/58167633-7c36de80-7ce0-11e9-93a5-d0990d2e5295.png)

I find a solution.
First, follow [this](https://github.com/facebook/react-native/issues/23282#issuecomment-476439080).
Then open the './ios/GitPoint.xcodeproj' with Xcode and change the "File - Project Setting - Build System" to "Legacy Build System".
Then it works well for me.

**Comment by dustturtle** [comment]
cd node_modules/react-native/third-party/glog-0.3.4
../../scripts/ios-configure-glog.sh
This finally solved the problem "config.h not found".
And many thanks to @cloudy9101 , you really help a lot
