### ISSUE TITLE
Tool used in the main readme prototype

### ISSUE THREAD

**Issue by lucalves** [gitpoint/git-point#886]
Good morning!

I have a little question about the repository main README.

Which tool was made the prototype screenshots of the application?

For example, the tool I'm asking was used in this image [here](https://camo.githubusercontent.com/23000a0148c8b81e8afda51cef7b2c62ac4f2bac/687474703a2f2f692e696d6775722e636f6d2f486f774636614d2e706e67) in the main README.

Awaiting, thanks!

**Comment by chinesedfan** [comment]
I am not sure how @housseindjirdeh made those pictures. If they are real screenshots, you can run the app in Xcode simulators with Window->Show Device Bezels selected. Hope it can help you.

**Comment by lucalves** [comment]
Thanks @chinesedfan. If anyone knows the specific tool used, it would be very good.
