### ISSUE TITLE
Numbered list count bug

### ISSUE THREAD

**Issue by Antoine38660** [gitpoint/git-point#92]
Just found this weird one : 

`2.` on numbered list seems to be skipped...

Screenshots:
<img src="https://user-images.githubusercontent.com/9287184/28253035-b7282c0e-6a74-11e7-8a7c-3774af66e447.jpg" alt="Gitpoint" width="300"/>
Original from [Github.com](https://github.com) :
<img width="782" alt="Github" src="https://user-images.githubusercontent.com/9287184/28253036-b72886ae-6a74-11e7-833a-40759401046a.png">

**Comment by housseindjirdeh** [comment]
Interesting - not sure why this is happening

Good catch however! I do a bunch of conditional checks on the type of DOM element in `CommentListItem` for the comment HTML retrieved, so I may be doing something unnecessary with ordered lists.

**Comment by Antoine38660** [comment]
**Some more information after another test**
Initial markdown:
> 1. One
> 2. Two
> 3. Three
> 4. Four
> 5. Five
> 6. ...
<img src="https://user-images.githubusercontent.com/9287184/28279384-b01dcee6-6af6-11e7-8871-f6aded88352f.png" width="300" alt="screenshot" />

The bug exist for each _even number_.

**Comment by Antoine38660** [comment]
Found this one: https://github.com/jsdf/react-native-htmlview/issues/92 

I tried to update `react-native-htmlview` to 0.11.1 but it doesn't seem to be fixed... I'll reopen an issue there.
I also checked the `commentBodyAdjusted` (https://github.com/gitpoint/git-point/blob/master/src/components/comment-list-item.component.js#L283) but there is no problem with this generated DOM.

Seems definitely to be an `HTMLView` issue 😉

**Comment by housseindjirdeh** [comment]
Ah thanks a million for diving into this, looks like it's definitely something with the package.

Cheers let us know when you create an issue there and we'll link it here - in the meantime we can leave this ticket open until that gets resolved.

**Comment by Antoine38660** [comment]
Update: Just submitted a PR https://github.com/jsdf/react-native-htmlview/pull/131 to fix this one :smiley:
