### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by zhouxxiaolong** [gitpoint/git-point#94]
Unable to resolve module `config` from `/Users/github_clone/git-point-master/App.js`: Module does not exist in the module map.
How to steal?

**Comment by junedomingo** [comment]
Hi @zhouxxiaolong , try to clear the packager cache 
`sudo npm start --reset-cache`

**Comment by patw0929** [comment]
If you use yarn, run `yarn start -- --reset-cache`.

duplicate of #52.

**Comment by zhouxxiaolong** [comment]
Thanks,it’s working.

**Comment by zhouxxiaolong** [comment]
Thanks,it’s working.
