### ISSUE TITLE
I have some organizations, but not appeared

### ISSUE THREAD

**Issue by mingrammer** [gitpoint/git-point#96]
There are no any organizations on `ORGANIZATIONS` section on my profile page. But I have some orgs. 

It seems a bug? right?

**Comment by patw0929** [comment]
I can reproduce this issue on my phone.

It seems like that failed in `fetchAuthUserOrgs` action. 

Actually, I called the `https://api.github.com/user/orgs` API directly with the Authorization in header, it also responded me the empty array only.

Anyways, thanks for reporting this issue, and I'm still trying to figure out what happened.

**Comment by housseindjirdeh** [comment]
I just noticed this last night (funnily enough: the app on my device loads all my organizations just fine but when I run the app in the simulator now I don't see the GitPoint org 🤔 )

Thanks for opening this @mingrammer, weirdly enough you're right @patw0929 the API endpoint seems to be returning 2/3 of my organizations when I hit it directly and I'm not sure why either. Could be something on the server-side here.

**Comment by lex111** [comment]
Guys, I guessed the secret! :satisfied:

1. Go to this page https://github.com/settings/applications
2. Click here:
![image](https://user-images.githubusercontent.com/4408379/28280252-cf654934-6b2b-11e7-9703-11662229e2a2.png)
3. And we see this:
![image](https://user-images.githubusercontent.com/4408379/28280266-dcc45f34-6b2b-11e7-9d15-1c96976bf55f.png)

That's all. So that the ogranization is visible, you need to request permission! That's the whole secret. I only see the `github-beta` organization so only the request was made (although it seems it was originally, it does not matter).

Therefore, I propose to [use `fetchUserOrgs`](https://github.com/gitpoint/git-point/blob/master/src/api/index.js#L147) (instead of `fetchUuthUserOrgs`), which returns all the organizations **regardless of the request.** How are you? Will not we ask users to request access from all organizations? :smile:

**Comment by mingrammer** [comment]
@lex111 You're right. Once I've approved the some organizations I own to, the appears on git-point app. As you said, they should change the method for fetching the all orgs from an user even without any requesting.

**Comment by housseindjirdeh** [comment]
@lex111 you're a wizard ✨ Thank you so much for finding out what it was so fast. That explains why I was seeing the organization with the `GitPoint` Oauth application in my device but not with `GitPoint-Develop` when booting the simulator :)

I think that would work perfectly - but my only concern is setting the organization visibility to private.

![image](https://user-images.githubusercontent.com/12476932/28282193-a0d106b4-6af7-11e7-8aae-bf56b9068130.png)

[From the looks of it](https://developer.github.com/v3/orgs/#list-user-organizations), that endpoint only returns public memberships 😞 . Give it a shot nonetheless if you like and let me know if you do: but I think it may be a necessary workaround to give all your organizations access to `GitPoint`.

Please let me know what you folks think ❤️

**Comment by housseindjirdeh** [comment]
Also I notice that some organizations seemed to have automatically synced for me but others haven't and this may be an organization level security measure (maybe some organizations need you to first request access from them before integrating with a third party API?)

**Comment by lex111** [comment]
> From the looks of it, that endpoint only returns public memberships

@housseindjirdeh private organizations will not be visible, if you do not set them public visibility (if we get them through `fetchUserOrgs`), do you mean it?

**Comment by andrewda** [comment]
@housseindjirdeh 

> Also I notice that some organizations seemed to have automatically synced for me but others haven't and this may be an organization level security measure (maybe some organizations need you to first request access from them before integrating with a third party API?)

I believe what you're looking for is the third-party access setting which can be found at an organization's `Settings > Third-party access`. If access is restricted (I believe it is by default) then members have to request access. Administrators will always be allowed to grant access to any third-party app. If access is unrestricted, third-party access is automatically given to all apps that request it (i.e. no need to click "Grant Access"). So, for example, in @lex111's case, the `github-beta` organization has unrestricted third-party access.

(p.s. @lex111 how do I get in GitHub-Beta? :P)

**Comment by housseindjirdeh** [comment]
@lex111 yep exactly - even if I set an organization of mine as private visibility, I would still like to see it in my profile page in the app (although other folks cannot see it, does that make sense?)

@andrewda thanks a million, it's all making sense now

**Comment by lex111** [comment]
@housseindjirdeh now I understand, thanks for the clarification. At least I would list all public organizations to solve the current problem. Also, few will allow such a request:
![image](https://user-images.githubusercontent.com/4408379/28284319-3ab895e4-6b39-11e7-826e-806fd97ed96b.png)

We can make two requests (fetchUserOrgs + fetchAuthUserOrgs), and then merge the organizations, then we seem to have a full list of organizations, but is it really necessary? It's hard for me to decide this.

@andrewda earlier you could get through this [link](https://unity-preview.herokuapp.com/github-beta/unity-preview), now apparently not :/

**Comment by housseindjirdeh** [comment]
Yeah I was thinking the same thing - the thing is third party is restricted by default so I can see a lot of organizations requiring a request for approval.

Agreed we _could_ make two requests but again that's hoping that organization that requires third party approval is public (otherwise it still won't work). 

What I think we can do is have a little message under the organizations section list in the authenticated profile screen with something like "Can't see all your organizations? You may have to **request approval** for them" with the bolded text that links them to `https://github.com/settings/applications`. What do you think @lex111 @mingrammer @andrewda ? I personally think that's an acceptable workaround.

**Comment by andrewda** [comment]
There are definitely some organizations that (understandably) don't want to have lots of enabled third-party apps for privacy reasons. So I don't think it's an all-encompassing solution, but it would work for most orgs.

I actually think the best way to go about this, though, is to make two requests (as @lex111 pointed out). The first request (getting all of your public organizations) would be what others see when visiting your profile and doesn't require any manual approval from the user. Then, if accessing your own profile, make a second OAuth request to get the remaining organizations with private membership. That would maximize the number of shown repositories with the least amount of effort from the user.

**Comment by lex111** [comment]
@housseindjirdeh @andrewda I agree with all of you.

But tell me please how to make two requests better? Do `fetchAuthUserOrgs` send a request to get all the public organization, and after in `then` promise merge the organizations with private membership and remove the duplicates?

**Comment by housseindjirdeh** [comment]
Fair enough that approach works with me. @lex111 yep so we have fetchUserOrgs that does what it should do. In fetchAuthUserOrgs, you can try using Promise.all to hit both endpoints, merge the two results removing duplicates (combination of Set and .map maybe?). This way the completion event will only dispatch after both calls are finished.

**Comment by lex111** [comment]
@housseindjirdeh thank you, I [did](https://github.com/gitpoint/git-point/pull/115), but it did not work out through Set, although the solution is probably not very good, I'll be glad if you write how it can be improved. There was one additional addiction, is it very bad?
